import type { Problem, Lesson } from '../types';

// ===========================================================================
// bridge — Course 3 readiness: ratios/rates/%, integers, simple equations
// These go BEYOND 5th grade to show acceleration readiness for SRVUSD MAP.
// ===========================================================================

export const lessons: Lesson[] = [
  {
    domain: 'bridge', standard: '6.RP.1',
    title: 'Ratios, Rates & Percent',
    steps: [
      'A ratio compares two amounts, like 3 : 2 or 3 to 2.',
      'A unit rate is "per one" — divide to get it (miles per hour).',
      'Percent means "out of 100": 25% = 25/100 = 0.25.',
      'To find a percent of a number, multiply by its decimal form.',
    ],
    example: '20% of 50 = 0.20 × 50 = 10.',
    tip: 'Build a ratio table to scale up or down without mistakes.',
  },
  {
    domain: 'bridge', standard: '6.NS.5',
    title: 'Integers (Negative Numbers)',
    steps: [
      'Negative numbers are LEFT of 0 on the number line.',
      'The farther left, the smaller: −5 < −2.',
      'Adding a negative moves you left; subtracting a negative moves you right.',
      'Opposite numbers (3 and −3) are the same distance from 0.',
    ],
    example: '−3 + 5 = 2 (start at −3, move 5 right).',
    tip: 'Think of temperatures or money owed to picture negatives.',
  },
  {
    domain: 'bridge', standard: '6.EE.7',
    title: 'Solve Simple Equations',
    steps: [
      'A variable (like x) stands for an unknown number.',
      'Do the OPPOSITE operation to undo what is around x.',
      'Whatever you do to one side, do to the other side too.',
      'Check by plugging your answer back in.',
    ],
    example: 'x + 4 = 10 → subtract 4 from both sides → x = 6.',
    tip: 'Keep the equation "balanced" like a scale — both sides stay equal.',
  },
];

export const problems: Problem[] = [
  { id: 'br-1', domain: 'bridge', standard: '6.NS.5', tier: 1, type: 'multiple-choice',
    prompt: 'Which number is smaller: −4 or −1?',
    diagram: { kind: 'numberLine', min: -5, max: 5, ticks: 10, mark: -4 },
    choices: ['−4', '−1', 'They are equal', 'Cannot tell'], answer: '−4',
    hints: ['Farther left = smaller.'],
    explanation: '−4 is farther left on the number line, so −4 < −1.',
    solutions: [
      { title: 'Way 1: Number line', steps: [
        'Find −4 and −1 on the number line.',
        '−4 sits farther to the LEFT of zero than −1.',
        'Farther left always means smaller, so −4 is the smaller number.',
      ] },
      { title: 'Way 2: Think money owed', steps: [
        'Owing $4 leaves you with less money than owing $1.',
        'So −4 is less than −1, which means −4 is smaller.',
      ] },
    ] },
  { id: 'br-2', domain: 'bridge', standard: '6.RP.3', tier: 1, type: 'numeric',
    prompt: 'What is 50% of 30?', answer: '15', acceptable: ['15'],
    hints: ['50% = half.'],
    explanation: '50% means half, so 30 ÷ 2 = 15.',
    solutions: [
      { title: 'Way 1: Percent as a fraction', steps: [
        '50% is the same as one half.',
        'Half of 30 is 30 ÷ 2 = 15.',
        'So 50% of 30 is 15.',
      ] },
      { title: 'Way 2: Percent as a decimal', steps: [
        'Write 50% as the decimal 0.50.',
        'Multiply: 0.50 × 30 = 15.',
        'So 50% of 30 is 15.',
      ] },
      { title: 'Way 3: 10% chunks', steps: [
        '10% of 30 is 3.',
        '50% is five chunks of 10%, so 5 × 3 = 15.',
      ] },
    ] },
  { id: 'br-3', domain: 'bridge', standard: '6.EE.7', tier: 2, type: 'numeric',
    prompt: 'Solve for x:  x + 7 = 12', answer: '5', acceptable: ['5', 'x=5'],
    hints: ['Undo +7 by subtracting 7 from both sides.'],
    explanation: 'x + 7 = 12 → x = 12 − 7 = 5.',
    solutions: [
      { title: 'Way 1: Balance the equation', steps: [
        'The +7 is stuck to x, so undo it with the opposite: subtract 7.',
        'Subtract 7 from BOTH sides to keep the scale balanced.',
        '12 − 7 = 5, so x = 5. Check: 5 + 7 = 12. ✓',
      ] },
      { title: 'Way 2: What number makes it true?', steps: [
        'Ask: what number plus 7 gives 12?',
        'Count up from 7 to 12 — that is 5 steps.',
        'So x = 5.',
      ] },
    ] },
  { id: 'br-4', domain: 'bridge', standard: '6.RP.2', tier: 2, type: 'numeric',
    prompt: 'A car goes 120 miles in 2 hours. What is the unit rate in miles per hour?',
    answer: '60', acceptable: ['60', '60 mph'],
    hints: ['Per ONE hour: divide by 2.'],
    explanation: '120 ÷ 2 = 60 miles per hour.',
    solutions: [
      { title: 'Way 1: Divide to get per ONE', steps: [
        'Unit rate means miles for ONE hour.',
        'Divide miles by hours: 120 ÷ 2 = 60.',
        'The unit rate is 60 miles per hour.',
      ] },
      { title: 'Way 2: Ratio table', steps: [
        'Start the table: 120 miles in 2 hours.',
        'Halve both numbers to reach 1 hour: 60 miles in 1 hour.',
        'So the car goes 60 miles per hour.',
      ] },
    ] },
  { id: 'br-5', domain: 'bridge', standard: '6.NS.5', tier: 3, type: 'numeric',
    prompt: 'The temperature is −3°C and rises 8°C. What is the new temperature?',
    answer: '5', acceptable: ['5', '5°C', '5 C'],
    hints: ['Start at −3, move 8 right.'],
    explanation: '−3 + 8 = 5°C.',
    solutions: [
      { title: 'Way 1: Number line hops', steps: [
        'Start at −3 on the number line.',
        'Rising 8 degrees means hopping 8 to the RIGHT.',
        'You land on 5, so the new temperature is 5°C.',
      ] },
      { title: 'Way 2: Split the move at zero', steps: [
        'It takes 3 of the 8 degrees just to climb from −3 up to 0.',
        'That leaves 8 − 3 = 5 degrees above zero.',
        'So the new temperature is 5°C.',
      ] },
    ] },
  { id: 'br-6', domain: 'bridge', standard: '6.RP.3', tier: 3, type: 'numeric',
    prompt: 'A shirt costs $40. It is 25% off. What is the SALE price in dollars?',
    answer: '30', acceptable: ['30', '$30'],
    hints: ['25% of 40 = 0.25 × 40 = 10 off.', '40 − 10.'],
    explanation: '25% of 40 is 10; sale price = 40 − 10 = $30.',
    solutions: [
      { title: 'Way 1: Find the discount first', steps: [
        '25% is one quarter, and 40 ÷ 4 = 10, so the discount is $10.',
        'Subtract the discount: 40 − 10 = 30.',
        'The sale price is $30.',
      ] },
      { title: 'Way 2: Pay the percent that is LEFT', steps: [
        'If 25% comes off, you still pay 100% − 25% = 75%.',
        '75% of 40 is 0.75 × 40 = 30.',
        'The sale price is $30.',
      ] },
      { title: 'Way 3: 10% chunks', steps: [
        '10% of 40 is 4, so 20% is 8 and 5% is 2.',
        '25% off = 8 + 2 = 10 dollars off.',
        '40 − 10 = $30 sale price.',
      ] },
    ] },
  { id: 'br-7', domain: 'bridge', standard: '6.EE.7', tier: 4, type: 'numeric',
    prompt: 'Solve for x:  3x = 21', answer: '7', acceptable: ['7', 'x=7'],
    hints: ['3 times x = 21.', 'Divide both sides by 3.'],
    explanation: '3x = 21 → x = 21 ÷ 3 = 7.',
    solutions: [
      { title: 'Way 1: Balance the equation', steps: [
        '3x means 3 times x, so undo the ×3 with the opposite: divide by 3.',
        'Divide BOTH sides by 3: 21 ÷ 3 = 7.',
        'So x = 7. Check: 3 × 7 = 21. ✓',
      ] },
      { title: 'Way 2: Use a multiplication fact', steps: [
        'Ask: 3 times what number is 21?',
        'You know the fact 3 × 7 = 21.',
        'So x = 7.',
      ] },
    ] },
  { id: 'br-8', domain: 'bridge', standard: '6.EE.7', tier: 4, type: 'constructed',
    prompt: 'Solve 2x + 3 = 11 and explain each step.',
    answer: '4', acceptable: ['4', 'x=4'],
    hints: ['First undo +3 (subtract 3).', 'Then undo ×2 (divide by 2).'],
    explanation: 'Subtract 3 from both sides: 2x = 8. Divide both sides by 2: x = 4. Check: 2(4)+3 = 11. ✓',
    solutions: [
      { title: 'Way 1: Balance, undo in reverse order', steps: [
        'Undo the +3 first: subtract 3 from both sides, leaving 2x = 8.',
        'Undo the ×2 next: divide both sides by 2, so x = 4.',
        'Check by plugging in: 2 × 4 + 3 = 11. ✓',
      ] },
      { title: 'Way 2: Work backward from 11', steps: [
        'The machine did ×2 then +3 to reach 11, so reverse it.',
        'Undo +3: 11 − 3 = 8.',
        'Undo ×2: 8 ÷ 2 = 4, so x = 4.',
      ] },
    ] },
  { id: 'br-9', domain: 'bridge', standard: '6.RP.3', tier: 1, type: 'numeric',
    prompt: 'What is 10% of 70?', answer: '7', acceptable: ['7'],
    hints: ['10% = one tenth.'],
    explanation: '10% means one tenth: 70 ÷ 10 = 7.',
    solutions: [
      { title: 'Way 1: One tenth shortcut', steps: [
        '10% means one tenth of the number.',
        'One tenth of 70 is 70 ÷ 10 = 7.',
        'So 10% of 70 is 7.',
      ] },
      { title: 'Way 2: Percent as a decimal', steps: [
        'Write 10% as the decimal 0.10.',
        'Multiply: 0.10 × 70 = 7.',
        'So 10% of 70 is 7.',
      ] },
    ] },
  { id: 'br-10', domain: 'bridge', standard: '6.NS.6', tier: 2, type: 'numeric',
    prompt: 'What is the OPPOSITE of −6?', answer: '6', acceptable: ['6', '+6'],
    hints: ['Opposites are the same distance from 0, on the other side.'],
    explanation: 'The opposite of −6 is 6 — both are 6 steps from zero.',
    solutions: [
      { title: 'Way 1: Mirror across zero', steps: [
        '−6 sits 6 steps to the LEFT of zero.',
        'Its opposite sits 6 steps to the RIGHT of zero.',
        '6 steps right of zero is 6, so the opposite of −6 is 6.',
      ] },
      { title: 'Way 2: Flip the sign', steps: [
        'Opposite numbers have the same digits but the other sign.',
        'Flip the sign of −6 to get positive 6.',
        'So the opposite of −6 is 6.',
      ] },
    ] },
  { id: 'br-11', domain: 'bridge', standard: '6.RP.3', tier: 2, type: 'numeric',
    prompt: 'A smoothie recipe uses 2 cups of strawberries for every 3 cups of milk. With 6 cups of milk, how many cups of strawberries?',
    answer: '4', acceptable: ['4', '4 cups'],
    hints: ['Milk doubled (3 → 6).', 'Double the strawberries too.'],
    explanation: 'The ratio 2:3 scales up — milk doubled, so strawberries double: 2 × 2 = 4 cups.',
    solutions: [
      { title: 'Way 1: Scale factor', steps: [
        'Milk went from 3 cups to 6 cups — that is ×2.',
        'Keep the ratio fair: multiply strawberries by 2 also.',
        '2 × 2 = 4 cups of strawberries.',
      ] },
      { title: 'Way 2: Ratio table', steps: [
        'Row 1 of the table: 2 strawberries, 3 milk.',
        'Row 2: double both to get 4 strawberries, 6 milk.',
        '6 cups of milk lines up with 4 cups of strawberries.',
      ] },
      { title: 'Way 3: Strawberries per cup of milk', steps: [
        'The rate is 2 ÷ 3 = 2/3 cup of strawberries per cup of milk.',
        'For 6 cups of milk: 2/3 × 6 = 4.',
        'So you need 4 cups of strawberries.',
      ] },
    ] },
  { id: 'br-12', domain: 'bridge', standard: '6.EE.7', tier: 3, type: 'numeric',
    prompt: 'Solve for x:  x − 9 = 16', answer: '25', acceptable: ['25', 'x=25'],
    hints: ['Undo −9 by adding 9 to both sides.'],
    explanation: 'x − 9 = 16 → x = 16 + 9 = 25. Check: 25 − 9 = 16 ✓.',
    solutions: [
      { title: 'Way 1: Balance the equation', steps: [
        'The −9 is stuck to x, so undo it with the opposite: add 9.',
        'Add 9 to BOTH sides: x = 16 + 9 = 25.',
        'Check: 25 − 9 = 16. ✓ So x = 25.',
      ] },
      { title: 'Way 2: What number makes it true?', steps: [
        'Ask: what number loses 9 and still has 16 left?',
        'It must be 9 MORE than 16, so 16 + 9 = 25.',
        'So x = 25.',
      ] },
    ] },
  { id: 'br-13', domain: 'bridge', standard: '6.RP.3', tier: 3, type: 'numeric',
    prompt: 'What is 75% of 80?', answer: '60', acceptable: ['60'],
    hints: ['75% = 3/4.', '80 ÷ 4 = 20, then × 3.'],
    explanation: '75% = 3/4, and 3/4 × 80 = 60.',
    solutions: [
      { title: 'Way 1: Percent as a fraction', steps: [
        '75% is the same as 3/4.',
        'One quarter of 80 is 80 ÷ 4 = 20.',
        'Three quarters is 3 × 20 = 60, so 75% of 80 is 60.',
      ] },
      { title: 'Way 2: Percent as a decimal', steps: [
        'Write 75% as the decimal 0.75.',
        'Multiply: 0.75 × 80 = 60.',
        'So 75% of 80 is 60.',
      ] },
      { title: 'Way 3: Take 25% away', steps: [
        '25% of 80 is 80 ÷ 4 = 20.',
        '75% is everything except that quarter: 80 − 20 = 60.',
        'So 75% of 80 is 60.',
      ] },
    ] },
  { id: 'br-14', domain: 'bridge', standard: '6.NS.7', tier: 3, type: 'multiple-choice',
    prompt: 'Which temperature is the COLDEST?',
    choices: ['−7°C', '−2°C', '0°C', '3°C'], answer: '−7°C',
    hints: ['Coldest = smallest = farthest left on the number line.'],
    explanation: '−7 is farthest left on the number line, so −7°C is coldest.',
    solutions: [
      { title: 'Way 1: Number line', steps: [
        'Place −7, −2, 0, and 3 on a number line.',
        '−7 is farthest to the LEFT, so it is the smallest number.',
        'Smallest temperature = coldest, so −7°C is coldest.',
      ] },
      { title: 'Way 2: Compare negatives by distance below zero', steps: [
        'Any negative temperature is colder than 0°C or 3°C.',
        'Between −7 and −2, −7 is 7 degrees BELOW zero — deeper down.',
        'So −7°C is the coldest choice.',
      ] },
    ] },
  { id: 'br-15', domain: 'bridge', standard: '6.EE.7', tier: 4, type: 'numeric',
    prompt: 'Solve for x:  x ÷ 4 = 6', answer: '24', acceptable: ['24', 'x=24'],
    hints: ['Undo ÷4 by multiplying both sides by 4.'],
    explanation: 'x ÷ 4 = 6 → x = 6 × 4 = 24. Check: 24 ÷ 4 = 6 ✓.',
    solutions: [
      { title: 'Way 1: Balance the equation', steps: [
        'x is being divided by 4, so undo it with the opposite: multiply by 4.',
        'Multiply BOTH sides by 4: x = 6 × 4 = 24.',
        'Check: 24 ÷ 4 = 6. ✓ So x = 24.',
      ] },
      { title: 'Way 2: Think groups', steps: [
        'Some number split into 4 equal groups gives 6 in each group.',
        'Put the groups back together: 4 × 6 = 24.',
        'So x = 24.',
      ] },
    ] },
  { id: 'br-16', domain: 'bridge', standard: '6.RP.3', tier: 4, type: 'numeric',
    prompt: '15 is what PERCENT of 60?', answer: '25', acceptable: ['25', '25%'],
    hints: ['15/60 = 1/4.', 'Write 1/4 as a percent.'],
    explanation: '15/60 = 1/4 = 25%.',
    solutions: [
      { title: 'Way 1: Simplify the fraction', steps: [
        'Write the part over the whole: 15/60.',
        'Simplify: 15/60 = 1/4.',
        '1/4 as a percent is 25%, so 15 is 25% of 60.',
      ] },
      { title: 'Way 2: Divide to get a decimal', steps: [
        'Divide the part by the whole: 15 ÷ 60 = 0.25.',
        'Move the decimal two places right: 0.25 = 25%.',
        'So 15 is 25% of 60.',
      ] },
      { title: 'Way 3: Build with 10% and 5%', steps: [
        '10% of 60 is 6, so 20% is 12.',
        '5% of 60 is 3, and 12 + 3 = 15.',
        '20% + 5% = 25%, so 15 is 25% of 60.',
      ] },
    ] },
  { id: 'br-17', domain: 'bridge', standard: '6.RP.1', tier: 1, type: 'multiple-choice',
    prompt: 'A bag has 5 red marbles and 2 blue marbles. What is the ratio of red to blue?',
    choices: ['5 : 2', '2 : 5', '5 : 7', '2 : 7'], answer: '5 : 2',
    hints: ['Red to blue means red is named FIRST.', 'Count red (5), then blue (2).'],
    explanation: 'Red to blue lists red first, so the ratio is 5 : 2.',
    solutions: [
      { title: 'Way 1: Order matters', steps: [
        'The question says red TO blue, so red is written first.',
        'There are 5 red and 2 blue.',
        'So the ratio of red to blue is 5 : 2.',
      ] },
      { title: 'Way 2: Eliminate the traps', steps: [
        '5 : 7 and 2 : 7 compare a color to ALL 7 marbles — not asked.',
        '2 : 5 is blue to red — the wrong order.',
        'That leaves 5 : 2, red to blue.',
      ] },
    ] },
  { id: 'br-18', domain: 'bridge', standard: '6.NS.6', tier: 1, type: 'multiple-choice',
    prompt: 'Which number is marked on the number line?',
    diagram: { kind: 'numberLine', min: -5, max: 5, ticks: 10, mark: -3 },
    choices: ['−3', '3', '−2', '2'], answer: '−3',
    hints: ['The mark is LEFT of zero, so the number is negative.', 'Count the ticks from 0 to the mark.'],
    explanation: 'The mark is 3 ticks left of zero, which is −3.',
    solutions: [
      { title: 'Way 1: Count from zero', steps: [
        'Start at 0 and count ticks moving left: 1, 2, 3.',
        'Each tick left is one MORE negative.',
        'Three ticks left of zero is −3.',
      ] },
      { title: 'Way 2: Eliminate first', steps: [
        'The mark is left of 0, so it cannot be 3 or 2.',
        'It is 3 steps from zero, not 2.',
        'So the marked number is −3.',
      ] },
    ] },
  { id: 'br-19', domain: 'bridge', standard: '6.EE.1', tier: 1, type: 'numeric',
    prompt: 'What is the value of 2^4 (2 to the 4th power)?',
    answer: '16', acceptable: ['16'],
    hints: ['2^4 means 2 × 2 × 2 × 2, NOT 2 × 4.', 'Keep doubling: 2, 4, 8, ...'],
    explanation: '2^4 = 2 × 2 × 2 × 2 = 16.',
    solutions: [
      { title: 'Way 1: Repeated multiplication', steps: [
        '2^4 means multiply four 2s together: 2 × 2 × 2 × 2.',
        '2 × 2 = 4, then 4 × 2 = 8, then 8 × 2 = 16.',
        'So 2^4 = 16.',
      ] },
      { title: 'Way 2: Doubling pattern', steps: [
        '2^1 = 2, 2^2 = 4, 2^3 = 8 — each power doubles.',
        'Double once more: 2^4 = 16.',
        'Notice 2 × 4 = 8 would be wrong — exponents are not multiplying by 4.',
      ] },
    ] },
  { id: 'br-20', domain: 'bridge', standard: '6.RP.3', tier: 1, type: 'numeric',
    prompt: 'Write 25% as a DECIMAL.',
    answer: '0.25', acceptable: ['0.25', '.25'],
    hints: ['Percent means out of 100.', '25 out of 100 is 25 ÷ 100.'],
    explanation: '25% = 25/100 = 0.25.',
    solutions: [
      { title: 'Way 1: Out of 100', steps: [
        'Percent means out of 100, so 25% = 25/100.',
        '25 ÷ 100 = 0.25.',
        'So 25% as a decimal is 0.25.',
      ] },
      { title: 'Way 2: Move the decimal point', steps: [
        'To change a percent to a decimal, move the point TWO places left.',
        '25 becomes 0.25.',
        'So 25% = 0.25.',
      ] },
    ] },
  { id: 'br-21', domain: 'bridge', standard: '6.NS.5', tier: 1, type: 'multiple-choice',
    prompt: 'Which situation is best described by the number −20?',
    choices: ['Owing 20 dollars', 'Earning 20 dollars', 'Saving 20 dollars', 'Walking 20 steps'], answer: 'Owing 20 dollars',
    hints: ['Negative numbers describe amounts BELOW zero or losses.', 'Which choice is money going away?'],
    explanation: 'Owing money is a loss below zero, so owing $20 matches −20.',
    solutions: [
      { title: 'Way 1: Negative means below zero', steps: [
        'A negative number shows a loss or an amount below zero.',
        'Owing money means you are 20 dollars BELOW having nothing.',
        'So owing 20 dollars matches −20.',
      ] },
      { title: 'Way 2: Test each choice', steps: [
        'Earning and saving ADD money, so they would be +20.',
        'Walking 20 steps is just a count of 20.',
        'Only owing 20 dollars is a loss, so it is −20.',
      ] },
    ] },
  { id: 'br-22', domain: 'bridge', standard: '6.NS.7', tier: 1, type: 'multiple-choice',
    prompt: 'Which number is GREATER: −1 or −8?',
    diagram: { kind: 'numberLine', min: -10, max: 10, ticks: 20, mark: -8 },
    choices: ['−1', '−8', 'They are equal', 'Cannot tell'], answer: '−1',
    hints: ['Greater = farther RIGHT on the number line.', 'Which is closer to zero, −1 or −8?'],
    explanation: '−1 is to the right of −8 on the number line, so −1 > −8.',
    solutions: [
      { title: 'Way 1: Number line', steps: [
        'Find −1 and −8 on the number line.',
        '−1 is farther to the RIGHT, much closer to zero.',
        'Farther right means greater, so −1 is greater.',
      ] },
      { title: 'Way 2: Temperatures', steps: [
        'Think of −1°C and −8°C.',
        '−1°C is warmer — it is only 1 degree below freezing.',
        'Warmer means greater, so −1 > −8.',
      ] },
    ] },
  { id: 'br-23', domain: 'bridge', standard: '6.RP.2', tier: 1, type: 'numeric',
    prompt: '5 notebooks cost $10 in all. What is the cost per notebook in dollars?',
    answer: '2', acceptable: ['2', '$2', '2 dollars'],
    hints: ['Per notebook means for ONE notebook.', 'Split $10 equally among 5 notebooks.'],
    explanation: '10 ÷ 5 = $2 per notebook.',
    solutions: [
      { title: 'Way 1: Divide for the unit rate', steps: [
        'Unit rate means the cost of ONE notebook.',
        'Divide total cost by the count: 10 ÷ 5 = 2.',
        'Each notebook costs $2.',
      ] },
      { title: 'Way 2: Share it out', steps: [
        'Deal the 10 dollars into 5 equal piles, one per notebook.',
        'Each pile gets 2 dollars.',
        'So one notebook costs $2.',
      ] },
    ] },
  { id: 'br-24', domain: 'bridge', standard: '6.EE.2', tier: 1, type: 'multiple-choice',
    prompt: 'What is the value of x + 5 when x = 3?',
    choices: ['8', '2', '15', '35'], answer: '8',
    hints: ['Replace x with the number 3.', 'Then just add: 3 + 5.'],
    explanation: 'Substitute 3 for x: 3 + 5 = 8.',
    solutions: [
      { title: 'Way 1: Substitute', steps: [
        'The letter x is holding the number 3.',
        'Swap x for 3: the expression becomes 3 + 5.',
        '3 + 5 = 8.',
      ] },
      { title: 'Way 2: Spot the trap answers', steps: [
        '15 comes from multiplying 3 × 5 — but the sign is +.',
        '35 comes from gluing the digits together — not math.',
        'Adding correctly gives 3 + 5 = 8.',
      ] },
    ] },
  { id: 'br-25', domain: 'bridge', standard: '6.EE.1', tier: 2, type: 'multiple-choice',
    prompt: 'Which is GREATER: 2^5 or 5^2?',
    choices: ['2^5', '5^2', 'They are equal', 'Cannot tell'], answer: '2^5',
    hints: ['Compute each one — they are NOT the same.', '2^5 = 2 × 2 × 2 × 2 × 2 and 5^2 = 5 × 5.'],
    explanation: '2^5 = 32 and 5^2 = 25, so 2^5 is greater.',
    solutions: [
      { title: 'Way 1: Compute both values', steps: [
        '2^5 = 2 × 2 × 2 × 2 × 2 = 32.',
        '5^2 = 5 × 5 = 25.',
        '32 > 25, so 2^5 is greater.',
      ] },
      { title: 'Way 2: Doubling list vs one square', steps: [
        'Powers of 2: 2, 4, 8, 16, 32 — five doublings reach 32.',
        'Squaring 5 only gives 25.',
        'So 2^5 (32) beats 5^2 (25).',
      ] },
    ] },
  { id: 'br-26', domain: 'bridge', standard: '6.NS.7', tier: 2, type: 'multiple-choice',
    prompt: 'Which list shows the integers in order from LEAST to greatest?',
    choices: ['−6, −2, 0, 3', '0, −2, 3, −6', '−2, −6, 0, 3', '3, 0, −2, −6'], answer: '−6, −2, 0, 3',
    hints: ['Least to greatest goes left to right on a number line.', 'The most negative number comes first.'],
    explanation: 'From left to right on a number line: −6, −2, 0, 3.',
    solutions: [
      { title: 'Way 1: Number line sweep', steps: [
        'Place −6, −2, 0, and 3 on a number line.',
        'Read them from left to right: −6, then −2, then 0, then 3.',
        'So the correct order is −6, −2, 0, 3.',
      ] },
      { title: 'Way 2: Negatives first, by size', steps: [
        'Negatives are always less than 0 and the positives.',
        'Among negatives, −6 is deeper below zero than −2, so −6 is least.',
        'Order: −6, −2, 0, 3.',
      ] },
    ] },
  { id: 'br-27', domain: 'bridge', standard: '6.RP.3', tier: 2, type: 'numeric',
    prompt: 'What is 20% of 45?',
    answer: '9', acceptable: ['9'],
    hints: ['20% = 0.20 = one fifth.', 'Try 10% of 45 first, then double it.'],
    explanation: '20% of 45 = 0.20 × 45 = 9.',
    solutions: [
      { title: 'Way 1: Percent as a decimal', steps: [
        'Write 20% as the decimal 0.20.',
        'Multiply: 0.20 × 45 = 9.',
        'So 20% of 45 is 9.',
      ] },
      { title: 'Way 2: Percent as a fraction', steps: [
        '20% is the same as 1/5.',
        'One fifth of 45 is 45 ÷ 5 = 9.',
        'So 20% of 45 is 9.',
      ] },
      { title: 'Way 3: 10% chunks', steps: [
        '10% of 45 is 4.5.',
        '20% is double that: 4.5 × 2 = 9.',
      ] },
    ] },
  { id: 'br-28', domain: 'bridge', standard: '6.NS.7', tier: 2, type: 'numeric',
    prompt: 'What is |−9|, the absolute value of −9?',
    diagram: { kind: 'numberLine', min: -10, max: 10, ticks: 20, mark: -9 },
    answer: '9', acceptable: ['9', '+9'],
    hints: ['Absolute value asks: how FAR from zero?', 'Distance is never negative.'],
    explanation: '−9 is 9 units from zero, so |−9| = 9.',
    solutions: [
      { title: 'Way 1: Distance from zero', steps: [
        'Absolute value means distance from 0 on the number line.',
        'Count the hops from −9 back to 0: there are 9 hops.',
        'So |−9| = 9.',
      ] },
      { title: 'Way 2: Drop the sign', steps: [
        'Distance is never negative, so absolute value is never negative.',
        'For any negative number, the absolute value is its opposite.',
        'The opposite of −9 is 9, so |−9| = 9.',
      ] },
    ] },
  { id: 'br-29', domain: 'bridge', standard: '6.RP.1', tier: 2, type: 'multiple-choice',
    prompt: 'Which ratio is EQUIVALENT to 2 : 3?',
    choices: ['4 : 6', '3 : 2', '2 : 6', '6 : 4'], answer: '4 : 6',
    hints: ['Multiply BOTH parts of 2 : 3 by the same number.', 'Try multiplying both parts by 2.'],
    explanation: 'Doubling both parts of 2 : 3 gives 4 : 6, an equivalent ratio.',
    solutions: [
      { title: 'Way 1: Scale both parts', steps: [
        'Equivalent ratios multiply BOTH parts by the same number.',
        '2 × 2 = 4 and 3 × 2 = 6.',
        'So 4 : 6 is equivalent to 2 : 3.',
      ] },
      { title: 'Way 2: Check each choice', steps: [
        '3 : 2 and 6 : 4 flip the order — those match 3 : 2 instead.',
        '2 : 6 only multiplied the second part, so it is unfair.',
        '4 : 6 doubles both parts, so it is the match.',
      ] },
    ] },
  { id: 'br-30', domain: 'bridge', standard: '6.EE.2', tier: 2, type: 'numeric',
    prompt: 'Evaluate 3x + 2 when x = 4.',
    answer: '14', acceptable: ['14'],
    hints: ['3x means 3 TIMES x.', 'Multiply first, then add 2.'],
    explanation: '3 × 4 = 12, then 12 + 2 = 14.',
    solutions: [
      { title: 'Way 1: Substitute and follow order of operations', steps: [
        'Replace x with 4: the expression becomes 3 × 4 + 2.',
        'Multiply first: 3 × 4 = 12.',
        'Then add: 12 + 2 = 14.',
      ] },
      { title: 'Way 2: Think in groups', steps: [
        '3x means three groups of x, so three groups of 4: 4 + 4 + 4 = 12.',
        'Add 2 more: 12 + 2 = 14.',
        'So 3x + 2 equals 14 when x = 4.',
      ] },
    ] },
  { id: 'br-31', domain: 'bridge', standard: '6.NS.5', tier: 2, type: 'numeric',
    prompt: 'A diver is at an elevation of −12 feet and rises 7 feet. What is the new elevation in feet?',
    diagram: { kind: 'numberLine', min: -15, max: 5, ticks: 20, mark: -12 },
    answer: '-5', acceptable: ['-5', '−5', '-5 feet'],
    hints: ['Start at −12 and move 7 toward zero.', 'Rising means moving RIGHT (up) on the number line.'],
    explanation: '−12 + 7 = −5 feet.',
    solutions: [
      { title: 'Way 1: Number line hops', steps: [
        'Start at −12 on the number line.',
        'Rising 7 feet means 7 hops toward zero: −11, −10, −9, −8, −7, −6, −5.',
        'The diver is now at −5 feet.',
      ] },
      { title: 'Way 2: How far below zero is left?', steps: [
        'The diver was 12 feet below the surface.',
        'Rising 7 feet leaves 12 − 7 = 5 feet still below.',
        'Below zero means negative, so the elevation is −5 feet.',
      ] },
    ] },
  { id: 'br-32', domain: 'bridge', standard: '6.RP.2', tier: 2, type: 'multiple-choice',
    prompt: 'Which is the BETTER deal: 3 pens for $6 or 5 pens for $15?',
    choices: ['3 pens for $6', '5 pens for $15', 'They cost the same per pen', 'Cannot tell'], answer: '3 pens for $6',
    hints: ['Find the price of ONE pen in each deal.', '6 ÷ 3 versus 15 ÷ 5.'],
    explanation: '3 for $6 is $2 per pen; 5 for $15 is $3 per pen — $2 wins.',
    solutions: [
      { title: 'Way 1: Unit price', steps: [
        'Deal 1: 6 ÷ 3 = $2 per pen.',
        'Deal 2: 15 ÷ 5 = $3 per pen.',
        '$2 is cheaper, so 3 pens for $6 is the better deal.',
      ] },
      { title: 'Way 2: Make the pen counts match', steps: [
        'Scale both deals to 15 pens.',
        'Deal 1: 3 pens for $6, so 15 pens cost 5 × 6 = $30.',
        'Deal 2: 15 pens cost 3 × 15 = $45.',
        '$30 < $45, so 3 pens for $6 is better.',
      ] },
    ] },
  { id: 'br-33', domain: 'bridge', standard: '6.EE.7', tier: 2, type: 'numeric',
    prompt: 'Solve for x:  x + 13 = 30',
    answer: '17', acceptable: ['17', 'x=17'],
    hints: ['Undo +13 with the opposite operation.', 'Subtract 13 from both sides.'],
    explanation: 'x = 30 − 13 = 17.',
    solutions: [
      { title: 'Way 1: Balance the equation', steps: [
        'Subtract 13 from BOTH sides to undo the +13.',
        '30 − 13 = 17, so x = 17.',
        'Check: 17 + 13 = 30. ✓',
      ] },
      { title: 'Way 2: Count up', steps: [
        'Ask: 13 plus what reaches 30?',
        'From 13, add 7 to reach 20, then 10 more to reach 30.',
        '7 + 10 = 17, so x = 17.',
      ] },
    ] },
  { id: 'br-34', domain: 'bridge', standard: '6.RP.3', tier: 2, type: 'numeric',
    prompt: 'Write 3/5 as a PERCENT (just the number).',
    answer: '60', acceptable: ['60', '60%'],
    hints: ['Make the denominator 100.', 'Multiply top and bottom by 20.'],
    explanation: '3/5 = 60/100 = 60%.',
    solutions: [
      { title: 'Way 1: Make it out of 100', steps: [
        'Percent means out of 100, so turn fifths into hundredths.',
        'Multiply top and bottom by 20: 3/5 = 60/100.',
        '60/100 is 60%.',
      ] },
      { title: 'Way 2: Decimal first', steps: [
        'Divide: 3 ÷ 5 = 0.6.',
        'Move the decimal two places right: 0.6 = 60%.',
        'So 3/5 = 60%.',
      ] },
      { title: 'Way 3: One fifth at a time', steps: [
        '1/5 of 100% is 20%.',
        '3/5 is three of those: 3 × 20% = 60%.',
      ] },
    ] },
  { id: 'br-35', domain: 'bridge', standard: '6.NS.6', tier: 2, type: 'multiple-choice',
    prompt: 'The point 4 is marked on the number line. What is the OPPOSITE of 4?',
    diagram: { kind: 'numberLine', min: -5, max: 5, ticks: 10, mark: 4 },
    choices: ['−4', '4', '0', '8'], answer: '−4',
    hints: ['Opposites sit on opposite sides of zero.', 'Same distance from 0, other direction.'],
    explanation: 'The opposite of 4 is −4 — same distance from zero, other side.',
    solutions: [
      { title: 'Way 1: Mirror across zero', steps: [
        '4 is 4 steps to the RIGHT of zero.',
        'Its opposite is 4 steps to the LEFT of zero.',
        'That point is −4.',
      ] },
      { title: 'Way 2: Flip the sign', steps: [
        'Taking the opposite flips the sign of a number.',
        'Positive 4 becomes negative 4.',
        'So the opposite of 4 is −4.',
      ] },
    ] },
  { id: 'br-36', domain: 'bridge', standard: '6.EE.1', tier: 2, type: 'multiple-choice',
    prompt: 'What does 10^3 mean?',
    choices: ['10 × 10 × 10', '10 × 3', '10 + 10 + 10', '10 + 3'], answer: '10 × 10 × 10',
    hints: ['The exponent counts how many times the BASE is multiplied.', 'Three copies of 10, all multiplied.'],
    explanation: '10^3 means 10 × 10 × 10, which equals 1000.',
    solutions: [
      { title: 'Way 1: Exponent counts the factors', steps: [
        'The base is 10 and the exponent is 3.',
        'The exponent says: use 10 as a factor 3 times.',
        'So 10^3 = 10 × 10 × 10 (which is 1000).',
      ] },
      { title: 'Way 2: Size check', steps: [
        '10 × 3 and 10 + 10 + 10 both equal only 30, and 10 + 3 is 13.',
        'But 10^3 is 1000 — way bigger.',
        'Only 10 × 10 × 10 gives 1000, so that is the meaning.',
      ] },
    ] },
  { id: 'br-37', domain: 'bridge', standard: '6.RP.3', tier: 2, type: 'numeric',
    prompt: 'A recipe uses 3 cups of flour to make 12 muffins. How many cups of flour are needed for 36 muffins?',
    answer: '9', acceptable: ['9', '9 cups'],
    hints: ['How many times bigger is 36 than 12?', 'Multiply the flour by that same number.'],
    explanation: '36 muffins is 3 times 12, so flour triples: 3 × 3 = 9 cups.',
    solutions: [
      { title: 'Way 1: Scale factor', steps: [
        'Muffins went from 12 to 36, and 36 ÷ 12 = 3.',
        'Multiply the flour by the same factor: 3 × 3 = 9.',
        'You need 9 cups of flour.',
      ] },
      { title: 'Way 2: Ratio table', steps: [
        'Row 1: 3 cups → 12 muffins.',
        'Row 2: 6 cups → 24 muffins.',
        'Row 3: 9 cups → 36 muffins, so the answer is 9 cups.',
      ] },
      { title: 'Way 3: Muffins per cup', steps: [
        'Each cup of flour makes 12 ÷ 3 = 4 muffins.',
        'For 36 muffins: 36 ÷ 4 = 9.',
        'So 9 cups of flour are needed.',
      ] },
    ] },
  { id: 'br-38', domain: 'bridge', standard: '6.NS.5', tier: 2, type: 'multiple-choice',
    prompt: 'The temperature is 4°C and DROPS 9°C. What is the new temperature?',
    diagram: { kind: 'numberLine', min: -10, max: 10, ticks: 20, mark: 4 },
    choices: ['−5°C', '5°C', '−13°C', '13°C'], answer: '−5°C',
    hints: ['Dropping means moving LEFT on the number line.', 'It takes 4 degrees just to reach 0 — how many are left?'],
    explanation: '4 − 9 = −5, so the new temperature is −5°C.',
    solutions: [
      { title: 'Way 1: Number line hops', steps: [
        'Start at 4 and hop 9 to the left.',
        'The first 4 hops land on 0.',
        'The other 5 hops go below zero, landing on −5°C.',
      ] },
      { title: 'Way 2: Compare the sizes', steps: [
        'The drop (9) is bigger than the start (4), so the result is negative.',
        'How far negative? 9 − 4 = 5 degrees below zero.',
        'So the new temperature is −5°C.',
      ] },
    ] },
  { id: 'br-39', domain: 'bridge', standard: '6.EE.5', tier: 2, type: 'multiple-choice',
    prompt: 'Which value of x makes the equation x − 5 = 9 TRUE?',
    choices: ['14', '4', '45', '−4'], answer: '14',
    hints: ['Try plugging each choice into x − 5.', 'Or undo the −5 by adding 5.'],
    explanation: '14 − 5 = 9, so x = 14 makes the equation true.',
    solutions: [
      { title: 'Way 1: Test the choices', steps: [
        'Try 14: 14 − 5 = 9. ✓ That works.',
        'Try 4: 4 − 5 = −1. ✗',
        'So x = 14 is the value that makes it true.',
      ] },
      { title: 'Way 2: Undo with the opposite', steps: [
        'x lost 5 and ended at 9.',
        'Add the 5 back: 9 + 5 = 14.',
        'So x = 14. Check: 14 − 5 = 9. ✓',
      ] },
    ] },
  { id: 'br-40', domain: 'bridge', standard: '6.RP.3', tier: 3, type: 'numeric',
    prompt: 'What is 30% of 90?',
    answer: '27', acceptable: ['27'],
    hints: ['Find 10% of 90 first.', 'Then take three of those chunks.'],
    explanation: '30% of 90 = 0.30 × 90 = 27.',
    solutions: [
      { title: 'Way 1: 10% chunks', steps: [
        '10% of 90 is 9.',
        '30% is three chunks of 10%: 3 × 9 = 27.',
        'So 30% of 90 is 27.',
      ] },
      { title: 'Way 2: Percent as a decimal', steps: [
        'Write 30% as 0.30.',
        'Multiply: 0.30 × 90 = 27.',
        'So 30% of 90 is 27.',
      ] },
      { title: 'Way 3: Percent as a fraction', steps: [
        '30% = 30/100 = 3/10.',
        '3/10 of 90 is 90 ÷ 10 × 3 = 27.',
      ] },
    ] },
  { id: 'br-41', domain: 'bridge', standard: '6.RP.2', tier: 3, type: 'multiple-choice',
    prompt: 'Which is the BETTER deal: 12 ounces of juice for $3.60 or 16 ounces for $4.00?',
    choices: ['12 ounces for $3.60', '16 ounces for $4.00', 'Same price per ounce', 'Cannot tell'], answer: '16 ounces for $4.00',
    hints: ['Find the price of ONE ounce in each deal.', '3.60 ÷ 12 versus 4.00 ÷ 16.'],
    explanation: '$3.60 ÷ 12 = 30¢ per ounce but $4.00 ÷ 16 = 25¢ per ounce, so 16 oz wins.',
    solutions: [
      { title: 'Way 1: Unit price', steps: [
        'Deal 1: 3.60 ÷ 12 = $0.30 per ounce.',
        'Deal 2: 4.00 ÷ 16 = $0.25 per ounce.',
        '25 cents beats 30 cents, so 16 ounces for $4.00 is better.',
      ] },
      { title: 'Way 2: Make the amounts match', steps: [
        'Scale both deals to 48 ounces.',
        'Deal 1: 48 oz costs 4 × 3.60 = $14.40.',
        'Deal 2: 48 oz costs 3 × 4.00 = $12.00.',
        '$12.00 is cheaper, so 16 ounces for $4.00 is the better deal.',
      ] },
    ] },
  { id: 'br-42', domain: 'bridge', standard: '6.NS.7', tier: 3, type: 'numeric',
    prompt: 'How far apart are −4 and 3 on the number line?',
    diagram: { kind: 'numberLine', min: -5, max: 5, ticks: 10, mark: -4 },
    answer: '7', acceptable: ['7', '7 units'],
    hints: ['Count the hops from −4 all the way to 3.', 'Split the trip at zero: −4 to 0, then 0 to 3.'],
    explanation: '−4 to 0 is 4 units and 0 to 3 is 3 units: 4 + 3 = 7.',
    solutions: [
      { title: 'Way 1: Split the trip at zero', steps: [
        'From −4 up to 0 is 4 units.',
        'From 0 up to 3 is 3 more units.',
        'Total distance: 4 + 3 = 7 units.',
      ] },
      { title: 'Way 2: Absolute values', steps: [
        '−4 and 3 are on OPPOSITE sides of zero.',
        'Add their distances from zero: |−4| + |3| = 4 + 3.',
        'The distance is 7.',
      ] },
    ] },
  { id: 'br-43', domain: 'bridge', standard: '6.EE.7', tier: 3, type: 'multiple-choice',
    prompt: 'Solve for x:  5x = 45',
    choices: ['x = 9', 'x = 40', 'x = 50', 'x = 225'], answer: 'x = 9',
    hints: ['5x means 5 TIMES x.', 'Undo ×5 by dividing both sides by 5.'],
    explanation: '5x = 45 → x = 45 ÷ 5 = 9.',
    solutions: [
      { title: 'Way 1: Balance the equation', steps: [
        'x is multiplied by 5, so divide BOTH sides by 5.',
        '45 ÷ 5 = 9, so x = 9.',
        'Check: 5 × 9 = 45. ✓',
      ] },
      { title: 'Way 2: Use a multiplication fact', steps: [
        'Ask: 5 times what number is 45?',
        'You know 5 × 9 = 45.',
        'So x = 9 — not 40 (that subtracts) or 225 (that multiplies).',
      ] },
    ] },
  { id: 'br-44', domain: 'bridge', standard: '6.RP.3', tier: 3, type: 'numeric',
    prompt: 'A video game costs $60. It is on sale for 20% off. What is the SALE price in dollars?',
    answer: '48', acceptable: ['48', '$48', '48 dollars'],
    hints: ['First find 20% of 60.', 'Then subtract that discount from 60.'],
    explanation: '20% of 60 is 12, so the sale price is 60 − 12 = $48.',
    solutions: [
      { title: 'Way 1: Find the discount first', steps: [
        '20% of 60 is 0.20 × 60 = 12, so $12 comes off.',
        'Subtract: 60 − 12 = 48.',
        'The sale price is $48.',
      ] },
      { title: 'Way 2: Pay the percent that is LEFT', steps: [
        'With 20% off, you pay 100% − 20% = 80%.',
        '80% of 60 is 0.80 × 60 = 48.',
        'The sale price is $48.',
      ] },
      { title: 'Way 3: 10% chunks', steps: [
        '10% of 60 is 6, so 20% is 12.',
        'Take $12 off: 60 − 12 = $48.',
      ] },
    ] },
  { id: 'br-45', domain: 'bridge', standard: '6.EE.2', tier: 3, type: 'numeric',
    prompt: 'Evaluate 2x − 7 when x = 10.',
    answer: '13', acceptable: ['13'],
    hints: ['2x means 2 TIMES x.', 'Multiply first, then subtract 7.'],
    explanation: '2 × 10 = 20, then 20 − 7 = 13.',
    solutions: [
      { title: 'Way 1: Substitute and compute', steps: [
        'Replace x with 10: the expression becomes 2 × 10 − 7.',
        'Multiply first: 2 × 10 = 20.',
        'Then subtract: 20 − 7 = 13.',
      ] },
      { title: 'Way 2: Number machine', steps: [
        'Picture a machine: input x, double it, then take away 7.',
        'Input 10 → doubles to 20 → take away 7 → 13.',
        'So the value is 13.',
      ] },
    ] },
  { id: 'br-46', domain: 'bridge', standard: '6.NS.7', tier: 3, type: 'multiple-choice',
    prompt: 'Which statement is TRUE?',
    choices: ['−3 > −7', '−7 > −3', '−3 > 0', '−3 = 3'], answer: '−3 > −7',
    hints: ['Greater = farther right on the number line.', 'Which of −3 and −7 is closer to zero?'],
    explanation: '−3 is to the right of −7, so −3 > −7 is true.',
    solutions: [
      { title: 'Way 1: Number line', steps: [
        'Place −3 and −7 on a number line.',
        '−3 is farther RIGHT (closer to zero), so −3 is greater.',
        'That makes −3 > −7 the true statement.',
      ] },
      { title: 'Way 2: Eliminate the false ones', steps: [
        '−3 > 0 is false — negatives are below zero.',
        '−3 = 3 is false — they are opposites, not equals.',
        '−7 > −3 is backwards, so the true one is −3 > −7.',
      ] },
    ] },
  { id: 'br-47', domain: 'bridge', standard: '6.RP.3', tier: 3, type: 'numeric',
    prompt: '18 is what PERCENT of 72? (just the number)',
    answer: '25', acceptable: ['25', '25%'],
    hints: ['Write the part over the whole: 18/72.', 'Simplify that fraction, then turn it into a percent.'],
    explanation: '18/72 = 1/4 = 25%.',
    solutions: [
      { title: 'Way 1: Simplify the fraction', steps: [
        'Part over whole: 18/72.',
        'Divide top and bottom by 18: 18/72 = 1/4.',
        '1/4 = 25%, so 18 is 25% of 72.',
      ] },
      { title: 'Way 2: Divide to get a decimal', steps: [
        '18 ÷ 72 = 0.25.',
        'Move the decimal two places right: 0.25 = 25%.',
        'So 18 is 25% of 72.',
      ] },
      { title: 'Way 3: Quarter check', steps: [
        'Ask: how many 18s fit in 72? 72 ÷ 18 = 4.',
        'So 18 is exactly one quarter of 72.',
        'One quarter is 25%.',
      ] },
    ] },
  { id: 'br-48', domain: 'bridge', standard: '6.EE.1', tier: 3, type: 'multiple-choice',
    prompt: 'Which expression has a value of 64?',
    choices: ['2^6', '4^2', '8^1', '2^4'], answer: '2^6',
    hints: ['Compute each power one at a time.', 'Keep doubling for the powers of 2: 2, 4, 8, 16, ...'],
    explanation: '2^6 = 64, while 4^2 = 16, 8^1 = 8, and 2^4 = 16.',
    solutions: [
      { title: 'Way 1: Compute every choice', steps: [
        '2^6 = 2 × 2 × 2 × 2 × 2 × 2 = 64.',
        '4^2 = 16, 8^1 = 8, and 2^4 = 16.',
        'Only 2^6 equals 64.',
      ] },
      { title: 'Way 2: Doubling ladder', steps: [
        'Climb the powers of 2: 2, 4, 8, 16, 32, 64.',
        'That took 6 doublings, so 64 = 2^6.',
        'So 2^6 is the expression worth 64.',
      ] },
    ] },
  { id: 'br-49', domain: 'bridge', standard: '6.NS.5', tier: 3, type: 'numeric',
    prompt: 'Liam owes his sister $15, so his balance is −15 dollars. He pays back $9. What is his balance now?',
    answer: '-6', acceptable: ['-6', '−6', '-$6', '-6 dollars'],
    hints: ['Paying back debt moves the balance TOWARD zero.', 'He still owes 15 − 9 dollars.'],
    explanation: '−15 + 9 = −6, so he still owes $6.',
    solutions: [
      { title: 'Way 1: How much debt is left?', steps: [
        'He owed 15 dollars and paid back 9.',
        'Debt left: 15 − 9 = 6 dollars still owed.',
        'Owing 6 dollars is a balance of −6.',
      ] },
      { title: 'Way 2: Number line hops', steps: [
        'Start at −15 on a number line.',
        'Paying back $9 moves him 9 steps toward zero.',
        '−15 + 9 = −6, so his balance is −6 dollars.',
      ] },
    ] },
  { id: 'br-50', domain: 'bridge', standard: '6.RP.3', tier: 3, type: 'multiple-choice',
    prompt: 'Which is equivalent to 0.4?',
    choices: ['40%', '4%', '0.4%', '44%'], answer: '40%',
    hints: ['Write 0.4 as a fraction out of 100.', '0.4 = 0.40 = 40 hundredths.'],
    explanation: '0.4 = 40/100 = 40%.',
    solutions: [
      { title: 'Way 1: Hundredths', steps: [
        '0.4 is the same as 0.40, which is 40 hundredths.',
        '40 hundredths means 40 out of 100.',
        'Out of 100 is percent, so 0.4 = 40%.',
      ] },
      { title: 'Way 2: Move the decimal point', steps: [
        'To change a decimal to a percent, move the point TWO places right.',
        '0.4 → 40.',
        'So 0.4 = 40%, not 4%.',
      ] },
    ] },
  { id: 'br-51', domain: 'bridge', standard: '6.NS.7', tier: 3, type: 'constructed',
    prompt: 'Sam says −8 > −3 because 8 > 3. Explain the mistake.',
    answer: 'left', acceptable: ['number line', 'smaller', 'less', 'negative', 'farther'],
    hints: ['Picture −8 and −3 on a number line.', 'For negatives, a bigger digit means farther LEFT of zero.'],
    explanation: '−8 is farther left of zero than −3, so −8 is actually SMALLER: −8 < −3.',
    solutions: [
      { title: 'Way 1: Number line', steps: [
        'On a number line, −8 sits farther LEFT of zero than −3.',
        'Farther left always means smaller, even though the digit 8 is bigger.',
        'So the truth is −8 < −3; Sam used the rule for positives on negatives.',
      ] },
      { title: 'Way 2: Money owed', steps: [
        'Owing $8 leaves you worse off than owing $3.',
        'Worse off means a smaller number, so −8 is less than −3.',
        'Sam compared the digits but forgot the negative signs flip the order.',
      ] },
    ] },
  { id: 'br-52', domain: 'bridge', standard: '6.RP.1', tier: 3, type: 'multiple-choice',
    prompt: 'The ratio of boys to girls in a class is 3 : 4. There are 21 students in all. How many boys are there?',
    choices: ['9', '12', '3', '7'], answer: '9',
    hints: ['3 : 4 makes 3 + 4 = 7 equal parts.', 'Find the size of one part: 21 ÷ 7.'],
    explanation: '21 ÷ 7 parts = 3 per part, and boys have 3 parts: 3 × 3 = 9.',
    solutions: [
      { title: 'Way 1: Count the parts', steps: [
        'The ratio 3 : 4 splits the class into 3 + 4 = 7 equal parts.',
        'Each part holds 21 ÷ 7 = 3 students.',
        'Boys get 3 parts: 3 × 3 = 9 boys.',
      ] },
      { title: 'Way 2: Ratio table', steps: [
        '3 boys : 4 girls means 7 students total.',
        'Double it: 6 : 8 is 14 total. Triple it: 9 : 12 is 21 total.',
        '21 matches, so there are 9 boys.',
      ] },
    ] },
  { id: 'br-53', domain: 'bridge', standard: '6.NS.6', tier: 3, type: 'multiple-choice',
    prompt: 'A point is at −2.5 on the number line. Between which two integers does it sit?',
    diagram: { kind: 'numberLine', min: -5, max: 5, ticks: 10, mark: -2.5 },
    choices: ['−3 and −2', '−2 and −1', '2 and 3', '−4 and −3'], answer: '−3 and −2',
    hints: ['−2.5 is half a step PAST −2, moving left.', 'Going left from −2, the next integer is −3.'],
    explanation: '−2.5 sits halfway between −3 and −2.',
    solutions: [
      { title: 'Way 1: Walk the number line', steps: [
        'Start at −2 and move half a step LEFT to reach −2.5.',
        'Keep going left and the next whole number is −3.',
        'So −2.5 sits between −3 and −2.',
      ] },
      { title: 'Way 2: Mirror the positive side', steps: [
        'On the positive side, 2.5 sits between 2 and 3.',
        'Reflect across zero: −2.5 sits between −2 and −3.',
        'Written least to greatest, that is between −3 and −2.',
      ] },
    ] },
  { id: 'br-54', domain: 'bridge', standard: '6.EE.1', tier: 3, type: 'constructed',
    prompt: 'Mia says 2^3 = 6 because 2 × 3 = 6. Explain her mistake and give the correct value.',
    answer: '8', acceptable: ['repeated', 'multiply', '2 x 2 x 2', 'factor', 'eight'],
    hints: ['The exponent is NOT a number to multiply by.', '2^3 means 2 × 2 × 2.'],
    explanation: 'The exponent counts how many 2s to multiply: 2 × 2 × 2 = 8, not 2 × 3 = 6.',
    solutions: [
      { title: 'Way 1: What an exponent means', steps: [
        'The exponent 3 counts how many times 2 is used as a FACTOR.',
        'So 2^3 = 2 × 2 × 2, not 2 × 3.',
        '2 × 2 = 4 and 4 × 2 = 8, so 2^3 = 8.',
      ] },
      { title: 'Way 2: Doubling pattern', steps: [
        '2^1 = 2, 2^2 = 4, and each new power DOUBLES.',
        'Doubling 4 gives 8, so 2^3 = 8.',
        'Mia multiplied the base by the exponent, which is the classic trap.',
      ] },
    ] },
  { id: 'br-55', domain: 'bridge', standard: '6.EE.7', tier: 4, type: 'numeric',
    prompt: 'Solve for x:  2x + 5 = 17',
    answer: '6', acceptable: ['6', 'x=6'],
    hints: ['Undo the +5 first by subtracting 5 from both sides.', 'Then undo the ×2 by dividing both sides by 2.'],
    explanation: '2x + 5 = 17 → 2x = 12 → x = 6. Check: 2(6) + 5 = 17 ✓.',
    solutions: [
      { title: 'Way 1: Balance, undo in reverse order', steps: [
        'Subtract 5 from both sides: 2x = 12.',
        'Divide both sides by 2: x = 6.',
        'Check: 2 × 6 + 5 = 17. ✓',
      ] },
      { title: 'Way 2: Work backward', steps: [
        'The machine did ×2 then +5 and ended at 17.',
        'Undo +5: 17 − 5 = 12.',
        'Undo ×2: 12 ÷ 2 = 6, so x = 6.',
      ] },
      { title: 'Way 3: Guess and check', steps: [
        'Try x = 5: 2 × 5 + 5 = 15 — too small.',
        'Try x = 6: 2 × 6 + 5 = 17. ✓',
        'So x = 6.',
      ] },
    ] },
  { id: 'br-56', domain: 'bridge', standard: '6.RP.3', tier: 4, type: 'numeric',
    prompt: 'A $48 jacket is 25% off. What is the sale price in dollars?',
    answer: '36', acceptable: ['36', '$36', '36 dollars'],
    hints: ['25% is one quarter — find a quarter of 48.', 'Subtract that discount from 48.'],
    explanation: '25% of 48 is 12, so the sale price is 48 − 12 = $36.',
    solutions: [
      { title: 'Way 1: Quarter off', steps: [
        '25% is one quarter, and 48 ÷ 4 = 12.',
        'The discount is $12, so pay 48 − 12 = 36.',
        'The sale price is $36.',
      ] },
      { title: 'Way 2: Pay 75%', steps: [
        'With 25% off you pay 75% of the price.',
        '0.75 × 48 = 36.',
        'The sale price is $36.',
      ] },
      { title: 'Way 3: 10% chunks', steps: [
        '10% of 48 is 4.80, so 20% is 9.60 and 5% is 2.40.',
        '25% off = 9.60 + 2.40 = 12 dollars off.',
        '48 − 12 = $36.',
      ] },
    ] },
  { id: 'br-57', domain: 'bridge', standard: '6.NS.7', tier: 4, type: 'multiple-choice',
    prompt: 'Order from LEAST to greatest: 0, −7, |−5|, −2.',
    choices: ['−7, −2, 0, |−5|', '|−5|, −7, −2, 0', '0, −2, |−5|, −7', '−2, −7, 0, |−5|'], answer: '−7, −2, 0, |−5|',
    hints: ['First figure out the value of |−5|.', '|−5| = 5, a POSITIVE number.'],
    explanation: '|−5| = 5, so the order is −7 < −2 < 0 < 5.',
    solutions: [
      { title: 'Way 1: Simplify the absolute value first', steps: [
        '|−5| means the distance of −5 from zero, which is 5.',
        'Now order −7, −2, 0, and 5.',
        'Least to greatest: −7, −2, 0, then |−5|.',
      ] },
      { title: 'Way 2: Number line placement', steps: [
        'Plot the values: −7 far left, −2 nearer zero, 0, and |−5| = 5 on the right.',
        'Read left to right: −7, −2, 0, 5.',
        'So the correct list is −7, −2, 0, |−5|.',
      ] },
    ] },
  { id: 'br-58', domain: 'bridge', standard: '6.RP.2', tier: 4, type: 'multiple-choice',
    prompt: 'Brand A sells 8 granola bars for $10. Brand B sells 12 bars for $14.40. Which is the better deal?',
    choices: ['Brand A', 'Brand B', 'Same price per bar', 'Cannot tell'], answer: 'Brand B',
    hints: ['Find the price of ONE bar for each brand.', '10 ÷ 8 versus 14.40 ÷ 12.'],
    explanation: 'Brand A is $1.25 per bar and Brand B is $1.20 per bar, so Brand B wins.',
    solutions: [
      { title: 'Way 1: Unit price', steps: [
        'Brand A: 10 ÷ 8 = $1.25 per bar.',
        'Brand B: 14.40 ÷ 12 = $1.20 per bar.',
        '$1.20 is cheaper, so Brand B is the better deal.',
      ] },
      { title: 'Way 2: Make the bar counts match', steps: [
        'Scale both brands to 24 bars.',
        'Brand A: 3 packs of 8 cost 3 × 10 = $30.',
        'Brand B: 2 packs of 12 cost 2 × 14.40 = $28.80.',
        '$28.80 < $30, so Brand B is better.',
      ] },
    ] },
  { id: 'br-59', domain: 'bridge', standard: '6.EE.2', tier: 4, type: 'numeric',
    prompt: 'Evaluate 2x^2 (2 times x squared) when x = 3.',
    answer: '18', acceptable: ['18'],
    hints: ['The exponent belongs ONLY to x, not to the 2 in front.', 'Square 3 first, then multiply by 2.'],
    explanation: 'Square first: 3^2 = 9, then 2 × 9 = 18.',
    solutions: [
      { title: 'Way 1: Order of operations', steps: [
        'Replace x with 3: the expression is 2 × 3^2.',
        'Exponents come before multiplying: 3^2 = 9.',
        'Then 2 × 9 = 18.',
      ] },
      { title: 'Way 2: Dodge the classic trap', steps: [
        'Doubling first gives (2 × 3)^2 = 36 — but that is WRONG.',
        'The exponent sticks only to x, so square the 3 alone: 9.',
        'Multiply by 2 last: 2 × 9 = 18.',
      ] },
    ] },
  { id: 'br-60', domain: 'bridge', standard: '6.NS.5', tier: 4, type: 'multiple-choice',
    prompt: 'A submarine is at −40 meters. It rises 25 meters, then dives 10 meters. What is its final elevation?',
    choices: ['−25 m', '−5 m', '−55 m', '25 m'], answer: '−25 m',
    hints: ['Do one move at a time: rise first, then dive.', '−40 + 25 = −15, then go 10 more down.'],
    explanation: '−40 + 25 = −15, then −15 − 10 = −25 meters.',
    solutions: [
      { title: 'Way 1: One move at a time', steps: [
        'Start at −40 and rise 25: −40 + 25 = −15.',
        'Then dive 10: −15 − 10 = −25.',
        'The submarine ends at −25 meters.',
      ] },
      { title: 'Way 2: Net change first', steps: [
        'Combine the moves: up 25 and down 10 is a net rise of 15.',
        'Apply it to the start: −40 + 15 = −25.',
        'Final elevation: −25 meters.',
      ] },
    ] },
  { id: 'br-61', domain: 'bridge', standard: '6.EE.7', tier: 4, type: 'constructed',
    prompt: 'Solve 3x − 2 = 13 and explain each step.',
    answer: '5', acceptable: ['5', 'x=5', 'add 2', 'divide by 3', 'both sides'],
    hints: ['First undo the −2 (add 2 to both sides).', 'Then undo the ×3 (divide both sides by 3).'],
    explanation: 'Add 2 to both sides: 3x = 15. Divide by 3: x = 5. Check: 3(5) − 2 = 13. ✓',
    solutions: [
      { title: 'Way 1: Balance, undo in reverse order', steps: [
        'Add 2 to BOTH sides to undo the −2: 3x = 15.',
        'Divide both sides by 3 to undo the ×3: x = 5.',
        'Check: 3 × 5 − 2 = 13. ✓',
      ] },
      { title: 'Way 2: Work backward', steps: [
        'The machine did ×3 then −2 and ended at 13.',
        'Undo −2: 13 + 2 = 15.',
        'Undo ×3: 15 ÷ 3 = 5, so x = 5.',
      ] },
    ] },
  { id: 'br-62', domain: 'bridge', standard: '6.RP.3', tier: 4, type: 'numeric',
    prompt: '40% of a number is 26. What is the number?',
    answer: '65', acceptable: ['65'],
    hints: ['If 40% is 26, then 10% is 26 ÷ 4.', 'The whole number is 100%, or ten of those 10% pieces.'],
    explanation: '10% is 26 ÷ 4 = 6.5, so 100% is 6.5 × 10 = 65.',
    solutions: [
      { title: 'Way 1: Step down to 10%', steps: [
        '40% of the number is 26, so 10% is 26 ÷ 4 = 6.5.',
        'The whole is 100%, which is ten 10% pieces: 6.5 × 10 = 65.',
        'Check: 40% of 65 = 0.4 × 65 = 26. ✓',
      ] },
      { title: 'Way 2: Write an equation', steps: [
        'Let n be the number: 0.4 × n = 26.',
        'Divide both sides by 0.4: n = 26 ÷ 0.4 = 65.',
        'So the number is 65.',
      ] },
      { title: 'Way 3: Use the fraction 2/5', steps: [
        '40% = 2/5, so 2/5 of the number is 26.',
        'One fifth is 26 ÷ 2 = 13.',
        'Five fifths make the whole: 13 × 5 = 65.',
      ] },
    ] },
  { id: 'br-63', domain: 'bridge', standard: '6.NS.7', tier: 4, type: 'multiple-choice',
    prompt: 'Which statement is TRUE?',
    choices: ['|−6| > |4|', '|−6| < |4|', '|−6| = −6', '−6 > 4'], answer: '|−6| > |4|',
    hints: ['Absolute value = distance from zero.', 'Find |−6| and |4| first, then compare.'],
    explanation: '|−6| = 6 and |4| = 4, and 6 > 4.',
    solutions: [
      { title: 'Way 1: Compute the absolute values', steps: [
        '|−6| is the distance from −6 to zero, which is 6.',
        '|4| is the distance from 4 to zero, which is 4.',
        '6 > 4, so |−6| > |4| is true.',
      ] },
      { title: 'Way 2: Eliminate the false ones', steps: [
        '|−6| = −6 is false — absolute value is never negative.',
        '−6 > 4 is false — negatives are less than positives.',
        '−6 is FARTHER from zero than 4, so |−6| > |4| is the true one.',
      ] },
    ] },
  { id: 'br-64', domain: 'bridge', standard: '6.RP.3', tier: 4, type: 'constructed',
    prompt: 'A $50 backpack is 30% off. Find the sale price and explain TWO different ways to get it.',
    answer: '35', acceptable: ['$35', '15', '70%', 'subtract', 'discount'],
    hints: ['Way A: find 30% of 50, then subtract it.', 'Way B: with 30% off you PAY 70% — find 70% of 50.'],
    explanation: '30% of 50 is 15 off, or pay 70% of 50 — either way the sale price is $35.',
    solutions: [
      { title: 'Way 1: Find the discount, then subtract', steps: [
        '30% of 50 is 0.30 × 50 = 15, so $15 comes off.',
        'Subtract from the price: 50 − 15 = 35.',
        'The sale price is $35.',
      ] },
      { title: 'Way 2: Pay the percent that is LEFT', steps: [
        'Taking 30% off means you still pay 70%.',
        '70% of 50 is 0.70 × 50 = 35.',
        'The sale price is $35 — same answer, one step fewer.',
      ] },
      { title: 'Way 3: 10% chunks', steps: [
        '10% of 50 is 5, so 30% is 3 × 5 = 15 off.',
        '50 − 15 = 35, so the sale price is $35.',
      ] },
    ] },
  { id: 'br-65', domain: 'bridge', standard: '6.EE.1', tier: 4, type: 'multiple-choice',
    prompt: 'What is the value of 3^4?',
    choices: ['81', '12', '64', '27'], answer: '81',
    hints: ['3^4 means 3 × 3 × 3 × 3, NOT 3 × 4.', 'Build up: 3, 9, 27, ...'],
    explanation: '3^4 = 3 × 3 × 3 × 3 = 81.',
    solutions: [
      { title: 'Way 1: Multiply step by step', steps: [
        '3 × 3 = 9.',
        '9 × 3 = 27, and 27 × 3 = 81.',
        'So 3^4 = 81 (12 is the trap from 3 × 4, and 27 is only 3^3).',
      ] },
      { title: 'Way 2: Square of a square', steps: [
        '3^4 is the same as (3^2) × (3^2).',
        '3^2 = 9, so 3^4 = 9 × 9.',
        '9 × 9 = 81.',
      ] },
    ] },
  { id: 'br-66', domain: 'bridge', standard: '6.NS.5', tier: 4, type: 'constructed',
    prompt: 'At dawn the temperature was −6°C. By noon it was 9°C. Explain how to find how many degrees it rose.',
    answer: '15', acceptable: ['15 degrees', 'distance', 'add', 'number line', '6 + 9'],
    hints: ['Split the climb at zero: −6 up to 0, then 0 up to 9.', 'Add the two pieces of the climb.'],
    explanation: 'From −6 to 0 is 6 degrees and 0 to 9 is 9 more, so it rose 6 + 9 = 15 degrees.',
    solutions: [
      { title: 'Way 1: Split the climb at zero', steps: [
        'Climbing from −6 up to 0 takes 6 degrees.',
        'Climbing from 0 up to 9 takes 9 more degrees.',
        'Total rise: 6 + 9 = 15 degrees.',
      ] },
      { title: 'Way 2: Subtract the start from the end', steps: [
        'Change = end − start = 9 − (−6).',
        'Subtracting a negative is the same as adding: 9 + 6.',
        'The temperature rose 15 degrees.',
      ] },
      { title: 'Way 3: Distance on a number line', steps: [
        '−6 and 9 are on opposite sides of zero.',
        'Their distance apart is |−6| + |9| = 6 + 9.',
        'So the temperature rose 15 degrees.',
      ] },
    ] },
];
