import type { Problem, Lesson } from '../types';

// ===========================================================================
// bridge — Course 3 readiness: ratios/rates/%, integers, simple equations
// These go BEYOND 5th grade to show acceleration readiness for SRVUSD MAP.
// ===========================================================================

export const lessons: Lesson[] = [
  {
    domain: 'bridge', standard: '6.RP.1',
    title: 'Ratios, Rates & Percent',
    steps: [
      'A ratio compares two amounts, like 3 : 2 or 3 to 2.',
      'A unit rate is "per one" — divide to get it (miles per hour).',
      'Percent means "out of 100": 25% = 25/100 = 0.25.',
      'To find a percent of a number, multiply by its decimal form.',
    ],
    example: '20% of 50 = 0.20 × 50 = 10.',
    tip: 'Build a ratio table to scale up or down without mistakes.',
  },
  {
    domain: 'bridge', standard: '6.NS.5',
    title: 'Integers (Negative Numbers)',
    steps: [
      'Negative numbers are LEFT of 0 on the number line.',
      'The farther left, the smaller: −5 < −2.',
      'Adding a negative moves you left; subtracting a negative moves you right.',
      'Opposite numbers (3 and −3) are the same distance from 0.',
    ],
    example: '−3 + 5 = 2 (start at −3, move 5 right).',
    tip: 'Think of temperatures or money owed to picture negatives.',
  },
  {
    domain: 'bridge', standard: '6.EE.7',
    title: 'Solve Simple Equations',
    steps: [
      'A variable (like x) stands for an unknown number.',
      'Do the OPPOSITE operation to undo what is around x.',
      'Whatever you do to one side, do to the other side too.',
      'Check by plugging your answer back in.',
    ],
    example: 'x + 4 = 10 → subtract 4 from both sides → x = 6.',
    tip: 'Keep the equation "balanced" like a scale — both sides stay equal.',
  },
];

export const problems: Problem[] = [
  { id: 'br-1', domain: 'bridge', standard: '6.NS.5', tier: 1, type: 'multiple-choice',
    prompt: 'Which number is smaller: −4 or −1?',
    diagram: { kind: 'numberLine', min: -5, max: 5, ticks: 10, mark: -4 },
    choices: ['−4', '−1', 'They are equal', 'Cannot tell'], answer: '−4',
    hints: ['Farther left = smaller.'],
    explanation: '−4 is farther left on the number line, so −4 < −1.' },
  { id: 'br-2', domain: 'bridge', standard: '6.RP.3', tier: 1, type: 'numeric',
    prompt: 'What is 50% of 30?', answer: '15', acceptable: ['15'],
    hints: ['50% = half.'],
    explanation: '50% means half, so 30 ÷ 2 = 15.' },
  { id: 'br-3', domain: 'bridge', standard: '6.EE.7', tier: 2, type: 'numeric',
    prompt: 'Solve for x:  x + 7 = 12', answer: '5', acceptable: ['5', 'x=5'],
    hints: ['Undo +7 by subtracting 7 from both sides.'],
    explanation: 'x + 7 = 12 → x = 12 − 7 = 5.' },
  { id: 'br-4', domain: 'bridge', standard: '6.RP.2', tier: 2, type: 'numeric',
    prompt: 'A car goes 120 miles in 2 hours. What is the unit rate in miles per hour?',
    answer: '60', acceptable: ['60', '60 mph'],
    hints: ['Per ONE hour: divide by 2.'],
    explanation: '120 ÷ 2 = 60 miles per hour.' },
  { id: 'br-5', domain: 'bridge', standard: '6.NS.5', tier: 3, type: 'numeric',
    prompt: 'The temperature is −3°C and rises 8°C. What is the new temperature?',
    answer: '5', acceptable: ['5', '5°C', '5 C'],
    hints: ['Start at −3, move 8 right.'],
    explanation: '−3 + 8 = 5°C.' },
  { id: 'br-6', domain: 'bridge', standard: '6.RP.3', tier: 3, type: 'numeric',
    prompt: 'A shirt costs $40. It is 25% off. What is the SALE price in dollars?',
    answer: '30', acceptable: ['30', '$30'],
    hints: ['25% of 40 = 0.25 × 40 = 10 off.', '40 − 10.'],
    explanation: '25% of 40 is 10; sale price = 40 − 10 = $30.' },
  { id: 'br-7', domain: 'bridge', standard: '6.EE.7', tier: 4, type: 'numeric',
    prompt: 'Solve for x:  3x = 21', answer: '7', acceptable: ['7', 'x=7'],
    hints: ['3 times x = 21.', 'Divide both sides by 3.'],
    explanation: '3x = 21 → x = 21 ÷ 3 = 7.' },
  { id: 'br-8', domain: 'bridge', standard: '6.EE.7', tier: 4, type: 'constructed',
    prompt: 'Solve 2x + 3 = 11 and explain each step.',
    answer: '4', acceptable: ['4', 'x=4'],
    hints: ['First undo +3 (subtract 3).', 'Then undo ×2 (divide by 2).'],
    explanation: 'Subtract 3 from both sides: 2x = 8. Divide both sides by 2: x = 4. Check: 2(4)+3 = 11. ✓' },
  { id: 'br-9', domain: 'bridge', standard: '6.RP.3', tier: 1, type: 'numeric',
    prompt: 'What is 10% of 70?', answer: '7', acceptable: ['7'],
    hints: ['10% = one tenth.'],
    explanation: '10% means one tenth: 70 ÷ 10 = 7.' },
  { id: 'br-10', domain: 'bridge', standard: '6.NS.6', tier: 2, type: 'numeric',
    prompt: 'What is the OPPOSITE of −6?', answer: '6', acceptable: ['6', '+6'],
    hints: ['Opposites are the same distance from 0, on the other side.'],
    explanation: 'The opposite of −6 is 6 — both are 6 steps from zero.' },
  { id: 'br-11', domain: 'bridge', standard: '6.RP.3', tier: 2, type: 'numeric',
    prompt: 'A smoothie recipe uses 2 cups of strawberries for every 3 cups of milk. With 6 cups of milk, how many cups of strawberries?',
    answer: '4', acceptable: ['4', '4 cups'],
    hints: ['Milk doubled (3 → 6).', 'Double the strawberries too.'],
    explanation: 'The ratio 2:3 scales up — milk doubled, so strawberries double: 2 × 2 = 4 cups.' },
  { id: 'br-12', domain: 'bridge', standard: '6.EE.7', tier: 3, type: 'numeric',
    prompt: 'Solve for x:  x − 9 = 16', answer: '25', acceptable: ['25', 'x=25'],
    hints: ['Undo −9 by adding 9 to both sides.'],
    explanation: 'x − 9 = 16 → x = 16 + 9 = 25. Check: 25 − 9 = 16 ✓.' },
  { id: 'br-13', domain: 'bridge', standard: '6.RP.3', tier: 3, type: 'numeric',
    prompt: 'What is 75% of 80?', answer: '60', acceptable: ['60'],
    hints: ['75% = 3/4.', '80 ÷ 4 = 20, then × 3.'],
    explanation: '75% = 3/4, and 3/4 × 80 = 60.' },
  { id: 'br-14', domain: 'bridge', standard: '6.NS.7', tier: 3, type: 'multiple-choice',
    prompt: 'Which temperature is the COLDEST?',
    choices: ['−7°C', '−2°C', '0°C', '3°C'], answer: '−7°C',
    hints: ['Coldest = smallest = farthest left on the number line.'],
    explanation: '−7 is farthest left on the number line, so −7°C is coldest.' },
  { id: 'br-15', domain: 'bridge', standard: '6.EE.7', tier: 4, type: 'numeric',
    prompt: 'Solve for x:  x ÷ 4 = 6', answer: '24', acceptable: ['24', 'x=24'],
    hints: ['Undo ÷4 by multiplying both sides by 4.'],
    explanation: 'x ÷ 4 = 6 → x = 6 × 4 = 24. Check: 24 ÷ 4 = 6 ✓.' },
  { id: 'br-16', domain: 'bridge', standard: '6.RP.3', tier: 4, type: 'numeric',
    prompt: '15 is what PERCENT of 60?', answer: '25', acceptable: ['25', '25%'],
    hints: ['15/60 = 1/4.', 'Write 1/4 as a percent.'],
    explanation: '15/60 = 1/4 = 25%.' },
];
