import type { Problem, Lesson } from '../types';

// ===========================================================================
// 5.G — Geometry (coordinate plane, classifying 2D shapes)
// ===========================================================================

export const lessons: Lesson[] = [
  {
    domain: '5.G', standard: '5.G.1',
    title: 'The Coordinate Plane',
    steps: [
      'A point is written (x, y).',
      'x tells you how far RIGHT from 0; y tells you how far UP.',
      'Always move along x FIRST, then y.',
      'The origin is (0, 0).',
    ],
    example: '(3, 2) means 3 right and 2 up.',
    tip: 'Remember "x comes before y" just like in the alphabet — and you walk before you climb.',
  },
  {
    domain: '5.G', standard: '5.G.3',
    title: 'Classify Triangles & Quadrilaterals',
    steps: [
      'A square is a special rectangle (4 right angles + all sides equal).',
      'A rectangle is a special parallelogram.',
      'A rhombus has 4 equal sides; a square is a rhombus too.',
      'Properties of a category belong to ALL shapes in it.',
    ],
    example: 'Every square is a rectangle, but not every rectangle is a square.',
    tip: 'Think of nested boxes: squares ⊂ rectangles ⊂ parallelograms ⊂ quadrilaterals.',
  },
];

export const problems: Problem[] = [
  { id: 'geo-1', domain: '5.G', standard: '5.G.1', tier: 1, type: 'multiple-choice',
    prompt: 'Which point is at (3, 1)?',
    diagram: { kind: 'coordinate', points: [{ x: 3, y: 1, label: 'A' }, { x: 1, y: 3, label: 'B' }], max: 6 },
    choices: ['A', 'B', 'Neither', 'Both'], answer: 'A',
    hints: ['x first (right), then y (up).', '3 right and 1 up.'],
    explanation: '(3,1) means 3 right, 1 up — that is point A. Point B at (1,3) is the swap.',
    solutions: [
      { title: 'Way 1: Walk the grid', steps: [
        'Start at the origin (0, 0).',
        'Move 3 units right because x = 3.',
        'Move 1 unit up because y = 1.',
        'You land on point A, so the answer is A.',
      ] },
      { title: 'Way 2: Check each label', steps: [
        'Point A sits 3 right and 1 up, which matches (3, 1).',
        'Point B sits 1 right and 3 up, which is (1, 3) — the swap.',
        'Only point A matches, so the answer is A.',
      ] },
    ] },
  { id: 'geo-2', domain: '5.G', standard: '5.G.3', tier: 1, type: 'multiple-choice',
    prompt: 'A shape has 4 equal sides and 4 right angles. What is it?',
    diagram: { kind: 'shape', shape: 'square' },
    choices: ['Square', 'Triangle', 'Trapezoid', 'Circle'], answer: 'Square',
    hints: ['4 right angles AND all sides equal.'],
    explanation: '4 right angles + 4 equal sides = a square.',
    solutions: [
      { title: 'Way 1: Match the definition', steps: [
        'A square is the only quadrilateral with 4 equal sides AND 4 right angles.',
        'The clue lists exactly those two properties.',
        'So the shape is a Square.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'A triangle has 3 sides, not 4, so it is out.',
        'A trapezoid does not need equal sides or right angles.',
        'A circle has no straight sides at all.',
        'Only the square fits, so the answer is Square.',
      ] },
    ] },
  { id: 'geo-3', domain: '5.G', standard: '5.G.1', tier: 2, type: 'numeric',
    prompt: 'Start at (0,0). Move 4 right and 3 up. Write the point as x,y (e.g. 4,3).',
    answer: '4,3', acceptable: ['(4,3)', '4, 3', '4 3'],
    hints: ['x = right amount, y = up amount.'],
    explanation: '4 right and 3 up from the origin is (4, 3).',
    solutions: [
      { title: 'Way 1: Use the x-then-y rule', steps: [
        'The first number of a point is how far right: 4.',
        'The second number is how far up: 3.',
        'So the point is written 4,3.',
      ] },
      { title: 'Way 2: Walk the grid', steps: [
        'Put your finger on the origin (0, 0).',
        'Count 4 steps right; you are at (4, 0).',
        'Count 3 steps up; you land at (4, 3).',
        'The answer is 4,3.',
      ] },
    ] },
  { id: 'geo-4', domain: '5.G', standard: '5.G.3', tier: 2, type: 'multiple-choice',
    prompt: 'Which statement is ALWAYS true?',
    choices: ['Every square is a rectangle', 'Every rectangle is a square', 'Every triangle is a square', 'No square is a rectangle'], answer: 'Every square is a rectangle',
    hints: ['A square has all the properties of a rectangle plus equal sides.'],
    explanation: 'A square meets every rule of a rectangle (4 right angles), so every square IS a rectangle. The reverse is not true.',
    solutions: [
      { title: 'Way 1: Use the hierarchy', steps: [
        'A rectangle is any quadrilateral with 4 right angles.',
        'Every square has 4 right angles, so it passes the rectangle test.',
        'So "Every square is a rectangle" is always true.',
      ] },
      { title: 'Way 2: Hunt for counterexamples', steps: [
        'A 2 by 5 rectangle is not a square, so "every rectangle is a square" fails.',
        'A triangle has 3 sides, so it can never be a square.',
        'Squares pass the rectangle test, so "no square is a rectangle" is false.',
        'The only statement with no counterexample is "Every square is a rectangle".',
      ] },
    ] },
  { id: 'geo-5', domain: '5.G', standard: '5.G.2', tier: 3, type: 'numeric',
    prompt: 'A path goes from (1,2) to (1,6). How many units long is it?',
    diagram: { kind: 'coordinate', points: [{ x: 1, y: 2, label: 'P' }, { x: 1, y: 6, label: 'Q' }], max: 8 },
    answer: '4', acceptable: ['4', '4 units'],
    hints: ['Same x, so just compare the y-values.', '6 − 2.'],
    explanation: 'Same x = 1, so the length is the change in y: 6 − 2 = 4 units.',
    solutions: [
      { title: 'Way 1: Subtract the y-values', steps: [
        'Both points have x = 1, so the path runs straight up and down.',
        'Subtract the y-values: 6 − 2 = 4.',
        'The path is 4 units long.',
      ] },
      { title: 'Way 2: Count the hops', steps: [
        'Start at (1, 2) and hop up one unit at a time.',
        'You pass y = 3, then 4, then 5, and land on 6.',
        'That is 4 hops, so the path is 4 units long.',
      ] },
    ] },
  { id: 'geo-6', domain: '5.G', standard: '5.G.4', tier: 3, type: 'multiple-choice',
    prompt: 'Which quadrilateral has exactly ONE pair of parallel sides?',
    diagram: { kind: 'shape', shape: 'trapezoid' },
    choices: ['Trapezoid', 'Rectangle', 'Rhombus', 'Square'], answer: 'Trapezoid',
    hints: ['Parallelograms have TWO pairs.', 'Which one has only one pair?'],
    explanation: 'A trapezoid has exactly one pair of parallel sides; the others all have two pairs.',
    solutions: [
      { title: 'Way 1: Check the definition', steps: [
        'A trapezoid is defined as a quadrilateral with exactly one pair of parallel sides.',
        'That matches the question word for word.',
        'So the answer is Trapezoid.',
      ] },
      { title: 'Way 2: Count pairs in each shape', steps: [
        'Rectangles, rhombuses, and squares are all parallelograms.',
        'Every parallelogram has TWO pairs of parallel sides.',
        'Only the trapezoid stops at one pair, so the answer is Trapezoid.',
      ] },
    ] },
  { id: 'geo-7', domain: '5.G', standard: '5.G.2', tier: 4, type: 'numeric',
    prompt: 'A rectangle has corners (1,1), (5,1), (5,4), (1,4). What is its AREA?',
    answer: '12', acceptable: ['12', '12 square units'],
    hints: ['Width = 5 − 1 = 4. Height = 4 − 1 = 3.', 'Area = width × height.'],
    explanation: 'Width = 4, height = 3, so area = 4 × 3 = 12 square units.',
    solutions: [
      { title: 'Way 1: Subtract coordinates, then multiply', steps: [
        'Width: the x-values go from 1 to 5, so 5 − 1 = 4 units.',
        'Height: the y-values go from 1 to 4, so 4 − 1 = 3 units.',
        'Area = 4 × 3 = 12 square units.',
      ] },
      { title: 'Way 2: Count unit squares', steps: [
        'Picture the rectangle on grid paper from x = 1 to 5 and y = 1 to 4.',
        'Each row holds 4 unit squares, and there are 3 rows.',
        'Counting 4 + 4 + 4 gives 12 square units.',
      ] },
    ] },
  { id: 'geo-8', domain: '5.G', standard: '5.G.3', tier: 4, type: 'constructed',
    prompt: 'Is a rhombus always a square? Explain why or why not.',
    answer: 'no', acceptable: ['no', 'angles', 'not always'],
    hints: ['A rhombus has 4 equal sides.', 'Does it always have right angles?'],
    explanation: 'No. A rhombus has 4 equal sides but its angles do not have to be right angles. Only when all 4 angles are 90° is the rhombus also a square.',
    solutions: [
      { title: 'Way 1: Compare the definitions', steps: [
        'A rhombus needs 4 equal sides; a square needs that PLUS 4 right angles.',
        'Nothing in the rhombus rule requires right angles.',
        'So no, a rhombus is not always a square.',
      ] },
      { title: 'Way 2: Find a counterexample', steps: [
        'Picture a diamond with 4 equal sides leaning to one side.',
        'Its angles are not 90 degrees, so it fails the square test.',
        'It is still a rhombus, so one counterexample proves the answer is no.',
      ] },
    ] },
  { id: 'geo-9', domain: '5.G', standard: '5.G.1', tier: 1, type: 'numeric',
    prompt: 'What is the y-coordinate of the point (2, 7)?', answer: '7', acceptable: ['7'],
    hints: ['Points are written (x, y) — y is second.'],
    explanation: 'In (2, 7) the second number is y, so y = 7.',
    solutions: [
      { title: 'Way 1: Use the position rule', steps: [
        'Points are always written (x, y), so the second number is y.',
        'In (2, 7) the second number is 7.',
        'So the y-coordinate is 7.',
      ] },
      { title: 'Way 2: Think right-then-up', steps: [
        'The point (2, 7) means walk 2 right, then climb 7 up.',
        'The climbing amount is the y-coordinate.',
        'So y = 7.',
      ] },
    ] },
  { id: 'geo-10', domain: '5.G', standard: '5.G.1', tier: 2, type: 'multiple-choice',
    prompt: 'Which point lies ON the x-axis?',
    choices: ['(5, 0)', '(0, 5)', '(5, 5)', '(1, 5)'], answer: '(5, 0)',
    hints: ['On the x-axis, the height (y) is 0.'],
    explanation: 'A point on the x-axis has y = 0, so (5, 0) is on the x-axis. (0, 5) is on the y-axis.',
    solutions: [
      { title: 'Way 1: Use the y = 0 rule', steps: [
        'The x-axis is the flat line where the height y equals 0.',
        'Look for the choice whose second number is 0.',
        'That is (5, 0), so it lies on the x-axis.',
      ] },
      { title: 'Way 2: Plot each point', steps: [
        '(0, 5) climbs 5 up the y-axis, so it is not on the x-axis.',
        '(5, 5) and (1, 5) both float 5 units above the x-axis.',
        '(5, 0) goes 5 right with no height, sitting right on the x-axis.',
        'So the answer is (5, 0).',
      ] },
    ] },
  { id: 'geo-11', domain: '5.G', standard: '5.G.4', tier: 2, type: 'multiple-choice',
    prompt: 'A triangle has all three sides the same length. What kind is it?',
    diagram: { kind: 'shape', shape: 'triangle' },
    choices: ['Equilateral', 'Scalene', 'Right', 'Obtuse'], answer: 'Equilateral',
    hints: ['"Equi-" means equal.'],
    explanation: 'All sides equal = equilateral. (Scalene = no equal sides; isosceles = at least two equal.)',
    solutions: [
      { title: 'Way 1: Break down the word', steps: [
        'The prefix "equi-" means equal, and "lateral" means sides.',
        'A triangle with all three sides equal is equilateral.',
        'So the answer is Equilateral.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'Scalene means NO sides match, so that is out.',
        'Right and obtuse describe angles, not side lengths.',
        'The side name that fits all-equal sides is Equilateral.',
      ] },
    ] },
  { id: 'geo-12', domain: '5.G', standard: '5.G.2', tier: 3, type: 'numeric',
    prompt: 'A rectangle has corners (0,0), (6,0), (6,3), (0,3). What is its PERIMETER?',
    diagram: { kind: 'coordinate', points: [{ x: 0, y: 0 }, { x: 6, y: 0 }, { x: 6, y: 3 }, { x: 0, y: 3 }], max: 7 },
    answer: '18', acceptable: ['18', '18 units'],
    hints: ['Width = 6, height = 3.', 'Perimeter = 2 × (6 + 3).'],
    explanation: 'Sides are 6 and 3, so perimeter = 2 × (6 + 3) = 18 units.',
    solutions: [
      { title: 'Way 1: Use the perimeter formula', steps: [
        'Width: 6 − 0 = 6 units. Height: 3 − 0 = 3 units.',
        'Perimeter = 2 × (6 + 3) = 2 × 9 = 18.',
        'The perimeter is 18 units.',
      ] },
      { title: 'Way 2: Walk all four sides', steps: [
        'Walk the bottom from (0,0) to (6,0): 6 units.',
        'Walk up to (6,3): 3 units. Walk the top back: 6 more.',
        'Walk down to the start: 3 more.',
        'Add 6 + 3 + 6 + 3 = 18 units around.',
      ] },
    ] },
  { id: 'geo-13', domain: '5.G', standard: '5.G.3', tier: 3, type: 'multiple-choice',
    prompt: 'Which statement is ALWAYS true?',
    choices: ['All rhombuses are parallelograms', 'All parallelograms are rhombuses', 'All trapezoids are parallelograms', 'All rectangles are squares'], answer: 'All rhombuses are parallelograms',
    hints: ['A rhombus has two pairs of parallel sides.', 'Categories nest: rhombus ⊂ parallelogram.'],
    explanation: 'Every rhombus has two pairs of parallel sides, so it IS a parallelogram. The reverse fails (a non-square rectangle is a parallelogram but not a rhombus).',
    solutions: [
      { title: 'Way 1: Check parallel pairs', steps: [
        'A rhombus always has two pairs of parallel sides.',
        'Two pairs of parallel sides is exactly what makes a parallelogram.',
        'So "All rhombuses are parallelograms" is always true.',
      ] },
      { title: 'Way 2: Knock out the rest', steps: [
        'A 2 by 5 rectangle is a parallelogram but not a rhombus, so choice 2 fails.',
        'A trapezoid has only ONE pair of parallel sides, so choice 3 fails.',
        'That same 2 by 5 rectangle is not a square, so choice 4 fails.',
        'Only "All rhombuses are parallelograms" survives.',
      ] },
    ] },
  { id: 'geo-14', domain: '5.G', standard: '5.G.2', tier: 4, type: 'numeric',
    prompt: 'Three corners of a rectangle are (2,1), (7,1), and (7,5). Where is the FOURTH corner? (write like 2,5)',
    answer: '2,5', acceptable: ['(2,5)', '2, 5', '2 5'],
    hints: ['It must line up with (2,1) vertically and (7,5) horizontally.'],
    explanation: 'The fourth corner shares x = 2 with (2,1) and y = 5 with (7,5): the point (2, 5).',
    solutions: [
      { title: 'Way 1: Match x and y', steps: [
        'The missing corner sits directly above (2, 1), so its x must be 2.',
        'It sits level with (7, 5), so its y must be 5.',
        'The fourth corner is (2, 5), written 2,5.',
      ] },
      { title: 'Way 2: Plot and trace', steps: [
        'Plot (2,1), (7,1), and (7,5); the bottom and right sides appear.',
        'Trace left from (7, 5) staying at height 5.',
        'Trace up from (2, 1) staying at x = 2.',
        'The two paths cross at (2, 5), so the answer is 2,5.',
      ] },
    ] },
  { id: 'geo-15', domain: '5.G', standard: '5.G.1', tier: 4, type: 'multiple-choice',
    prompt: 'A pattern of points follows the rule "y = x + 2". Which point fits the rule?',
    choices: ['(3, 5)', '(5, 3)', '(2, 2)', '(4, 8)'], answer: '(3, 5)',
    hints: ['Add 2 to x — do you get y?', '3 + 2 = 5 ✓'],
    explanation: 'For (3, 5): y = 3 + 2 = 5 ✓. The others fail the rule. (This previews graphing relationships!)',
    solutions: [
      { title: 'Way 1: Test the winning point', steps: [
        'The rule says: add 2 to x and you should get y.',
        'For (3, 5): 3 + 2 = 5, which matches the y-value.',
        'So (3, 5) fits the rule.',
      ] },
      { title: 'Way 2: Rule out the rest', steps: [
        'For (5, 3): 5 + 2 = 7, not 3, so it fails.',
        'For (2, 2): 2 + 2 = 4, not 2, so it fails.',
        'For (4, 8): 4 + 2 = 6, not 8, so it fails.',
        'Only (3, 5) works, so the answer is (3, 5).',
      ] },
    ] },
  { id: 'geo-16', domain: '5.G', standard: '5.G.1', tier: 1, type: 'multiple-choice',
    prompt: 'What are the coordinates of the origin?',
    choices: ['(0, 0)', '(1, 1)', '(0, 1)', '(1, 0)'], answer: '(0, 0)',
    hints: ['The origin is where the two axes cross.', 'You have moved 0 right and 0 up.'],
    explanation: 'The origin is the starting corner where the axes meet: (0, 0).',
    solutions: [
      { title: 'Way 1: Use the meaning of origin', steps: [
        'The origin is where the x-axis and y-axis cross.',
        'At that spot you have gone 0 right and 0 up.',
        'So the origin is (0, 0).',
      ] },
      { title: 'Way 2: Test each choice', steps: [
        '(1, 1) is 1 right and 1 up, away from the corner.',
        '(0, 1) is on the y-axis but 1 up; (1, 0) is on the x-axis but 1 right.',
        'Only (0, 0) has moved nowhere, so the origin is (0, 0).',
      ] },
    ] },
  { id: 'geo-17', domain: '5.G', standard: '5.G.1', tier: 1, type: 'numeric',
    prompt: 'What is the x-coordinate of the point (5, 2)?', answer: '5', acceptable: ['5'],
    hints: ['Points are written (x, y) — x comes first.', 'Grab the FIRST number inside the parentheses.'],
    explanation: 'In (5, 2) the first number is x, so x = 5.',
    solutions: [
      { title: 'Way 1: Use the position rule', steps: [
        'Points are always written (x, y), so the first number is x.',
        'In (5, 2) the first number is 5.',
        'So the x-coordinate is 5.',
      ] },
      { title: 'Way 2: Think right-then-up', steps: [
        'The point (5, 2) means walk 5 right, then climb 2 up.',
        'The walking-right amount is the x-coordinate.',
        'So x = 5.',
      ] },
    ] },
  { id: 'geo-18', domain: '5.G', standard: '5.G.1', tier: 1, type: 'multiple-choice',
    prompt: 'Which ordered pair names point P?',
    diagram: { kind: 'coordinate', points: [{ x: 2, y: 4, label: 'P' }], max: 6 },
    choices: ['(2, 4)', '(4, 2)', '(2, 2)', '(4, 4)'], answer: '(2, 4)',
    hints: ['Count how far right first, then how far up.', 'P is 2 right and 4 up.'],
    explanation: 'P is 2 right and 4 up, so it is (2, 4) — right comes first.',
    solutions: [
      { title: 'Way 1: Count right, then up', steps: [
        'Start at the origin and slide right until you are under P: 2 units.',
        'Now climb up to P: 4 units.',
        'Right comes first, so P is (2, 4).',
      ] },
      { title: 'Way 2: Test the tempting swap', steps: [
        '(4, 2) means 4 right and 2 up, which lands in a different spot.',
        'P is clearly farther up than it is right, so y must be the bigger number.',
        'That matches (2, 4), so the answer is (2, 4).',
      ] },
    ] },
  { id: 'geo-19', domain: '5.G', standard: '5.G.1', tier: 1, type: 'multiple-choice',
    prompt: 'To plot the point (4, 6), what should you do FIRST?',
    choices: ['Move 4 right from the origin', 'Move 6 up from the origin', 'Move 4 up from the origin', 'Move 6 right from the origin'], answer: 'Move 4 right from the origin',
    hints: ['x comes before y, just like in the alphabet.', 'The first number tells you how far RIGHT.'],
    explanation: 'The first number is x = 4, and x means move right first.',
    solutions: [
      { title: 'Way 1: Use the x-first rule', steps: [
        'An ordered pair is (x, y), and x always comes first.',
        'Here x = 4, and x tells you how far right to go.',
        'So the first move is 4 right from the origin.',
      ] },
      { title: 'Way 2: Walk it like directions', steps: [
        'Plotting a point is like walking: along the ground first, then climbing.',
        'The ground move uses the first number, 4, going right.',
        'So you move 4 right from the origin first.',
      ] },
    ] },
  { id: 'geo-20', domain: '5.G', standard: '5.G.4', tier: 1, type: 'multiple-choice',
    prompt: 'A quadrilateral has 4 right angles, but its sides are NOT all equal. What is it?',
    diagram: { kind: 'shape', shape: 'rectangle' },
    choices: ['Rectangle', 'Square', 'Trapezoid', 'Triangle'], answer: 'Rectangle',
    hints: ['4 right angles is the rectangle rule.', 'A square would also need all equal sides.'],
    explanation: '4 right angles without all-equal sides makes a rectangle, not a square.',
    solutions: [
      { title: 'Way 1: Match the definition', steps: [
        'A rectangle is a quadrilateral with 4 right angles.',
        'It does not need all sides equal — only opposite sides match.',
        'So the shape is a Rectangle.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'A square needs all 4 sides equal, but this shape does not have that.',
        'A triangle has only 3 sides, and a trapezoid does not need any right angles.',
        'The only fit is Rectangle.',
      ] },
    ] },
  { id: 'geo-21', domain: '5.G', standard: '5.G.1', tier: 1, type: 'numeric',
    prompt: 'Start at the origin. Move 2 right and 5 up. Write the point as x,y (e.g. 2,5).',
    answer: '2,5', acceptable: ['(2,5)', '2, 5', '2 5'],
    hints: ['x = how far right, y = how far up.', 'Right 2 gives x = 2; up 5 gives y = 5.'],
    explanation: '2 right and 5 up from the origin is (2, 5).',
    solutions: [
      { title: 'Way 1: Use the x-then-y rule', steps: [
        'The right amount becomes the first number: x = 2.',
        'The up amount becomes the second number: y = 5.',
        'So the point is 2,5.',
      ] },
      { title: 'Way 2: Walk the grid', steps: [
        'Put your finger on (0, 0).',
        'Slide 2 steps right to reach (2, 0).',
        'Climb 5 steps up to land on (2, 5).',
        'The answer is 2,5.',
      ] },
    ] },
  { id: 'geo-22', domain: '5.G', standard: '5.G.3', tier: 1, type: 'multiple-choice',
    prompt: 'Which name fits EVERY square?',
    choices: ['Rectangle', 'Triangle', 'Pentagon', 'Hexagon'], answer: 'Rectangle',
    hints: ['A square has 4 right angles.', 'Which choice is defined by 4 right angles?'],
    explanation: 'Every square has 4 right angles, so every square is also a rectangle.',
    solutions: [
      { title: 'Way 1: Check the rectangle test', steps: [
        'A rectangle is any quadrilateral with 4 right angles.',
        'Every square has 4 right angles, so it passes the test.',
        'So Rectangle fits every square.',
      ] },
      { title: 'Way 2: Count the sides', steps: [
        'A square always has exactly 4 sides.',
        'Triangles have 3, pentagons have 5, and hexagons have 6 — none match.',
        'The only 4-sided choice is Rectangle, and squares qualify, so the answer is Rectangle.',
      ] },
    ] },
  { id: 'geo-23', domain: '5.G', standard: '5.G.1', tier: 1, type: 'numeric',
    prompt: 'A point sits ON the y-axis. What must its x-coordinate be?',
    answer: '0', acceptable: ['0', 'zero'],
    hints: ['The y-axis is the up-and-down line through the origin.', 'On that line you have moved 0 units right.'],
    explanation: 'Every point on the y-axis has moved 0 right, so x = 0.',
    solutions: [
      { title: 'Way 1: Think about the walk', steps: [
        'To reach the y-axis you never step right at all.',
        'No steps right means the x-coordinate is 0.',
        'So x must be 0.',
      ] },
      { title: 'Way 2: Check examples', steps: [
        'Points like (0, 1), (0, 4), and (0, 7) all sit on the y-axis.',
        'Each one starts with 0 as its first number.',
        'The pattern shows x = 0 for every y-axis point.',
      ] },
    ] },
  { id: 'geo-24', domain: '5.G', standard: '5.G.4', tier: 1, type: 'multiple-choice',
    prompt: 'A triangle has exactly one right angle. How is it classified by its angles?',
    choices: ['Right', 'Acute', 'Obtuse', 'Equilateral'], answer: 'Right',
    hints: ['A right angle measures exactly 90 degrees.', 'One 90-degree corner gives the triangle its name.'],
    explanation: 'A triangle with one 90-degree angle is a right triangle.',
    solutions: [
      { title: 'Way 1: Match the angle name', steps: [
        'A 90-degree angle is called a right angle.',
        'A triangle that contains one right angle is named after it.',
        'So the triangle is a Right triangle.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'Acute means ALL angles are smaller than 90 degrees, so that fails.',
        'Obtuse means one angle is bigger than 90 degrees, not equal to it.',
        'Equilateral describes sides, not angles.',
        'The correct angle name is Right.',
      ] },
    ] },
  { id: 'geo-25', domain: '5.G', standard: '5.G.2', tier: 2, type: 'numeric',
    prompt: 'On a treasure map, the ship is at (3, 1) and the cave is at (3, 5). How many units is the straight walk from the ship to the cave?',
    diagram: { kind: 'coordinate', points: [{ x: 3, y: 1, label: 'S' }, { x: 3, y: 5, label: 'C' }], max: 6 },
    answer: '4', acceptable: ['4', '4 units'],
    hints: ['Both points share x = 3, so the walk is straight up.', 'Subtract the y-values: 5 − 1.'],
    explanation: 'Same x, so the distance is the change in y: 5 − 1 = 4 units.',
    solutions: [
      { title: 'Way 1: Subtract the y-values', steps: [
        'Both points have x = 3, so the path goes straight up.',
        'Subtract the heights: 5 − 1 = 4.',
        'The walk is 4 units long.',
      ] },
      { title: 'Way 2: Count the hops', steps: [
        'Start at the ship on (3, 1).',
        'Hop up to y = 2, 3, 4, and finally 5 at the cave.',
        'That is 4 hops, so the walk is 4 units.',
      ] },
    ] },
  { id: 'geo-26', domain: '5.G', standard: '5.G.1', tier: 2, type: 'multiple-choice',
    prompt: 'Which point lies ON the y-axis?',
    choices: ['(0, 4)', '(4, 0)', '(4, 4)', '(1, 4)'], answer: '(0, 4)',
    hints: ['The y-axis is the up-and-down line.', 'On the y-axis, the first number (x) is 0.'],
    explanation: 'A point on the y-axis has x = 0, so (0, 4) is on the y-axis.',
    solutions: [
      { title: 'Way 1: Use the x = 0 rule', steps: [
        'Every point on the y-axis has an x-coordinate of 0.',
        'Scan the choices for a first number of 0.',
        'Only (0, 4) starts with 0, so it lies on the y-axis.',
      ] },
      { title: 'Way 2: Plot each point', steps: [
        '(4, 0) sits on the x-axis, 4 to the right.',
        '(4, 4) and (1, 4) both step right first, leaving the y-axis behind.',
        '(0, 4) goes 0 right and 4 straight up the y-axis, so it is the answer.',
      ] },
    ] },
  { id: 'geo-27', domain: '5.G', standard: '5.G.4', tier: 2, type: 'multiple-choice',
    prompt: 'A quadrilateral has two pairs of parallel sides but NO right angles. Which name fits?',
    diagram: { kind: 'shape', shape: 'parallelogram' },
    choices: ['Parallelogram', 'Rectangle', 'Square', 'Trapezoid'], answer: 'Parallelogram',
    hints: ['Two pairs of parallel sides is the parallelogram rule.', 'Rectangles and squares would need right angles.'],
    explanation: 'Two pairs of parallel sides with no right angles is a plain parallelogram.',
    solutions: [
      { title: 'Way 1: Match the definition', steps: [
        'A parallelogram is any quadrilateral with two pairs of parallel sides.',
        'Right angles are not required for the name.',
        'So the shape is a Parallelogram.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'A rectangle and a square both need 4 right angles, but this shape has none.',
        'A trapezoid has only ONE pair of parallel sides, but this shape has two.',
        'The only name left is Parallelogram.',
      ] },
    ] },
  { id: 'geo-28', domain: '5.G', standard: '5.G.2', tier: 2, type: 'numeric',
    prompt: 'Maya walks along a straight grid street from (2, 3) to (7, 3). How many units does she walk?',
    answer: '5', acceptable: ['5', '5 units'],
    hints: ['Both points share y = 3, so the walk is sideways.', 'Subtract the x-values: 7 − 2.'],
    explanation: 'Same y, so the distance is the change in x: 7 − 2 = 5 units.',
    solutions: [
      { title: 'Way 1: Subtract the x-values', steps: [
        'Both points have y = 3, so the street runs left to right.',
        'Subtract the x-values: 7 − 2 = 5.',
        'Maya walks 5 units.',
      ] },
      { title: 'Way 2: Count the blocks', steps: [
        'Start at (2, 3) and step right one unit at a time.',
        'You touch x = 3, 4, 5, 6, and stop at 7.',
        'That is 5 steps, so Maya walks 5 units.',
      ] },
    ] },
  { id: 'geo-29', domain: '5.G', standard: '5.G.3', tier: 2, type: 'multiple-choice',
    prompt: 'Complete the sentence: A rectangle is ____ a parallelogram.',
    choices: ['always', 'sometimes', 'never', 'only when it is a square'], answer: 'always',
    hints: ['Does a rectangle have two pairs of parallel sides?', 'If yes, it passes the parallelogram test every time.'],
    explanation: 'Every rectangle has two pairs of parallel sides, so it is always a parallelogram.',
    solutions: [
      { title: 'Way 1: Check the definition', steps: [
        'A parallelogram needs two pairs of parallel sides.',
        'In every rectangle, both pairs of opposite sides are parallel.',
        'So a rectangle is ALWAYS a parallelogram.',
      ] },
      { title: 'Way 2: Use the hierarchy chain', steps: [
        'The shape family nests: squares inside rectangles inside parallelograms.',
        'Anything inside the rectangle box is automatically inside the parallelogram box.',
        'So the answer is always.',
      ] },
    ] },
  { id: 'geo-30', domain: '5.G', standard: '5.G.1', tier: 2, type: 'numeric',
    prompt: 'Point A is at (6, 2). Point B is 3 units straight UP from A. Write B as x,y (e.g. 6,5).',
    answer: '6,5', acceptable: ['(6,5)', '6, 5', '6 5'],
    hints: ['Moving up changes only the y-value.', 'Add 3 to the y-coordinate: 2 + 3.'],
    explanation: 'Up means add to y: (6, 2 + 3) = (6, 5).',
    solutions: [
      { title: 'Way 1: Add to the y-coordinate', steps: [
        'Moving up never changes x, so x stays 6.',
        'Add the climb to y: 2 + 3 = 5.',
        'Point B is 6,5.',
      ] },
      { title: 'Way 2: Walk the grid', steps: [
        'Put your finger on (6, 2).',
        'Hop up three times: (6, 3), then (6, 4), then (6, 5).',
        'You stop at (6, 5), so B is 6,5.',
      ] },
    ] },
  { id: 'geo-31', domain: '5.G', standard: '5.G.4', tier: 2, type: 'multiple-choice',
    prompt: 'A triangle has sides 5 cm, 5 cm, and 8 cm. How is it classified by its sides?',
    diagram: { kind: 'shape', shape: 'triangle' },
    choices: ['Isosceles', 'Equilateral', 'Scalene', 'Right'], answer: 'Isosceles',
    hints: ['Count how many sides match.', 'Two equal sides has a special name.'],
    explanation: 'Exactly two equal sides (5 and 5) makes the triangle isosceles.',
    solutions: [
      { title: 'Way 1: Count the matching sides', steps: [
        'The side lengths are 5, 5, and 8.',
        'Two sides match and one is different.',
        'A triangle with at least two equal sides is Isosceles.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'Equilateral needs all three sides equal, but 8 breaks that.',
        'Scalene needs NO equal sides, but the two 5s break that.',
        'Right describes angles, not side lengths.',
        'The side classification is Isosceles.',
      ] },
    ] },
  { id: 'geo-32', domain: '5.G', standard: '5.G.2', tier: 2, type: 'numeric',
    prompt: 'On a city map, the library is at (1, 2) and the park is at (5, 2). How many units long is the straight walk from the library to the park?',
    diagram: { kind: 'coordinate', points: [{ x: 1, y: 2, label: 'L' }, { x: 5, y: 2, label: 'P' }], max: 6 },
    answer: '4', acceptable: ['4', '4 units'],
    hints: ['Both places share y = 2, so the walk is sideways.', 'Find the change in x: 5 − 1.'],
    explanation: 'Same y, so the walk is along x: 5 − 1 = 4 units.',
    solutions: [
      { title: 'Way 1: Subtract the x-values', steps: [
        'Both points have y = 2, so the walk stays level — no going up.',
        'The x-values change from 1 to 5, and 5 − 1 = 4.',
        'So the walk is 4 units long.',
      ] },
      { title: 'Way 2: Count the blocks', steps: [
        'Start at the library on (1, 2).',
        'Step right past x = 2, 3, 4, and arrive at 5.',
        'You took 4 sideways steps, so the walk is 4 units.',
      ] },
    ] },
  { id: 'geo-33', domain: '5.G', standard: '5.G.1', tier: 2, type: 'numeric',
    prompt: 'A point follows the rule y = x + 3. If x = 4, write the point as x,y (e.g. 4,7).',
    answer: '4,7', acceptable: ['(4,7)', '4, 7', '4 7'],
    hints: ['Plug x = 4 into the rule.', 'y = 4 + 3.'],
    explanation: 'When x = 4, y = 4 + 3 = 7, so the point is (4, 7).',
    solutions: [
      { title: 'Way 1: Plug into the rule', steps: [
        'The rule says y is 3 more than x.',
        'With x = 4, compute y = 4 + 3 = 7.',
        'The point is 4,7.',
      ] },
      { title: 'Way 2: Build a quick table', steps: [
        'Try small x-values: x = 1 gives y = 4; x = 2 gives y = 5; x = 3 gives y = 6.',
        'The pattern adds 1 to each, so x = 4 gives y = 7.',
        'The point is 4,7.',
      ] },
    ] },
  { id: 'geo-34', domain: '5.G', standard: '5.G.3', tier: 2, type: 'constructed',
    prompt: 'Leo says every square is also a rhombus. Is he right? Explain using sides.',
    answer: 'yes', acceptable: ['yes', 'equal sides', 'four equal sides', 'rhombus rule', 'correct'],
    hints: ['What is the only requirement to be a rhombus?', 'Does a square have 4 equal sides?'],
    explanation: 'Yes — a rhombus only needs 4 equal sides, and every square has exactly that.',
    solutions: [
      { title: 'Way 1: Check the rhombus test', steps: [
        'The rhombus rule asks for one thing: 4 equal sides.',
        'Every square has 4 equal sides by definition.',
        'So yes, Leo is right — every square is a rhombus.',
      ] },
      { title: 'Way 2: Use the hierarchy chain', steps: [
        'A square is a rhombus that also picked up 4 right angles.',
        'Adding extra properties never removes a shape from its family.',
        'So a square stays in the rhombus family — Leo is right.',
      ] },
    ] },
  { id: 'geo-35', domain: '5.G', standard: '5.G.4', tier: 2, type: 'multiple-choice',
    prompt: 'Which shape ALWAYS has 4 equal sides but does NOT need right angles?',
    diagram: { kind: 'shape', shape: 'rhombus' },
    choices: ['Rhombus', 'Rectangle', 'Trapezoid', 'Right triangle'], answer: 'Rhombus',
    hints: ['Think of a pushed-over square, like a diamond.', 'Its sides stay equal even when the angles lean.'],
    explanation: 'A rhombus requires 4 equal sides and says nothing about right angles.',
    solutions: [
      { title: 'Way 1: Match the definition', steps: [
        'The rhombus rule is exactly "4 equal sides", with no angle requirement.',
        'A leaning diamond keeps equal sides without right angles.',
        'So the answer is Rhombus.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'A rectangle MUST have right angles, so it is out.',
        'A trapezoid does not need any equal sides.',
        'A right triangle has 3 sides and a required right angle.',
        'Only Rhombus fits the clue.',
      ] },
    ] },
  { id: 'geo-36', domain: '5.G', standard: '5.G.2', tier: 2, type: 'numeric',
    prompt: 'A spider starts at (4, 4). It crawls 2 units left and 3 units up. Write its new spot as x,y (e.g. 2,7).',
    answer: '2,7', acceptable: ['(2,7)', '2, 7', '2 7'],
    hints: ['Left changes x; up changes y.', 'x: 4 − 2 = 2. y: 4 + 3 = 7.'],
    explanation: 'Left 2 makes x = 4 − 2 = 2; up 3 makes y = 4 + 3 = 7, so (2, 7).',
    solutions: [
      { title: 'Way 1: Adjust each coordinate', steps: [
        'Crawling left subtracts from x: 4 − 2 = 2.',
        'Crawling up adds to y: 4 + 3 = 7.',
        'The new spot is 2,7.',
      ] },
      { title: 'Way 2: Walk the grid', steps: [
        'Start at (4, 4) and step left twice: (3, 4), then (2, 4).',
        'Now climb up three times: (2, 5), (2, 6), (2, 7).',
        'The spider lands at 2,7.',
      ] },
    ] },
  { id: 'geo-37', domain: '5.G', standard: '5.G.4', tier: 2, type: 'multiple-choice',
    prompt: 'A triangle has one angle that is LARGER than 90 degrees. What is it called?',
    choices: ['Obtuse', 'Acute', 'Right', 'Scalene'], answer: 'Obtuse',
    hints: ['An angle bigger than 90 degrees is an obtuse angle.', 'The triangle takes its name from that wide angle.'],
    explanation: 'One angle over 90 degrees makes the whole triangle obtuse.',
    solutions: [
      { title: 'Way 1: Name the wide angle', steps: [
        'An angle larger than 90 degrees is called obtuse.',
        'A triangle containing an obtuse angle is named after it.',
        'So the triangle is Obtuse.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'Acute means every angle is under 90 degrees, so that fails.',
        'Right means one angle is exactly 90 degrees, not more.',
        'Scalene is about sides, not angles.',
        'The angle name that fits is Obtuse.',
      ] },
    ] },
  { id: 'geo-38', domain: '5.G', standard: '5.G.1', tier: 2, type: 'multiple-choice',
    prompt: 'Zoe tried to plot (5, 2) by moving 2 right and 5 up. What mistake did she make?',
    choices: ['She swapped x and y', 'She moved too far right', 'She started at (1, 1)', 'She made no mistake'], answer: 'She swapped x and y',
    hints: ['The first number tells how far RIGHT.', 'Compare her moves to the numbers in (5, 2).'],
    explanation: 'For (5, 2) you go 5 right and 2 up; Zoe used the numbers in the wrong order.',
    solutions: [
      { title: 'Way 1: Compare to the correct moves', steps: [
        'The point (5, 2) means 5 right and 2 up.',
        'Zoe went 2 right and 5 up, using each number for the wrong direction.',
        'So her mistake was swapping x and y.',
      ] },
      { title: 'Way 2: See where she landed', steps: [
        'Moving 2 right and 5 up lands on the point (2, 5).',
        '(2, 5) is the reverse of the target point (5, 2).',
        'Landing on the reversed point shows she swapped x and y.',
      ] },
    ] },
  { id: 'geo-39', domain: '5.G', standard: '5.G.2', tier: 3, type: 'numeric',
    prompt: 'A rectangle has corners (2,1), (6,1), (6,4), (2,4). What is its PERIMETER?',
    diagram: { kind: 'coordinate', points: [{ x: 2, y: 1 }, { x: 6, y: 1 }, { x: 6, y: 4 }, { x: 2, y: 4 }], max: 7 },
    answer: '14', acceptable: ['14', '14 units'],
    hints: ['Width = 6 − 2; height = 4 − 1.', 'Perimeter = 2 × (width + height).'],
    explanation: 'Width 4 and height 3 give perimeter 2 × (4 + 3) = 14 units.',
    solutions: [
      { title: 'Way 1: Use the formula', steps: [
        'Width: 6 − 2 = 4 units. Height: 4 − 1 = 3 units.',
        'Perimeter = 2 × (4 + 3) = 2 × 7 = 14.',
        'The perimeter is 14 units.',
      ] },
      { title: 'Way 2: Walk all four sides', steps: [
        'Bottom from (2,1) to (6,1): 4 units. Right side up to (6,4): 3 units.',
        'Top back to (2,4): 4 units. Left side down to the start: 3 units.',
        'Add 4 + 3 + 4 + 3 = 14 units.',
      ] },
    ] },
  { id: 'geo-40', domain: '5.G', standard: '5.G.3', tier: 3, type: 'multiple-choice',
    prompt: 'Which statement is only SOMETIMES true?',
    choices: ['A parallelogram is a rectangle', 'A square is a rhombus', 'A rectangle is a parallelogram', 'A square is a quadrilateral'], answer: 'A parallelogram is a rectangle',
    hints: ['Three of these are ALWAYS true.', 'Does every parallelogram have right angles?'],
    explanation: 'A parallelogram is a rectangle only when it happens to have right angles.',
    solutions: [
      { title: 'Way 1: Test the angle requirement', steps: [
        'A parallelogram becomes a rectangle only if it has 4 right angles.',
        'Some parallelograms lean with no right angles, and some are rectangles.',
        'True for some and false for others means SOMETIMES true.',
      ] },
      { title: 'Way 2: Confirm the others are always true', steps: [
        'A square has 4 equal sides, so it is always a rhombus.',
        'A rectangle has two pairs of parallel sides, so it is always a parallelogram.',
        'A square has 4 sides, so it is always a quadrilateral.',
        'The only sometimes statement is "A parallelogram is a rectangle".',
      ] },
    ] },
  { id: 'geo-41', domain: '5.G', standard: '5.G.2', tier: 3, type: 'numeric',
    prompt: 'A garden is a rectangle with corners (0,2), (5,2), (5,8), (0,8). What is its AREA in square units?',
    answer: '30', acceptable: ['30', '30 square units'],
    hints: ['Width = 5 − 0; height = 8 − 2.', 'Area = width × height.'],
    explanation: 'Width 5 and height 6 give area 5 × 6 = 30 square units.',
    solutions: [
      { title: 'Way 1: Subtract, then multiply', steps: [
        'Width: 5 − 0 = 5 units. Height: 8 − 2 = 6 units.',
        'Area = 5 × 6 = 30.',
        'The garden covers 30 square units.',
      ] },
      { title: 'Way 2: Count rows of squares', steps: [
        'Each row of the garden holds 5 unit squares.',
        'The garden rises from y = 2 to y = 8, so there are 6 rows.',
        'Skip-count 5, 10, 15, 20, 25, 30 — the area is 30 square units.',
      ] },
    ] },
  { id: 'geo-42', domain: '5.G', standard: '5.G.4', tier: 3, type: 'multiple-choice',
    prompt: 'Which shape does NOT belong in the parallelogram family?',
    choices: ['Trapezoid', 'Rectangle', 'Rhombus', 'Square'], answer: 'Trapezoid',
    hints: ['The family rule is TWO pairs of parallel sides.', 'Which shape has only one pair?'],
    explanation: 'A trapezoid has only one pair of parallel sides, so it is not a parallelogram.',
    solutions: [
      { title: 'Way 1: Apply the family rule', steps: [
        'To join the parallelogram family, a shape needs two pairs of parallel sides.',
        'A trapezoid has exactly one pair, so it fails the test.',
        'The shape that does not belong is the Trapezoid.',
      ] },
      { title: 'Way 2: Check the members', steps: [
        'Rectangles, rhombuses, and squares all have two pairs of parallel sides.',
        'All three sit inside the parallelogram family.',
        'The leftover shape, the Trapezoid, is the one that does not belong.',
      ] },
    ] },
  { id: 'geo-43', domain: '5.G', standard: '5.G.2', tier: 3, type: 'multiple-choice',
    prompt: 'Points A(1,1), B(5,1), and C(5,3) are three corners of a rectangle. Which point is the fourth corner?',
    diagram: { kind: 'coordinate', points: [{ x: 1, y: 1, label: 'A' }, { x: 5, y: 1, label: 'B' }, { x: 5, y: 3, label: 'C' }], max: 6 },
    choices: ['(1, 3)', '(3, 1)', '(5, 5)', '(1, 5)'], answer: '(1, 3)',
    hints: ['The corner must sit above A and level with C.', 'Take x from A and y from C.'],
    explanation: 'The fourth corner shares x = 1 with A and y = 3 with C: (1, 3).',
    solutions: [
      { title: 'Way 1: Match x and y', steps: [
        'The missing corner sits straight above A(1, 1), so its x is 1.',
        'It sits level with C(5, 3), so its y is 3.',
        'The fourth corner is (1, 3).',
      ] },
      { title: 'Way 2: Plot and trace', steps: [
        'Plot A, B, and C; the bottom and right sides of the rectangle appear.',
        'Slide left from C staying at height 3, and slide up from A staying at x = 1.',
        'The two paths meet at (1, 3), so the answer is (1, 3).',
      ] },
    ] },
  { id: 'geo-44', domain: '5.G', standard: '5.G.3', tier: 3, type: 'constructed',
    prompt: 'Ava says every parallelogram is a rectangle. Explain why she is wrong.',
    answer: 'angles', acceptable: ['right angles', 'no right angles', 'slanted', 'not always', 'lean'],
    hints: ['What extra rule does a rectangle have?', 'Picture a leaning parallelogram with no square corners.'],
    explanation: 'A rectangle needs 4 right angles, but many parallelograms lean and have none.',
    solutions: [
      { title: 'Way 1: Compare the rules', steps: [
        'A parallelogram only needs two pairs of parallel sides.',
        'A rectangle needs those parallel sides PLUS 4 right angles.',
        'Since a parallelogram can skip the right angles, Ava is wrong.',
      ] },
      { title: 'Way 2: Show a counterexample', steps: [
        'Picture a parallelogram pushed sideways so its corners are slanted.',
        'It still has two pairs of parallel sides, but no 90-degree angles.',
        'That shape is a parallelogram and NOT a rectangle, which proves Ava wrong.',
      ] },
    ] },
  { id: 'geo-45', domain: '5.G', standard: '5.G.4', tier: 3, type: 'multiple-choice',
    prompt: 'A triangle has sides 3 cm, 4 cm, and 6 cm. How is it classified by its sides?',
    choices: ['Scalene', 'Isosceles', 'Equilateral', 'Acute'], answer: 'Scalene',
    hints: ['Compare all three lengths.', 'No two sides match.'],
    explanation: 'All three sides are different lengths, so the triangle is scalene.',
    solutions: [
      { title: 'Way 1: Compare the sides', steps: [
        'The lengths are 3, 4, and 6 — check for matches.',
        'No two lengths are equal.',
        'A triangle with no equal sides is Scalene.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'Equilateral needs all sides equal — fails, since 3, 4, and 6 differ.',
        'Isosceles needs at least two equal sides — fails too.',
        'Acute describes angles, not sides.',
        'The side classification is Scalene.',
      ] },
    ] },
  { id: 'geo-46', domain: '5.G', standard: '5.G.2', tier: 3, type: 'numeric',
    prompt: 'A pirate starts at (2, 2), walks along gridlines to (7, 2), then up to the gold at (7, 6). How many units does she walk in all?',
    diagram: { kind: 'coordinate', points: [{ x: 2, y: 2, label: 'S' }, { x: 7, y: 2 }, { x: 7, y: 6, label: 'G' }], max: 8 },
    answer: '9', acceptable: ['9', '9 units'],
    hints: ['Find each leg separately: across, then up.', 'Across: 7 − 2 = 5. Up: 6 − 2 = 4. Add them.'],
    explanation: 'The walk is 5 units across plus 4 units up: 5 + 4 = 9 units.',
    solutions: [
      { title: 'Way 1: Add the two legs', steps: [
        'First leg is sideways: 7 − 2 = 5 units.',
        'Second leg is up: 6 − 2 = 4 units.',
        'Total walk: 5 + 4 = 9 units.',
      ] },
      { title: 'Way 2: Count every step', steps: [
        'Step right from x = 2 to x = 7: that is 5 steps.',
        'Step up from y = 2 to y = 6: that is 4 steps.',
        'Counting all steps gives 5 + 4 = 9 units.',
      ] },
    ] },
  { id: 'geo-47', domain: '5.G', standard: '5.G.1', tier: 3, type: 'multiple-choice',
    prompt: 'Which statement about the point (0, 6) is true?',
    choices: ['It lies on the y-axis', 'It lies on the x-axis', 'It is the origin', 'It is 6 units right of the origin'], answer: 'It lies on the y-axis',
    hints: ['Its x-coordinate is 0.', 'x = 0 means no steps right — straight up the vertical axis.'],
    explanation: 'With x = 0, the point never leaves the vertical axis: (0, 6) is on the y-axis.',
    solutions: [
      { title: 'Way 1: Use the x = 0 rule', steps: [
        'The first number of (0, 6) is 0, so the point moves 0 units right.',
        'Points with x = 0 sit on the vertical axis.',
        'So (0, 6) lies on the y-axis.',
      ] },
      { title: 'Way 2: Eliminate the others', steps: [
        'The x-axis needs y = 0, but here y = 6.',
        'The origin is (0, 0), and this point is 6 too high.',
        'It moves 6 up, not 6 right.',
        'The true statement is that it lies on the y-axis.',
      ] },
    ] },
  { id: 'geo-48', domain: '5.G', standard: '5.G.4', tier: 3, type: 'multiple-choice',
    prompt: 'A triangle has two equal sides and one right angle. Which names BOTH apply to it?',
    diagram: { kind: 'shape', shape: 'triangle' },
    choices: ['Right and isosceles', 'Right and equilateral', 'Obtuse and scalene', 'Acute and isosceles'], answer: 'Right and isosceles',
    hints: ['Classify by sides AND by angles separately.', 'Two equal sides = isosceles; one 90-degree angle = right.'],
    explanation: 'Two equal sides makes it isosceles, and a 90-degree angle makes it right.',
    solutions: [
      { title: 'Way 1: Classify twice', steps: [
        'By sides: two equal sides means isosceles.',
        'By angles: one 90-degree angle means right.',
        'Both names together: Right and isosceles.',
      ] },
      { title: 'Way 2: Eliminate the impostors', steps: [
        'Equilateral triangles have all 60-degree angles, so none can be right.',
        'Scalene means no equal sides, but this triangle has two.',
        'Acute means no angle reaches 90 degrees, but this one has a right angle.',
        'Only "Right and isosceles" fits.',
      ] },
    ] },
  { id: 'geo-49', domain: '5.G', standard: '5.G.2', tier: 3, type: 'numeric',
    prompt: 'A square has corners (1,1) and (4,1) along its bottom side. What is its AREA in square units?',
    diagram: { kind: 'coordinate', points: [{ x: 1, y: 1 }, { x: 4, y: 1 }], max: 6 },
    answer: '9', acceptable: ['9', '9 square units'],
    hints: ['Find the side length first: 4 − 1.', 'A square has equal sides, so area = side × side.'],
    explanation: 'The side is 4 − 1 = 3, so the area is 3 × 3 = 9 square units.',
    solutions: [
      { title: 'Way 1: Side length, then multiply', steps: [
        'The bottom runs from x = 1 to x = 4, so the side is 4 − 1 = 3 units.',
        'Every side of a square matches, so the height is also 3.',
        'Area = 3 × 3 = 9 square units.',
      ] },
      { title: 'Way 2: Build it row by row', steps: [
        'The bottom side is 3 units long, so each row holds 3 unit squares.',
        'A square needs 3 rows to match its width.',
        'Count 3 + 3 + 3 = 9 square units.',
      ] },
    ] },
  { id: 'geo-50', domain: '5.G', standard: '5.G.3', tier: 3, type: 'constructed',
    prompt: 'Can a trapezoid ever be a parallelogram? Explain using parallel sides.',
    answer: 'no', acceptable: ['no', 'one pair', 'exactly one', 'two pairs', 'parallel'],
    hints: ['How many pairs of parallel sides does each shape need?', 'Exactly one pair can never equal two pairs.'],
    explanation: 'No — a trapezoid has exactly one pair of parallel sides, but a parallelogram needs two.',
    solutions: [
      { title: 'Way 1: Compare the counts', steps: [
        'A trapezoid has exactly one pair of parallel sides.',
        'A parallelogram must have two pairs.',
        'One pair can never count as two, so the answer is no.',
      ] },
      { title: 'Way 2: Picture both shapes', steps: [
        'Picture a trapezoid: the top and bottom run parallel, but the slanted legs do not.',
        'A parallelogram needs BOTH pairs of opposite sides parallel.',
        'The slanted legs break that rule, so a trapezoid is never a parallelogram.',
      ] },
    ] },
  { id: 'geo-51', domain: '5.G', standard: '5.G.1', tier: 3, type: 'multiple-choice',
    prompt: 'Points follow the rule y = 2 × x. Which point fits the rule?',
    choices: ['(3, 6)', '(6, 3)', '(2, 2)', '(4, 6)'], answer: '(3, 6)',
    hints: ['Double the x-value — do you get y?', '2 × 3 = 6.'],
    explanation: 'For (3, 6): 2 × 3 = 6, a match; the other points fail the doubling rule.',
    solutions: [
      { title: 'Way 1: Test the winner', steps: [
        'The rule says y should be double x.',
        'For (3, 6): 2 × 3 = 6, which matches the y-value.',
        'So (3, 6) fits the rule.',
      ] },
      { title: 'Way 2: Rule out the rest', steps: [
        'For (6, 3): 2 × 6 = 12, not 3, so it fails.',
        'For (2, 2): 2 × 2 = 4, not 2, so it fails.',
        'For (4, 6): 2 × 4 = 8, not 6, so it fails.',
        'Only (3, 6) works.',
      ] },
    ] },
  { id: 'geo-52', domain: '5.G', standard: '5.G.2', tier: 4, type: 'numeric',
    prompt: 'Three corners of a rectangle are (0,1), (4,1), and (4,6). What is the PERIMETER of the rectangle?',
    diagram: { kind: 'coordinate', points: [{ x: 0, y: 1 }, { x: 4, y: 1 }, { x: 4, y: 6 }], max: 7 },
    answer: '18', acceptable: ['18', '18 units'],
    hints: ['First find the missing corner: it is at (0, 6).', 'Width = 4 − 0 = 4 and height = 6 − 1 = 5; use 2 × (4 + 5).'],
    explanation: 'The sides are 4 and 5, so the perimeter is 2 × (4 + 5) = 18 units.',
    solutions: [
      { title: 'Way 1: Find the sides, then use the formula', steps: [
        'Width along the bottom: 4 − 0 = 4 units.',
        'Height up the right side: 6 − 1 = 5 units.',
        'Perimeter = 2 × (4 + 5) = 2 × 9 = 18 units.',
      ] },
      { title: 'Way 2: Complete the rectangle and walk it', steps: [
        'The missing corner shares x = 0 and y = 6, so it is (0, 6).',
        'Walk the sides: bottom 4, right 5, top 4, left 5.',
        'Add 4 + 5 + 4 + 5 = 18 units.',
      ] },
    ] },
  { id: 'geo-53', domain: '5.G', standard: '5.G.3', tier: 4, type: 'multiple-choice',
    prompt: 'Which list orders the shapes from MOST general to MOST specific?',
    choices: ['Quadrilateral, parallelogram, rectangle, square', 'Square, rectangle, parallelogram, quadrilateral', 'Parallelogram, quadrilateral, square, rectangle', 'Rectangle, square, quadrilateral, parallelogram'], answer: 'Quadrilateral, parallelogram, rectangle, square',
    hints: ['General means the biggest family with the fewest rules.', 'Each step should ADD a rule: parallel sides, then right angles, then equal sides.'],
    explanation: 'Each name adds a rule: 4 sides, then parallel pairs, then right angles, then equal sides.',
    solutions: [
      { title: 'Way 1: Add one rule at a time', steps: [
        'Quadrilateral only asks for 4 sides — the loosest rule.',
        'Parallelogram adds two pairs of parallel sides.',
        'Rectangle adds 4 right angles, and square finally adds 4 equal sides.',
        'So the order is quadrilateral, parallelogram, rectangle, square.',
      ] },
      { title: 'Way 2: Think of nested boxes', steps: [
        'The biggest box holds every 4-sided shape: quadrilaterals.',
        'Inside it sits the parallelogram box, then the rectangle box.',
        'The smallest box inside them all is the square.',
        'Reading from the outside in gives quadrilateral, parallelogram, rectangle, square.',
      ] },
    ] },
  { id: 'geo-54', domain: '5.G', standard: '5.G.2', tier: 4, type: 'numeric',
    prompt: 'A rectangle has bottom corners (2,2) and (8,2), and its area is 24 square units. What is the y-coordinate of its TOP side?',
    answer: '6', acceptable: ['6', 'y=6', 'y = 6'],
    hints: ['Width = 8 − 2 = 6, so height = 24 ÷ 6.', 'Add the height to the bottom y-value: 2 + 4.'],
    explanation: 'Width 6 means height 24 ÷ 6 = 4, so the top sits at y = 2 + 4 = 6.',
    solutions: [
      { title: 'Way 1: Divide, then add', steps: [
        'Width along the bottom: 8 − 2 = 6 units.',
        'Height = area ÷ width = 24 ÷ 6 = 4 units.',
        'Top y = bottom y + height = 2 + 4 = 6.',
      ] },
      { title: 'Way 2: Guess and check the height', steps: [
        'The width is 6, so test heights: 6 × 3 = 18, too small.',
        'Try height 4: 6 × 4 = 24, a perfect match.',
        'Starting at y = 2 and rising 4 puts the top side at y = 6.',
      ] },
    ] },
  { id: 'geo-55', domain: '5.G', standard: '5.G.3', tier: 4, type: 'constructed',
    prompt: 'Mia says: if a rhombus has 4 right angles, it must be a square. Is she right? Explain.',
    answer: 'yes', acceptable: ['yes', 'equal sides', 'right angles', 'square', 'correct'],
    hints: ['List what the shape now has: equal sides AND right angles.', 'Which shape is defined by both of those?'],
    explanation: 'Yes — 4 equal sides plus 4 right angles is exactly the definition of a square.',
    solutions: [
      { title: 'Way 1: Stack the properties', steps: [
        'A rhombus already has 4 equal sides.',
        'Adding 4 right angles gives equal sides AND right angles together.',
        'That is exactly a square, so Mia is right.',
      ] },
      { title: 'Way 2: Use the hierarchy', steps: [
        'A rhombus with right angles also passes the rectangle test.',
        'A shape that is both a rhombus and a rectangle sits in the overlap of the two families.',
        'That overlap is the square family, so yes, Mia is right.',
      ] },
    ] },
  { id: 'geo-56', domain: '5.G', standard: '5.G.1', tier: 4, type: 'numeric',
    prompt: 'Point P is at (3, 4). Point Q has the same numbers but with x and y swapped. Write Q as x,y (write like 7,2).',
    answer: '4,3', acceptable: ['(4,3)', '4, 3', '4 3'],
    hints: ['Swap means the first and second numbers trade places.', 'The 4 becomes x and the 3 becomes y.'],
    explanation: 'Swapping the numbers in (3, 4) gives the different point (4, 3).',
    solutions: [
      { title: 'Way 1: Do the swap', steps: [
        'P is (3, 4): x = 3 and y = 4.',
        'Trading places gives x = 4 and y = 3.',
        'So Q is 4,3.',
      ] },
      { title: 'Way 2: Plot both points', steps: [
        'P is 3 right and 4 up.',
        'Swapping the moves means Q goes 4 right and 3 up instead.',
        'That landing spot is the point 4,3.',
      ] },
    ] },
  { id: 'geo-57', domain: '5.G', standard: '5.G.4', tier: 4, type: 'multiple-choice',
    prompt: 'Which triangle is IMPOSSIBLE to draw?',
    choices: ['A right equilateral triangle', 'A right isosceles triangle', 'An obtuse scalene triangle', 'An acute equilateral triangle'], answer: 'A right equilateral triangle',
    hints: ['Every angle in an equilateral triangle is 60 degrees.', 'Can a 60-degree angle ever be a 90-degree angle?'],
    explanation: 'An equilateral triangle has all 60-degree angles, so it can never contain a 90-degree angle.',
    solutions: [
      { title: 'Way 1: Check the equilateral angles', steps: [
        'In an equilateral triangle, all three angles are equal.',
        'They must each be 60 degrees, never 90.',
        'So a right equilateral triangle is impossible.',
      ] },
      { title: 'Way 2: Draw the other three', steps: [
        'A right isosceles triangle works: 90, 45, and 45 degrees with two equal sides.',
        'An obtuse scalene triangle works: angles like 120, 40, 20 with all sides different.',
        'An acute equilateral triangle is every equilateral triangle.',
        'The only one you cannot draw is the right equilateral triangle.',
      ] },
    ] },
  { id: 'geo-58', domain: '5.G', standard: '5.G.4', tier: 4, type: 'constructed',
    prompt: 'Jon says a triangle can have TWO right angles. Explain why he is wrong.',
    answer: 'no', acceptable: ['no', '180', 'third angle', 'never meet', 'parallel'],
    hints: ['Try drawing two 90-degree corners on one segment.', 'What happens to the two sides going up?'],
    explanation: 'Two right angles would make two sides rise straight up in parallel and never meet at a third corner.',
    solutions: [
      { title: 'Way 1: Try to draw it', steps: [
        'Draw a base and stand a 90-degree side at each end.',
        'Both sides go straight up, perfectly parallel.',
        'Parallel sides never meet, so no third corner forms — Jon is wrong.',
      ] },
      { title: 'Way 2: Add up the angles', steps: [
        'The three angles of a triangle always total 180 degrees.',
        'Two right angles already use 90 + 90 = 180 degrees.',
        'That leaves 0 degrees for the third angle, which is impossible, so Jon is wrong.',
      ] },
    ] },
  { id: 'geo-59', domain: '5.G', standard: '5.G.2', tier: 4, type: 'numeric',
    prompt: 'A playground is a rectangle with corners (2,1), (9,1), (9,4), (2,4). How many SQUARE units does it cover?',
    diagram: { kind: 'coordinate', points: [{ x: 2, y: 1 }, { x: 9, y: 1 }, { x: 9, y: 4 }, { x: 2, y: 4 }], max: 10 },
    answer: '21', acceptable: ['21', '21 square units'],
    hints: ['Width = 9 − 2; height = 4 − 1.', 'Area = width × height = 7 × 3.'],
    explanation: 'Width 7 and height 3 give area 7 × 3 = 21 square units.',
    solutions: [
      { title: 'Way 1: Subtract, then multiply', steps: [
        'Width: 9 − 2 = 7 units.',
        'Height: 4 − 1 = 3 units.',
        'Area = 7 × 3 = 21 square units.',
      ] },
      { title: 'Way 2: Count rows of squares', steps: [
        'Each row from x = 2 to x = 9 holds 7 unit squares.',
        'The playground rises from y = 1 to y = 4, making 3 rows.',
        'Count 7 + 7 + 7 = 21 square units.',
      ] },
    ] },
  { id: 'geo-60', domain: '5.G', standard: '5.G.1', tier: 4, type: 'multiple-choice',
    prompt: 'Points follow the rule: the y-coordinate is 3 times the x-coordinate. Which point does NOT fit?',
    choices: ['(3, 6)', '(1, 3)', '(2, 6)', '(3, 9)'], answer: '(3, 6)',
    hints: ['Multiply each x by 3 and compare to y.', '3 × 3 = 9, not 6.'],
    explanation: 'For (3, 6): 3 × 3 = 9, not 6, so that point breaks the rule.',
    solutions: [
      { title: 'Way 1: Test every point', steps: [
        'For (1, 3): 3 × 1 = 3, a match. For (2, 6): 3 × 2 = 6, a match.',
        'For (3, 9): 3 × 3 = 9, a match.',
        'For (3, 6): 3 × 3 = 9, but y is 6 — no match.',
        'The point that does NOT fit is (3, 6).',
      ] },
      { title: 'Way 2: Predict y from each x', steps: [
        'Triple each x-value: x = 1 needs y = 3, x = 2 needs y = 6, x = 3 needs y = 9.',
        'Three points hit their required y exactly.',
        '(3, 6) should have y = 9 but shows 6, so (3, 6) breaks the rule.',
      ] },
    ] },
];
