import type { Problem, Lesson } from '../types';

// ===========================================================================
// 5.G — Geometry (coordinate plane, classifying 2D shapes)
// ===========================================================================

export const lessons: Lesson[] = [
  {
    domain: '5.G', standard: '5.G.1',
    title: 'The Coordinate Plane',
    steps: [
      'A point is written (x, y).',
      'x tells you how far RIGHT from 0; y tells you how far UP.',
      'Always move along x FIRST, then y.',
      'The origin is (0, 0).',
    ],
    example: '(3, 2) means 3 right and 2 up.',
    tip: 'Remember "x comes before y" just like in the alphabet — and you walk before you climb.',
  },
  {
    domain: '5.G', standard: '5.G.3',
    title: 'Classify Triangles & Quadrilaterals',
    steps: [
      'A square is a special rectangle (4 right angles + all sides equal).',
      'A rectangle is a special parallelogram.',
      'A rhombus has 4 equal sides; a square is a rhombus too.',
      'Properties of a category belong to ALL shapes in it.',
    ],
    example: 'Every square is a rectangle, but not every rectangle is a square.',
    tip: 'Think of nested boxes: squares ⊂ rectangles ⊂ parallelograms ⊂ quadrilaterals.',
  },
];

export const problems: Problem[] = [
  { id: 'geo-1', domain: '5.G', standard: '5.G.1', tier: 1, type: 'multiple-choice',
    prompt: 'Which point is at (3, 1)?',
    diagram: { kind: 'coordinate', points: [{ x: 3, y: 1, label: 'A' }, { x: 1, y: 3, label: 'B' }], max: 6 },
    choices: ['A', 'B', 'Neither', 'Both'], answer: 'A',
    hints: ['x first (right), then y (up).', '3 right and 1 up.'],
    explanation: '(3,1) means 3 right, 1 up — that is point A. Point B at (1,3) is the swap.' },
  { id: 'geo-2', domain: '5.G', standard: '5.G.3', tier: 1, type: 'multiple-choice',
    prompt: 'A shape has 4 equal sides and 4 right angles. What is it?',
    diagram: { kind: 'shape', shape: 'square' },
    choices: ['Square', 'Triangle', 'Trapezoid', 'Circle'], answer: 'Square',
    hints: ['4 right angles AND all sides equal.'],
    explanation: '4 right angles + 4 equal sides = a square.' },
  { id: 'geo-3', domain: '5.G', standard: '5.G.1', tier: 2, type: 'numeric',
    prompt: 'Start at (0,0). Move 4 right and 3 up. Write the point as x,y (e.g. 4,3).',
    answer: '4,3', acceptable: ['(4,3)', '4, 3', '4 3'],
    hints: ['x = right amount, y = up amount.'],
    explanation: '4 right and 3 up from the origin is (4, 3).' },
  { id: 'geo-4', domain: '5.G', standard: '5.G.3', tier: 2, type: 'multiple-choice',
    prompt: 'Which statement is ALWAYS true?',
    choices: ['Every square is a rectangle', 'Every rectangle is a square', 'Every triangle is a square', 'No square is a rectangle'], answer: 'Every square is a rectangle',
    hints: ['A square has all the properties of a rectangle plus equal sides.'],
    explanation: 'A square meets every rule of a rectangle (4 right angles), so every square IS a rectangle. The reverse is not true.' },
  { id: 'geo-5', domain: '5.G', standard: '5.G.2', tier: 3, type: 'numeric',
    prompt: 'A path goes from (1,2) to (1,6). How many units long is it?',
    diagram: { kind: 'coordinate', points: [{ x: 1, y: 2, label: 'P' }, { x: 1, y: 6, label: 'Q' }], max: 8 },
    answer: '4', acceptable: ['4', '4 units'],
    hints: ['Same x, so just compare the y-values.', '6 − 2.'],
    explanation: 'Same x = 1, so the length is the change in y: 6 − 2 = 4 units.' },
  { id: 'geo-6', domain: '5.G', standard: '5.G.4', tier: 3, type: 'multiple-choice',
    prompt: 'Which quadrilateral has exactly ONE pair of parallel sides?',
    diagram: { kind: 'shape', shape: 'trapezoid' },
    choices: ['Trapezoid', 'Rectangle', 'Rhombus', 'Square'], answer: 'Trapezoid',
    hints: ['Parallelograms have TWO pairs.', 'Which one has only one pair?'],
    explanation: 'A trapezoid has exactly one pair of parallel sides; the others all have two pairs.' },
  { id: 'geo-7', domain: '5.G', standard: '5.G.2', tier: 4, type: 'numeric',
    prompt: 'A rectangle has corners (1,1), (5,1), (5,4), (1,4). What is its AREA?',
    answer: '12', acceptable: ['12', '12 square units'],
    hints: ['Width = 5 − 1 = 4. Height = 4 − 1 = 3.', 'Area = width × height.'],
    explanation: 'Width = 4, height = 3, so area = 4 × 3 = 12 square units.' },
  { id: 'geo-8', domain: '5.G', standard: '5.G.3', tier: 4, type: 'constructed',
    prompt: 'Is a rhombus always a square? Explain why or why not.',
    answer: 'no', acceptable: ['no', 'angles', 'not always'],
    hints: ['A rhombus has 4 equal sides.', 'Does it always have right angles?'],
    explanation: 'No. A rhombus has 4 equal sides but its angles do not have to be right angles. Only when all 4 angles are 90° is the rhombus also a square.' },
  { id: 'geo-9', domain: '5.G', standard: '5.G.1', tier: 1, type: 'numeric',
    prompt: 'What is the y-coordinate of the point (2, 7)?', answer: '7', acceptable: ['7'],
    hints: ['Points are written (x, y) — y is second.'],
    explanation: 'In (2, 7) the second number is y, so y = 7.' },
  { id: 'geo-10', domain: '5.G', standard: '5.G.1', tier: 2, type: 'multiple-choice',
    prompt: 'Which point lies ON the x-axis?',
    choices: ['(5, 0)', '(0, 5)', '(5, 5)', '(1, 5)'], answer: '(5, 0)',
    hints: ['On the x-axis, the height (y) is 0.'],
    explanation: 'A point on the x-axis has y = 0, so (5, 0) is on the x-axis. (0, 5) is on the y-axis.' },
  { id: 'geo-11', domain: '5.G', standard: '5.G.4', tier: 2, type: 'multiple-choice',
    prompt: 'A triangle has all three sides the same length. What kind is it?',
    diagram: { kind: 'shape', shape: 'triangle' },
    choices: ['Equilateral', 'Scalene', 'Right', 'Obtuse'], answer: 'Equilateral',
    hints: ['"Equi-" means equal.'],
    explanation: 'All sides equal = equilateral. (Scalene = no equal sides; isosceles = at least two equal.)' },
  { id: 'geo-12', domain: '5.G', standard: '5.G.2', tier: 3, type: 'numeric',
    prompt: 'A rectangle has corners (0,0), (6,0), (6,3), (0,3). What is its PERIMETER?',
    diagram: { kind: 'coordinate', points: [{ x: 0, y: 0 }, { x: 6, y: 0 }, { x: 6, y: 3 }, { x: 0, y: 3 }], max: 7 },
    answer: '18', acceptable: ['18', '18 units'],
    hints: ['Width = 6, height = 3.', 'Perimeter = 2 × (6 + 3).'],
    explanation: 'Sides are 6 and 3, so perimeter = 2 × (6 + 3) = 18 units.' },
  { id: 'geo-13', domain: '5.G', standard: '5.G.3', tier: 3, type: 'multiple-choice',
    prompt: 'Which statement is ALWAYS true?',
    choices: ['All rhombuses are parallelograms', 'All parallelograms are rhombuses', 'All trapezoids are parallelograms', 'All rectangles are squares'], answer: 'All rhombuses are parallelograms',
    hints: ['A rhombus has two pairs of parallel sides.', 'Categories nest: rhombus ⊂ parallelogram.'],
    explanation: 'Every rhombus has two pairs of parallel sides, so it IS a parallelogram. The reverse fails (a non-square rectangle is a parallelogram but not a rhombus).' },
  { id: 'geo-14', domain: '5.G', standard: '5.G.2', tier: 4, type: 'numeric',
    prompt: 'Three corners of a rectangle are (2,1), (7,1), and (7,5). Where is the FOURTH corner? (write like 2,5)',
    answer: '2,5', acceptable: ['(2,5)', '2, 5', '2 5'],
    hints: ['It must line up with (2,1) vertically and (7,5) horizontally.'],
    explanation: 'The fourth corner shares x = 2 with (2,1) and y = 5 with (7,5): the point (2, 5).' },
  { id: 'geo-15', domain: '5.G', standard: '5.G.1', tier: 4, type: 'multiple-choice',
    prompt: 'A pattern of points follows the rule "y = x + 2". Which point fits the rule?',
    choices: ['(3, 5)', '(5, 3)', '(2, 2)', '(4, 8)'], answer: '(3, 5)',
    hints: ['Add 2 to x — do you get y?', '3 + 2 = 5 ✓'],
    explanation: 'For (3, 5): y = 3 + 2 = 5 ✓. The others fail the rule. (This previews graphing relationships!)' },
];
