import type { Problem, Lesson } from '../types';

// ===========================================================================
// 5.MD — Measurement & Data (unit conversion, line plots, volume)
// ===========================================================================

export const lessons: Lesson[] = [
  {
    domain: '5.MD', standard: '5.MD.1',
    title: 'Convert Measurement Units',
    steps: [
      'Know the key facts: 1 ft = 12 in, 1 m = 100 cm, 1 km = 1000 m, 1 lb = 16 oz, 1 gal = 4 qt.',
      'Bigger unit → smaller unit: MULTIPLY.',
      'Smaller unit → bigger unit: DIVIDE.',
    ],
    example: '3 ft = 3 × 12 = 36 in.',
    tip: 'Write the units beside the numbers so you can check they cancel correctly.',
  },
  {
    domain: '5.MD', standard: '5.MD.5',
    title: 'Volume of Rectangular Prisms',
    steps: [
      'Volume = length × width × height (V = l × w × h).',
      'You can also do V = base area × height.',
      'For an irregular solid, split it into boxes and add the volumes.',
      'Volume is measured in CUBIC units (cm³, in³).',
    ],
    example: 'A box 4 × 3 × 2 has V = 4 × 3 × 2 = 24 cubic units.',
    tip: 'Count layers: base layer of l×w cubes, stacked h high.',
  },
  {
    domain: '5.MD', standard: '5.MD.2',
    title: 'Line Plots with Fractions',
    steps: [
      'Each X on the line plot is one data point at that value.',
      'To find a total, multiply each value by how many Xs, then add.',
      'You can redistribute amounts evenly to find a fair share.',
    ],
    example: 'Three plants at 1/4 cup → 3 × 1/4 = 3/4 cup total.',
    tip: 'Line plots often ask for the difference between the tallest and shortest stacks.',
  },
];

export const problems: Problem[] = [
  { id: 'md-1', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'numeric',
    prompt: 'How many inches are in 2 feet?', answer: '24', acceptable: ['24', '24 in'],
    hints: ['1 foot = 12 inches.', '2 × 12.'],
    explanation: '2 ft × 12 in/ft = 24 inches.',
    solutions: [
      { title: 'Way 1: Multiply by the conversion factor', steps: [
        'Feet are bigger than inches, and 1 foot equals 12 inches.',
        'Going from a bigger unit to a smaller unit means multiply: 2 × 12 = 24.',
        'So 2 feet equals 24 inches.',
      ] },
      { title: 'Way 2: Count up foot by foot', steps: [
        'The first foot is 12 inches.',
        'The second foot adds 12 more inches: 12 + 12 = 24.',
        'So 2 feet equals 24 inches.',
      ] },
    ] },
  { id: 'md-2', domain: '5.MD', standard: '5.MD.5', tier: 1, type: 'numeric',
    prompt: 'Find the volume of a box 5 long, 2 wide, 3 high.',
    diagram: { kind: 'prism', l: 5, w: 2, h: 3 },
    answer: '30', acceptable: ['30', '30 cubic units'],
    hints: ['V = l × w × h.', '5 × 2 × 3.'],
    explanation: 'V = 5 × 2 × 3 = 30 cubic units.',
    solutions: [
      { title: 'Way 1: Use V = l × w × h', steps: [
        'Multiply length times width first: 5 × 2 = 10.',
        'Then multiply by the height: 10 × 3 = 30.',
        'The volume is 30 cubic units.',
      ] },
      { title: 'Way 2: Count cube layers', steps: [
        'The bottom layer holds 5 × 2 = 10 unit cubes.',
        'The box is 3 layers high, so stack 3 layers: 10 + 10 + 10 = 30.',
        'The volume is 30 cubic units.',
      ] },
    ] },
  { id: 'md-3', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'numeric',
    prompt: 'A rope is 250 cm long. How many meters is that?', answer: '2.5', acceptable: ['2.5', '2.5 m'],
    hints: ['1 m = 100 cm.', 'Smaller→bigger: divide by 100.'],
    explanation: '250 cm ÷ 100 = 2.5 m.',
    solutions: [
      { title: 'Way 1: Divide by 100', steps: [
        'Centimeters are smaller than meters, and 100 cm make 1 m.',
        'Smaller unit to bigger unit means divide: 250 ÷ 100 = 2.5.',
        'The rope is 2.5 meters long.',
      ] },
      { title: 'Way 2: Break the length apart', steps: [
        'Split 250 cm into 200 cm and 50 cm.',
        '200 cm is 2 whole meters, and 50 cm is half a meter, or 0.5 m.',
        'Add the parts: 2 + 0.5 = 2.5 meters.',
      ] },
    ] },
  { id: 'md-4', domain: '5.MD', standard: '5.MD.5', tier: 2, type: 'numeric',
    prompt: 'A fish tank is 8 × 4 × 5 inches. What is its volume in cubic inches?',
    diagram: { kind: 'prism', l: 8, w: 4, h: 5 },
    answer: '160', acceptable: ['160'],
    hints: ['Base area = 8 × 4 = 32.', 'Times height 5.'],
    explanation: 'V = 8 × 4 × 5 = 160 cubic inches.',
    solutions: [
      { title: 'Way 1: Base area times height', steps: [
        'The base of the tank is 8 × 4 = 32 square inches.',
        'Multiply the base area by the height: 32 × 5 = 160.',
        'The volume is 160 cubic inches.',
      ] },
      { title: 'Way 2: Group the factors differently', steps: [
        'You can multiply in any order, so try 4 × 5 = 20 first.',
        'Then 20 × 8 = 160.',
        'The volume is 160 cubic inches.',
      ] },
    ] },
  { id: 'md-5', domain: '5.MD', standard: '5.MD.2', tier: 3, type: 'numeric',
    prompt: 'On a line plot, 4 cups hold 1/2 L each and 2 cups hold 1/4 L each. Total liters?',
    answer: '2.5', acceptable: ['2.5', '5/2', '2 1/2'],
    hints: ['4 × 1/2 = 2 L.', '2 × 1/4 = 1/2 L. Add.'],
    explanation: '4 × 1/2 = 2 L; 2 × 1/4 = 1/2 L; total = 2 1/2 = 2.5 L.',
    solutions: [
      { title: 'Way 1: Multiply each value, then add', steps: [
        'Four cups hold 1/2 L each: 4 × 1/2 = 2 liters.',
        'Two cups hold 1/4 L each: 2 × 1/4 = 1/2 liter.',
        'Add the amounts: 2 + 1/2 = 2 1/2, so the total is 2.5 liters.',
      ] },
      { title: 'Way 2: Count everything in fourths', steps: [
        'Each 1/2 L is 2 fourths, so 4 cups give 4 × 2 = 8 fourths.',
        'Each 1/4 L is 1 fourth, so 2 cups give 2 fourths.',
        'That is 8 + 2 = 10 fourths, and 10/4 = 2 1/2, so the total is 2.5 liters.',
      ] },
    ] },
  { id: 'md-6', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'numeric',
    prompt: 'An L-shaped solid is made of a 3×3×2 box plus a 3×1×2 box. Total volume?',
    answer: '24', acceptable: ['24'],
    hints: ['Find each box: 3×3×2 and 3×1×2.', '18 + 6.'],
    explanation: 'First box 3×3×2 = 18; second 3×1×2 = 6; total = 18 + 6 = 24 cubic units.',
    solutions: [
      { title: 'Way 1: Add the two boxes', steps: [
        'The first box has volume 3 × 3 × 2 = 18 cubic units.',
        'The second box has volume 3 × 1 × 2 = 6 cubic units.',
        'Add them: 18 + 6 = 24 cubic units in all.',
      ] },
      { title: 'Way 2: Combine the bases first', steps: [
        'Both boxes are 3 long and 2 tall, so look at their widths: 3 and 1.',
        'Together the base is 3 long and 3 + 1 = 4 wide, an area of 12 squares.',
        'Multiply by the height: 12 × 2 = 24 cubic units.',
      ] },
    ] },
  { id: 'md-7', domain: '5.MD', standard: '5.MD.1', tier: 4, type: 'numeric',
    prompt: 'A race is 2.5 km. A runner has gone 1750 m. How many METERS are left?',
    answer: '750', acceptable: ['750', '750 m'],
    hints: ['2.5 km = 2500 m.', '2500 − 1750.'],
    explanation: '2.5 km = 2500 m; 2500 − 1750 = 750 m left.',
    solutions: [
      { title: 'Way 1: Convert, then subtract', steps: [
        'First make the units match: 2.5 km × 1000 = 2500 meters.',
        'Subtract the distance already run: 2500 − 1750 = 750.',
        'The runner has 750 meters left.',
      ] },
      { title: 'Way 2: Count up to the finish', steps: [
        'The race is 2.5 km, which is 2500 meters.',
        'From 1750, add 250 to reach 2000, then 500 more to reach 2500.',
        'That is 250 + 500 = 750 meters left.',
      ] },
    ] },
  { id: 'md-8', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'constructed',
    prompt: 'A box has volume 48 cm³ and a base of 6 cm × 2 cm. Explain how to find its height.',
    answer: '4', acceptable: ['4', '4 cm', 'divide'],
    hints: ['Base area = 6 × 2 = 12.', 'Height = Volume ÷ base area.'],
    explanation: 'Base area = 6 × 2 = 12 cm². Since V = base × height, height = 48 ÷ 12 = 4 cm.',
    solutions: [
      { title: 'Way 1: Divide by the base area', steps: [
        'Find the base area first: 6 × 2 = 12 square cm.',
        'Volume equals base area times height, so height = volume ÷ base area.',
        'Divide: 48 ÷ 12 = 4, so the height is 4 cm.',
      ] },
      { title: 'Way 2: Find the missing factor', steps: [
        'Write the volume equation with a blank: 6 × 2 × h = 48.',
        'Simplify the known part: 12 × h = 48.',
        'Ask what number times 12 makes 48: 12 × 4 = 48, so the height is 4 cm.',
      ] },
      { title: 'Way 3: Stack layers until you reach 48', steps: [
        'Each 1 cm layer of the box holds 6 × 2 = 12 cubes.',
        'Count layers: 12, 24, 36, 48 — that took 4 layers.',
        'So the box must be 4 cm tall.',
      ] },
    ] },
  { id: 'md-9', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'numeric',
    prompt: 'How many grams are in 3 kilograms?', answer: '3000', acceptable: ['3000', '3,000', '3000 g'],
    hints: ['1 kg = 1000 g.', 'Bigger → smaller unit: multiply.'],
    explanation: '3 kg × 1000 = 3000 grams.',
    solutions: [
      { title: 'Way 1: Multiply by 1000', steps: [
        'One kilogram equals 1000 grams.',
        'Kilograms are bigger, so multiply: 3 × 1000 = 3000.',
        'There are 3000 grams in 3 kilograms.',
      ] },
      { title: 'Way 2: Add kilogram by kilogram', steps: [
        'Each kilogram is 1000 grams.',
        'Add three of them: 1000 + 1000 + 1000 = 3000.',
        'So 3 kilograms is 3000 grams.',
      ] },
    ] },
  { id: 'md-10', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'numeric',
    prompt: 'How many quarts are in 3 gallons?', answer: '12', acceptable: ['12', '12 quarts'],
    hints: ['1 gallon = 4 quarts.'],
    explanation: '3 gal × 4 qt/gal = 12 quarts.',
    solutions: [
      { title: 'Way 1: Multiply by 4', steps: [
        'One gallon equals 4 quarts.',
        'Gallons are bigger, so multiply: 3 × 4 = 12.',
        'There are 12 quarts in 3 gallons.',
      ] },
      { title: 'Way 2: Build a ratio table', steps: [
        'Start the table: 1 gallon is 4 quarts.',
        'Keep adding 4: 2 gallons is 8 quarts, 3 gallons is 12 quarts.',
        'So 3 gallons equals 12 quarts.',
      ] },
    ] },
  { id: 'md-11', domain: '5.MD', standard: '5.MD.2', tier: 2, type: 'multiple-choice',
    prompt: 'A line plot shows plant heights: two Xs at 1/2 in, three Xs at 3/4 in. What is the DIFFERENCE between the tallest and shortest heights?',
    choices: ['1/4 in', '1/2 in', '3/4 in', '1 in'], answer: '1/4 in',
    hints: ['Tallest value 3/4, shortest 1/2.', '3/4 − 1/2 = 3/4 − 2/4.'],
    explanation: '3/4 − 1/2 = 3/4 − 2/4 = 1/4 inch.',
    solutions: [
      { title: 'Way 1: Subtract with a common denominator', steps: [
        'The tallest height is 3/4 in and the shortest is 1/2 in.',
        'Rewrite 1/2 as 2/4 so both fractions count fourths.',
        'Subtract: 3/4 − 2/4 = 1/4, so the difference is 1/4 in.',
      ] },
      { title: 'Way 2: Count up on a number line', steps: [
        'Start at 1/2, which is the same as 2/4.',
        'Hop by fourths until you reach 3/4: that takes just one hop of 1/4.',
        'So the difference between the heights is 1/4 in.',
      ] },
    ] },
  { id: 'md-12', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'numeric',
    prompt: 'How many MINUTES are in 2 1/4 hours?', answer: '135', acceptable: ['135', '135 min'],
    hints: ['1 hour = 60 min, so 2 hours = 120.', '1/4 hour = 15 min.'],
    explanation: '2 × 60 = 120; 1/4 × 60 = 15; total = 135 minutes.',
    solutions: [
      { title: 'Way 1: Split into hours and a quarter hour', steps: [
        'Two whole hours is 2 × 60 = 120 minutes.',
        'A quarter of an hour is 60 ÷ 4 = 15 minutes.',
        'Add the parts: 120 + 15 = 135 minutes.',
      ] },
      { title: 'Way 2: Multiply by the fraction', steps: [
        'Write 2 1/4 as the fraction 9/4.',
        'Multiply by 60: 9/4 × 60 = 540 ÷ 4.',
        '540 ÷ 4 = 135, so 2 1/4 hours is 135 minutes.',
      ] },
    ] },
  { id: 'md-13', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'numeric',
    prompt: 'A cube has edges 4 cm long. What is its volume in cm³?',
    diagram: { kind: 'prism', l: 4, w: 4, h: 4 },
    answer: '64', acceptable: ['64'],
    hints: ['All edges equal: V = 4 × 4 × 4.'],
    explanation: 'V = 4 × 4 × 4 = 64 cm³.',
    solutions: [
      { title: 'Way 1: Multiply the three edges', steps: [
        'A cube has equal length, width, and height, so V = 4 × 4 × 4.',
        'Work left to right: 4 × 4 = 16, then 16 × 4 = 64.',
        'The volume is 64 cm³.',
      ] },
      { title: 'Way 2: Count cube layers', steps: [
        'The bottom layer is 4 × 4 = 16 centimeter cubes.',
        'There are 4 layers, so skip count: 16, 32, 48, 64.',
        'The volume is 64 cm³.',
      ] },
    ] },
  { id: 'md-14', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'numeric',
    prompt: 'A box has volume 90 in³. Its length is 5 in and width is 3 in. What is its HEIGHT?',
    answer: '6', acceptable: ['6', '6 in'],
    hints: ['Base area = 5 × 3 = 15.', 'Height = 90 ÷ 15.'],
    explanation: 'V = l × w × h, so h = 90 ÷ (5 × 3) = 90 ÷ 15 = 6 inches.',
    solutions: [
      { title: 'Way 1: Divide by the base area', steps: [
        'The base area is length times width: 5 × 3 = 15 square inches.',
        'Height equals volume divided by base area: 90 ÷ 15 = 6.',
        'The height is 6 inches.',
      ] },
      { title: 'Way 2: Find the missing factor', steps: [
        'Write the equation 5 × 3 × h = 90, which is 15 × h = 90.',
        'Think: 15 times what number is 90? Since 15 × 6 = 90, h = 6.',
        'The height is 6 inches.',
      ] },
    ] },
  { id: 'md-15', domain: '5.MD', standard: '5.MD.1', tier: 4, type: 'numeric',
    prompt: 'A package weighs 5 pounds 4 ounces. How many OUNCES is that in total?',
    answer: '84', acceptable: ['84', '84 oz'],
    hints: ['1 lb = 16 oz.', '5 × 16 = 80, then add the extra 4.'],
    explanation: '5 lb = 80 oz; 80 + 4 = 84 ounces.',
    solutions: [
      { title: 'Way 1: Convert the pounds, then add', steps: [
        'One pound equals 16 ounces, so 5 pounds is 5 × 16 = 80 ounces.',
        'Add the extra 4 ounces: 80 + 4 = 84.',
        'The package weighs 84 ounces.',
      ] },
      { title: 'Way 2: Use a ratio table', steps: [
        'List pounds and ounces: 1 lb is 16, 2 lb is 32, 3 lb is 48, 4 lb is 64, 5 lb is 80.',
        'The package is 5 lb 4 oz, so add 4 to 80.',
        '80 + 4 = 84 ounces in total.',
      ] },
    ] },
  { id: 'md-16', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'constructed',
    prompt: 'Two different boxes BOTH have volume 24 cubic units. Give possible dimensions for each and explain how that can happen.',
    answer: '24', acceptable: ['2x3x4', '1x4x6', '2 × 3 × 4', '1 × 4 × 6', 'same volume'],
    hints: ['Find numbers that multiply to 24.', 'Try 2 × 3 × 4 and 1 × 4 × 6.'],
    explanation: '2 × 3 × 4 = 24 and 1 × 4 × 6 = 24. Different shapes can hold the same amount — volume only depends on the PRODUCT of the dimensions.',
    solutions: [
      { title: 'Way 1: Hunt for factor triples of 24', steps: [
        'Volume is length × width × height, so find three numbers that multiply to 24.',
        'One choice is 2 × 3 × 4 = 24.',
        'Another is 1 × 4 × 6 = 24, so two different boxes can both have volume 24.',
      ] },
      { title: 'Way 2: Double one dimension, halve another', steps: [
        'Start with a 2 × 3 × 4 box, which has volume 24.',
        'Halve the 2 to get 1 and double the 3 to get 6: now the box is 1 × 6 × 4.',
        'The product stays 24, so both boxes hold the same volume of 24 cubic units.',
      ] },
    ] },
  { id: 'md-17', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'multiple-choice',
    prompt: 'How many centimeters are in 4 meters?',
    choices: ['40', '400', '4,000', '44'], answer: '400',
    hints: ['1 m = 100 cm.', 'Bigger → smaller unit: multiply by 100.'],
    explanation: '4 m × 100 = 400 cm.',
    solutions: [
      { title: 'Way 1: Multiply by 100', steps: [
        'One meter equals 100 centimeters.',
        'Meters are bigger, so multiply: 4 × 100 = 400.',
        'There are 400 centimeters in 4 meters.',
      ] },
      { title: 'Way 2: Use a ratio table', steps: [
        'Start with 1 m = 100 cm.',
        'Keep adding 100: 2 m is 200, 3 m is 300, 4 m is 400.',
        'So 4 meters equals 400 centimeters.',
      ] },
    ] },
  { id: 'md-18', domain: '5.MD', standard: '5.MD.4', tier: 1, type: 'numeric',
    prompt: 'A box is packed with unit cubes. Each layer has 6 cubes, and there are 2 layers. How many cubes fill the box?',
    diagram: { kind: 'prism', l: 3, w: 2, h: 2 },
    answer: '12', acceptable: ['12', '12 cubes'],
    hints: ['Each layer has 6 cubes.', 'Two layers: 6 + 6.'],
    explanation: '2 layers × 6 cubes = 12 cubes.',
    solutions: [
      { title: 'Way 1: Add the layers', steps: [
        'The bottom layer has 6 cubes.',
        'The top layer has 6 more: 6 + 6 = 12.',
        'It takes 12 cubes to fill the box.',
      ] },
      { title: 'Way 2: Multiply cubes per layer by layers', steps: [
        'There are 6 cubes in each layer and 2 layers.',
        'Multiply: 6 × 2 = 12.',
        'The box holds 12 unit cubes.',
      ] },
    ] },
  { id: 'md-19', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'multiple-choice',
    prompt: 'Which unit is BEST for measuring the weight of a paper clip?',
    choices: ['grams', 'kilograms', 'liters', 'meters'], answer: 'grams',
    hints: ['A paper clip is very light.', 'Liters measure liquid and meters measure length.'],
    explanation: 'A paper clip weighs about 1 gram, so grams fit best.',
    solutions: [
      { title: 'Way 1: Think about the size of the object', steps: [
        'A paper clip is tiny and very light.',
        'A gram is a tiny unit of weight, about the weight of one paper clip.',
        'So grams are the best unit.',
      ] },
      { title: 'Way 2: Eliminate units that do not fit', steps: [
        'Liters measure liquid and meters measure length, so cross those out.',
        'A kilogram is about the weight of a big textbook, far too heavy.',
        'That leaves grams as the best choice.',
      ] },
    ] },
  { id: 'md-20', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'numeric',
    prompt: 'How many milliliters are in 2 liters?',
    answer: '2000', acceptable: ['2000', '2,000', '2000 mL'],
    hints: ['1 L = 1000 mL.', 'Bigger → smaller unit: multiply.'],
    explanation: '2 L × 1000 = 2000 mL.',
    solutions: [
      { title: 'Way 1: Multiply by 1000', steps: [
        'One liter equals 1000 milliliters.',
        'Liters are bigger, so multiply: 2 × 1000 = 2000.',
        'There are 2000 milliliters in 2 liters.',
      ] },
      { title: 'Way 2: Add liter by liter', steps: [
        'The first liter is 1000 mL.',
        'The second liter adds 1000 more: 1000 + 1000 = 2000.',
        'So 2 liters is 2000 milliliters.',
      ] },
    ] },
  { id: 'md-21', domain: '5.MD', standard: '5.MD.3', tier: 1, type: 'multiple-choice',
    prompt: 'Volume is measured in which kind of units?',
    choices: ['square units', 'cubic units', 'linear units', 'degrees'], answer: 'cubic units',
    hints: ['Volume fills up space in 3 dimensions.', 'Think of stacking little cubes inside a box.'],
    explanation: 'Volume counts unit cubes, so it is measured in cubic units.',
    solutions: [
      { title: 'Way 1: Think about what volume means', steps: [
        'Volume tells how much space a solid figure fills.',
        'We measure that space by packing it with unit cubes and counting them.',
        'So volume is measured in cubic units.',
      ] },
      { title: 'Way 2: Eliminate the other units', steps: [
        'Square units measure flat area, not space inside a solid.',
        'Linear units measure length, and degrees measure angles.',
        'The only unit left for volume is cubic units.',
      ] },
    ] },
  { id: 'md-22', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'numeric',
    prompt: 'How many feet are in 3 yards?',
    answer: '9', acceptable: ['9', '9 ft', '9 feet'],
    hints: ['1 yard = 3 feet.', '3 × 3.'],
    explanation: '3 yd × 3 ft/yd = 9 feet.',
    solutions: [
      { title: 'Way 1: Multiply by 3', steps: [
        'One yard equals 3 feet.',
        'Yards are bigger, so multiply: 3 × 3 = 9.',
        'There are 9 feet in 3 yards.',
      ] },
      { title: 'Way 2: Skip count by 3s', steps: [
        'Count 3 feet for each yard: 3, 6, 9.',
        'After 3 yards you reach 9.',
        'So 3 yards equals 9 feet.',
      ] },
    ] },
  { id: 'md-23', domain: '5.MD', standard: '5.MD.5', tier: 1, type: 'numeric',
    prompt: 'Find the volume of a box 2 units long, 2 units wide, and 4 units high.',
    diagram: { kind: 'prism', l: 2, w: 2, h: 4 },
    answer: '16', acceptable: ['16', '16 cubic units'],
    hints: ['V = l × w × h.', '2 × 2 × 4.'],
    explanation: 'V = 2 × 2 × 4 = 16 cubic units.',
    solutions: [
      { title: 'Way 1: Use V = l × w × h', steps: [
        'Multiply length and width: 2 × 2 = 4.',
        'Multiply by the height: 4 × 4 = 16.',
        'The volume is 16 cubic units.',
      ] },
      { title: 'Way 2: Stack the layers', steps: [
        'Each layer holds 2 × 2 = 4 cubes.',
        'The box is 4 layers tall, so count: 4, 8, 12, 16.',
        'The volume is 16 cubic units.',
      ] },
    ] },
  { id: 'md-24', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'multiple-choice',
    prompt: 'How many minutes are in 3 hours?',
    choices: ['30', '90', '180', '300'], answer: '180',
    hints: ['1 hour = 60 minutes.', '3 × 60.'],
    explanation: '3 × 60 = 180 minutes.',
    solutions: [
      { title: 'Way 1: Multiply by 60', steps: [
        'One hour equals 60 minutes.',
        'Multiply: 3 × 60 = 180.',
        'There are 180 minutes in 3 hours.',
      ] },
      { title: 'Way 2: Skip count by 60', steps: [
        'Count 60 minutes for each hour: 60, 120, 180.',
        'After 3 hours you reach 180.',
        'So 3 hours is 180 minutes.',
      ] },
    ] },
  { id: 'md-25', domain: '5.MD', standard: '5.MD.4', tier: 1, type: 'multiple-choice',
    prompt: 'A prism is built from unit cubes. The bottom layer has 4 rows of 3 cubes, and the prism is 2 layers tall. How many cubes were used?',
    diagram: { kind: 'prism', l: 4, w: 3, h: 2 },
    choices: ['12', '14', '24', '36'], answer: '24',
    hints: ['First find the cubes in one layer: 4 × 3.', 'Then multiply by 2 layers.'],
    explanation: 'One layer has 4 × 3 = 12 cubes; 2 layers make 24.',
    solutions: [
      { title: 'Way 1: Layer, then stack', steps: [
        'One layer has 4 rows of 3 cubes: 4 × 3 = 12 cubes.',
        'There are 2 layers: 12 × 2 = 24.',
        'The prism uses 24 cubes.',
      ] },
      { title: 'Way 2: Multiply all three numbers', steps: [
        'The prism is 4 long, 3 wide, and 2 tall.',
        'Multiply: 4 × 3 × 2 = 24.',
        'The prism uses 24 cubes.',
      ] },
    ] },
  { id: 'md-26', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'multiple-choice',
    prompt: 'Which measurement is the same as 5,000 meters?',
    choices: ['5 km', '50 km', '500 km', '1/2 km'], answer: '5 km',
    hints: ['1 km = 1000 m.', 'Smaller → bigger unit: divide by 1000.'],
    explanation: '5000 m ÷ 1000 = 5 km.',
    solutions: [
      { title: 'Way 1: Divide by 1000', steps: [
        'There are 1000 meters in every kilometer.',
        'Meters to kilometers means divide: 5000 ÷ 1000 = 5.',
        'So 5,000 meters is the same as 5 km.',
      ] },
      { title: 'Way 2: Build up by kilometers', steps: [
        'Count 1000 m for each kilometer: 1000, 2000, 3000, 4000, 5000.',
        'It takes 5 kilometers to reach 5,000 meters.',
        'So the answer is 5 km.',
      ] },
    ] },
  { id: 'md-27', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'numeric',
    prompt: 'A fruit punch recipe needs 3 pints of juice. How many CUPS of juice is that?',
    answer: '6', acceptable: ['6', '6 cups'],
    hints: ['1 pint = 2 cups.', '3 × 2.'],
    explanation: '3 pints × 2 cups/pint = 6 cups.',
    solutions: [
      { title: 'Way 1: Multiply by 2', steps: [
        'One pint equals 2 cups.',
        'Pints are bigger, so multiply: 3 × 2 = 6.',
        'The recipe needs 6 cups of juice.',
      ] },
      { title: 'Way 2: Use a ratio table', steps: [
        'Start with 1 pint = 2 cups.',
        'Keep adding 2 cups: 2 pints is 4 cups, 3 pints is 6 cups.',
        'So 3 pints equals 6 cups.',
      ] },
    ] },
  { id: 'md-28', domain: '5.MD', standard: '5.MD.5', tier: 2, type: 'multiple-choice',
    prompt: 'A prism is 6 units long, 3 units wide, and 4 units high. What is its volume?',
    diagram: { kind: 'prism', l: 6, w: 3, h: 4 },
    choices: ['13 cubic units', '36 cubic units', '72 cubic units', '144 cubic units'], answer: '72 cubic units',
    hints: ['V = l × w × h.', '6 × 3 = 18, then × 4.'],
    explanation: 'V = 6 × 3 × 4 = 72 cubic units.',
    solutions: [
      { title: 'Way 1: Base area times height', steps: [
        'The base is 6 × 3 = 18 square units.',
        'Multiply by the height: 18 × 4 = 72.',
        'The volume is 72 cubic units.',
      ] },
      { title: 'Way 2: Count cube layers', steps: [
        'Each layer holds 6 × 3 = 18 cubes.',
        'Stack 4 layers: 18, 36, 54, 72.',
        'The volume is 72 cubic units.',
      ] },
      { title: 'Way 3: Group the factors differently', steps: [
        'Multiply 3 × 4 = 12 first.',
        'Then 12 × 6 = 72.',
        'The volume is 72 cubic units.',
      ] },
    ] },
  { id: 'md-29', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'numeric',
    prompt: 'A board is 84 inches long. How many FEET is that?',
    answer: '7', acceptable: ['7', '7 ft', '7 feet'],
    hints: ['1 ft = 12 in.', 'Smaller → bigger unit: divide by 12.'],
    explanation: '84 ÷ 12 = 7 feet.',
    solutions: [
      { title: 'Way 1: Divide by 12', steps: [
        'Inches are smaller than feet, and 12 inches make 1 foot.',
        'Smaller to bigger means divide: 84 ÷ 12 = 7.',
        'The board is 7 feet long.',
      ] },
      { title: 'Way 2: Skip count by 12s', steps: [
        'Count a foot at a time: 12, 24, 36, 48, 60, 72, 84.',
        'It took 7 counts to reach 84.',
        'So 84 inches equals 7 feet.',
      ] },
    ] },
  { id: 'md-30', domain: '5.MD', standard: '5.MD.2', tier: 2, type: 'multiple-choice',
    prompt: 'A line plot shows ribbon lengths in yards: Xs at 1/4: 3, Xs at 1/2: 2, Xs at 3/4: 1. How many ribbons were measured in all?',
    choices: ['5', '6', '7', '8'], answer: '6',
    hints: ['Each X stands for one ribbon.', 'Count all the Xs: 3 + 2 + 1.'],
    explanation: 'Each X is one ribbon: 3 + 2 + 1 = 6 ribbons.',
    solutions: [
      { title: 'Way 1: Add the X counts', steps: [
        'Every X on a line plot stands for one ribbon.',
        'Add the Xs at each value: 3 + 2 + 1 = 6.',
        'There were 6 ribbons measured.',
      ] },
      { title: 'Way 2: Count the marks one by one', steps: [
        'Point to each X and count: 1, 2, 3 at one-fourth.',
        'Keep going: 4, 5 at one-half, then 6 at three-fourths.',
        'You counted 6 Xs, so 6 ribbons.',
      ] },
    ] },
  { id: 'md-31', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'multiple-choice',
    prompt: 'A bike trail is 4.2 kilometers long. How many METERS is that?',
    choices: ['42 m', '420 m', '4,200 m', '42,000 m'], answer: '4,200 m',
    hints: ['1 km = 1000 m.', 'Multiplying by 1000 moves the decimal 3 places.'],
    explanation: '4.2 km × 1000 = 4200 m.',
    solutions: [
      { title: 'Way 1: Multiply by 1000', steps: [
        'One kilometer equals 1000 meters.',
        'Multiply: 4.2 × 1000 moves the decimal three places right, giving 4200.',
        'The trail is 4,200 meters long.',
      ] },
      { title: 'Way 2: Break the distance apart', steps: [
        'Split 4.2 km into 4 km and 0.2 km.',
        '4 km is 4000 m, and 0.2 km is two tenths of 1000, which is 200 m.',
        'Add: 4000 + 200 = 4,200 meters.',
      ] },
    ] },
  { id: 'md-32', domain: '5.MD', standard: '5.MD.5', tier: 2, type: 'numeric',
    prompt: 'A storage bin is 7 inches long, 2 inches wide, and 3 inches high. What is its volume in cubic inches?',
    diagram: { kind: 'prism', l: 7, w: 2, h: 3 },
    answer: '42', acceptable: ['42', '42 cubic inches'],
    hints: ['V = l × w × h.', '7 × 2 = 14, then × 3.'],
    explanation: 'V = 7 × 2 × 3 = 42 cubic inches.',
    solutions: [
      { title: 'Way 1: Use V = l × w × h', steps: [
        'Multiply length and width: 7 × 2 = 14.',
        'Multiply by the height: 14 × 3 = 42.',
        'The volume is 42 cubic inches.',
      ] },
      { title: 'Way 2: Group the factors differently', steps: [
        'Multiply width and height first: 2 × 3 = 6.',
        'Then multiply by the length: 6 × 7 = 42.',
        'The volume is 42 cubic inches.',
      ] },
    ] },
  { id: 'md-33', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'multiple-choice',
    prompt: 'How many pints are in 2 gallons?',
    choices: ['4', '8', '16', '32'], answer: '16',
    hints: ['1 gal = 4 qt and 1 qt = 2 pt.', 'So 1 gallon = 8 pints.'],
    explanation: '2 gal = 8 qt = 16 pints.',
    solutions: [
      { title: 'Way 1: Step down through quarts', steps: [
        'First convert gallons to quarts: 2 × 4 = 8 quarts.',
        'Each quart is 2 pints: 8 × 2 = 16.',
        'There are 16 pints in 2 gallons.',
      ] },
      { title: 'Way 2: Use 1 gallon = 8 pints', steps: [
        'Since 1 gallon is 4 quarts and each quart is 2 pints, 1 gallon is 8 pints.',
        'Double it for 2 gallons: 8 × 2 = 16.',
        'There are 16 pints in 2 gallons.',
      ] },
    ] },
  { id: 'md-34', domain: '5.MD', standard: '5.MD.2', tier: 2, type: 'numeric',
    prompt: 'A line plot shows water in beakers: Xs at 1/8 L: 2, Xs at 1/4 L: 4. How many liters of water in all?',
    answer: '1.25', acceptable: ['1.25', '1 1/4', '5/4', '1.25 L'],
    hints: ['2 × 1/8 = 2/8 = 1/4.', '4 × 1/4 = 1. Add the parts.'],
    explanation: '2 × 1/8 = 1/4 and 4 × 1/4 = 1; total = 1 1/4 = 1.25 L.',
    solutions: [
      { title: 'Way 1: Multiply each value, then add', steps: [
        'Two beakers hold 1/8 L each: 2 × 1/8 = 2/8 = 1/4 L.',
        'Four beakers hold 1/4 L each: 4 × 1/4 = 1 L.',
        'Add: 1/4 + 1 = 1 1/4, so the total is 1.25 liters.',
      ] },
      { title: 'Way 2: Count everything in eighths', steps: [
        'The two 1/8 beakers give 2 eighths.',
        'Each 1/4 is 2 eighths, so four of them give 8 eighths.',
        'Total: 2 + 8 = 10 eighths, and 10/8 = 1 1/4 = 1.25 liters.',
      ] },
    ] },
  { id: 'md-35', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'multiple-choice',
    prompt: 'Marco ran 1,500 meters on Monday and 2 kilometers on Tuesday. How far did he run in all, in KILOMETERS?',
    choices: ['3.5 km', '35 km', '1,502 km', '3,500 km'], answer: '3.5 km',
    hints: ['Make the units match first.', '1500 m = 1.5 km, then add 2 km.'],
    explanation: '1500 m = 1.5 km; 1.5 + 2 = 3.5 km.',
    solutions: [
      { title: 'Way 1: Convert to kilometers, then add', steps: [
        'Change 1,500 m to kilometers: 1500 ÷ 1000 = 1.5 km.',
        'Add Tuesday: 1.5 + 2 = 3.5.',
        'Marco ran 3.5 km in all.',
      ] },
      { title: 'Way 2: Convert to meters, then back', steps: [
        'Change 2 km to meters: 2 × 1000 = 2000 m.',
        'Add the days: 1500 + 2000 = 3500 m.',
        'Convert back: 3500 ÷ 1000 = 3.5 km.',
      ] },
    ] },
  { id: 'md-36', domain: '5.MD', standard: '5.MD.4', tier: 2, type: 'numeric',
    prompt: 'A box is packed with centimeter cubes: 5 cubes long, 3 cubes wide, and 2 layers high. How many cubes fill the box?',
    diagram: { kind: 'prism', l: 5, w: 3, h: 2 },
    answer: '30', acceptable: ['30', '30 cubes'],
    hints: ['One layer has 5 × 3 cubes.', 'Then multiply by the 2 layers.'],
    explanation: 'One layer = 5 × 3 = 15 cubes; 2 layers = 30 cubes.',
    solutions: [
      { title: 'Way 1: Layer, then stack', steps: [
        'One layer holds 5 × 3 = 15 cubes.',
        'There are 2 layers: 15 + 15 = 30.',
        'The box holds 30 centimeter cubes.',
      ] },
      { title: 'Way 2: Multiply all three dimensions', steps: [
        'The cube counts are 5 long, 3 wide, and 2 high.',
        'Multiply: 5 × 3 × 2 = 30.',
        'The box holds 30 cubes.',
      ] },
    ] },
  { id: 'md-37', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'multiple-choice',
    prompt: 'How many ounces are in 2 1/2 pounds?',
    choices: ['32 oz', '36 oz', '40 oz', '42 oz'], answer: '40 oz',
    hints: ['1 lb = 16 oz.', '2 lb = 32 oz, and half a pound is 8 oz.'],
    explanation: '2 lb = 32 oz; 1/2 lb = 8 oz; 32 + 8 = 40 oz.',
    solutions: [
      { title: 'Way 1: Whole pounds plus a half pound', steps: [
        'Two pounds is 2 × 16 = 32 ounces.',
        'Half a pound is 16 ÷ 2 = 8 ounces.',
        'Add: 32 + 8 = 40 ounces.',
      ] },
      { title: 'Way 2: Multiply by the fraction', steps: [
        'Write 2 1/2 as 5/2.',
        'Multiply: 5/2 × 16 = 80 ÷ 2 = 40.',
        'So 2 1/2 pounds is 40 ounces.',
      ] },
    ] },
  { id: 'md-38', domain: '5.MD', standard: '5.MD.5', tier: 2, type: 'multiple-choice',
    prompt: 'Which expression gives the volume of a prism that is 9 units long, 2 units wide, and 5 units high?',
    diagram: { kind: 'prism', l: 9, w: 2, h: 5 },
    choices: ['9 + 2 + 5', '9 × 2 + 5', '9 × 2 × 5', '2 × (9 + 5)'], answer: '9 × 2 × 5',
    hints: ['Volume multiplies ALL three dimensions.', 'V = l × w × h.'],
    explanation: 'Volume is length × width × height: 9 × 2 × 5.',
    solutions: [
      { title: 'Way 1: Use the volume formula', steps: [
        'Volume of a rectangular prism is length × width × height.',
        'Plug in the dimensions: 9 × 2 × 5.',
        'So the expression 9 × 2 × 5 gives the volume.',
      ] },
      { title: 'Way 2: Think in cube layers', steps: [
        'The bottom layer has 9 × 2 unit cubes.',
        'There are 5 layers, so you multiply that layer by 5.',
        'That is 9 × 2 × 5, the correct expression.',
      ] },
    ] },
  { id: 'md-39', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'multiple-choice',
    prompt: 'A table is 3 1/2 feet wide. How many INCHES is that?',
    choices: ['36 in', '40 in', '42 in', '46 in'], answer: '42 in',
    hints: ['1 ft = 12 in.', '3 ft = 36 in, and half a foot is 6 in.'],
    explanation: '3 ft = 36 in; 1/2 ft = 6 in; 36 + 6 = 42 in.',
    solutions: [
      { title: 'Way 1: Whole feet plus a half foot', steps: [
        'Three feet is 3 × 12 = 36 inches.',
        'Half a foot is 12 ÷ 2 = 6 inches.',
        'Add: 36 + 6 = 42 inches.',
      ] },
      { title: 'Way 2: Multiply by the fraction', steps: [
        'Write 3 1/2 as 7/2.',
        'Multiply: 7/2 × 12 = 84 ÷ 2 = 42.',
        'The table is 42 inches wide.',
      ] },
    ] },
  { id: 'md-40', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'constructed',
    prompt: 'Explain how to convert 5 meters into centimeters, then give the answer.',
    answer: 'multiply', acceptable: ['500', '500 cm', '100', 'times 100', 'multiply by 100'],
    hints: ['1 m = 100 cm.', 'Bigger unit to smaller unit means multiply.'],
    explanation: 'Meters are bigger than centimeters, so multiply: 5 × 100 = 500 cm.',
    solutions: [
      { title: 'Way 1: Use the multiply rule', steps: [
        'One meter equals 100 centimeters.',
        'Going from a bigger unit to a smaller unit means multiply.',
        'Multiply 5 × 100 = 500, so 5 meters is 500 centimeters.',
      ] },
      { title: 'Way 2: Build a ratio table', steps: [
        'Start with 1 m = 100 cm.',
        'Add 100 cm for each meter: 200, 300, 400, 500.',
        'After 5 meters the table shows 500 centimeters.',
      ] },
    ] },
  { id: 'md-41', domain: '5.MD', standard: '5.MD.2', tier: 2, type: 'multiple-choice',
    prompt: 'A line plot shows pencil lengths in inches: Xs at 4 1/2: 2, Xs at 5: 3, Xs at 5 1/2: 1. Which length is MOST common?',
    choices: ['4 1/2 in', '5 in', '5 1/2 in', '6 in'], answer: '5 in',
    hints: ['Most common means the most Xs.', 'Compare the counts 2, 3, and 1.'],
    explanation: 'The value 5 in has 3 Xs, more than any other stack.',
    solutions: [
      { title: 'Way 1: Compare the X counts', steps: [
        'List the counts: 2 Xs at 4 1/2, 3 Xs at 5, and 1 X at 5 1/2.',
        'The biggest count is 3, which sits at 5 inches.',
        'So 5 in is the most common length.',
      ] },
      { title: 'Way 2: Find the tallest stack', steps: [
        'On a line plot, the most common value has the tallest tower of Xs.',
        'The tower at 5 inches is 3 Xs tall, taller than the others.',
        'So the most common pencil length is 5 in.',
      ] },
    ] },
  { id: 'md-42', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'numeric',
    prompt: 'A movie lasts 2 hours 25 minutes. How many MINUTES is that in all?',
    answer: '145', acceptable: ['145', '145 min', '145 minutes'],
    hints: ['1 hour = 60 minutes.', '2 × 60 = 120, then add 25.'],
    explanation: '2 h = 120 min; 120 + 25 = 145 minutes.',
    solutions: [
      { title: 'Way 1: Convert the hours, then add', steps: [
        'Two hours is 2 × 60 = 120 minutes.',
        'Add the extra minutes: 120 + 25 = 145.',
        'The movie lasts 145 minutes.',
      ] },
      { title: 'Way 2: Skip count, then add on', steps: [
        'Count an hour at a time: 60, 120.',
        'From 120, add 25 more minutes to get 145.',
        'The movie is 145 minutes long.',
      ] },
    ] },
  { id: 'md-43', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'multiple-choice',
    prompt: 'An L-shaped solid is a 5 × 4 × 3 box joined to a 2 × 4 × 3 box. What is the total volume?',
    choices: ['24 cubic units', '60 cubic units', '84 cubic units', '104 cubic units'], answer: '84 cubic units',
    hints: ['Find each box volume separately.', '5 × 4 × 3 = 60 and 2 × 4 × 3 = 24; add them.'],
    explanation: '60 + 24 = 84 cubic units.',
    solutions: [
      { title: 'Way 1: Add the two boxes', steps: [
        'The big box has volume 5 × 4 × 3 = 60 cubic units.',
        'The small box has volume 2 × 4 × 3 = 24 cubic units.',
        'Add them: 60 + 24 = 84 cubic units.',
      ] },
      { title: 'Way 2: Combine the lengths first', steps: [
        'Both boxes are 4 wide and 3 high, so line up their lengths: 5 and 2.',
        'Together they act like one box 7 long, 4 wide, and 3 high.',
        'Multiply: 7 × 4 × 3 = 84 cubic units.',
      ] },
    ] },
  { id: 'md-44', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'numeric',
    prompt: 'A bottle holds 1.5 liters of juice. Ana pours out two glasses of 350 mL each. How many MILLILITERS are left?',
    answer: '800', acceptable: ['800', '800 mL', '800 ml'],
    hints: ['1.5 L = 1500 mL.', 'Two glasses use 350 + 350 = 700 mL.'],
    explanation: '1500 − 700 = 800 mL left.',
    solutions: [
      { title: 'Way 1: Convert first, then subtract', steps: [
        'Change 1.5 L to milliliters: 1.5 × 1000 = 1500 mL.',
        'Two glasses use 2 × 350 = 700 mL.',
        'Subtract: 1500 − 700 = 800 mL left.',
      ] },
      { title: 'Way 2: Pour one glass at a time', steps: [
        'Start with 1500 mL, since 1.5 L = 1500 mL.',
        'After the first glass: 1500 − 350 = 1150 mL.',
        'After the second glass: 1150 − 350 = 800 mL left.',
      ] },
    ] },
  { id: 'md-45', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'numeric',
    prompt: 'A box has volume 120 cm³. Its length is 6 cm and its height is 4 cm. What is its WIDTH in cm?',
    answer: '5', acceptable: ['5', '5 cm'],
    hints: ['Multiply the known dimensions: 6 × 4 = 24.', 'Width = 120 ÷ 24.'],
    explanation: '6 × 4 = 24, and 120 ÷ 24 = 5, so the width is 5 cm.',
    solutions: [
      { title: 'Way 1: Divide by the known product', steps: [
        'Multiply the dimensions you know: 6 × 4 = 24.',
        'The missing width is the volume divided by that: 120 ÷ 24 = 5.',
        'The width is 5 cm.',
      ] },
      { title: 'Way 2: Find the missing factor', steps: [
        'Write the equation 6 × w × 4 = 120, which is 24 × w = 120.',
        'Think: 24 times what is 120? Since 24 × 5 = 120, w = 5.',
        'The width is 5 cm.',
      ] },
    ] },
  { id: 'md-46', domain: '5.MD', standard: '5.MD.2', tier: 3, type: 'multiple-choice',
    prompt: 'A line plot shows bags of flour in pounds: Xs at 1/4: 2, Xs at 1/2: 3, Xs at 1: 1. How many pounds of flour in all?',
    choices: ['2 lb', '2 1/2 lb', '3 lb', '3 1/2 lb'], answer: '3 lb',
    hints: ['Multiply each value by its number of Xs.', '2 × 1/4 = 1/2, 3 × 1/2 = 1 1/2, 1 × 1 = 1; add.'],
    explanation: '1/2 + 1 1/2 + 1 = 3 pounds.',
    solutions: [
      { title: 'Way 1: Multiply each value, then add', steps: [
        'Two bags at 1/4 lb: 2 × 1/4 = 1/2 lb.',
        'Three bags at 1/2 lb: 3 × 1/2 = 1 1/2 lb, and one bag is 1 lb.',
        'Add: 1/2 + 1 1/2 + 1 = 3 pounds in all.',
      ] },
      { title: 'Way 2: Count everything in fourths', steps: [
        'The 1/4 bags give 2 fourths.',
        'Each 1/2 is 2 fourths, so three give 6 fourths, and the 1 lb bag is 4 fourths.',
        'Total: 2 + 6 + 4 = 12 fourths, and 12/4 = 3 pounds.',
      ] },
    ] },
  { id: 'md-47', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'multiple-choice',
    prompt: 'Each fence board is 30 inches long. If 6 boards are laid end to end, how many FEET long is the row?',
    choices: ['15 ft', '18 ft', '30 ft', '180 ft'], answer: '15 ft',
    hints: ['First find the total inches: 6 × 30.', 'Then divide by 12 to get feet.'],
    explanation: '6 × 30 = 180 in, and 180 ÷ 12 = 15 feet.',
    solutions: [
      { title: 'Way 1: Multiply, then convert', steps: [
        'Six boards make 6 × 30 = 180 inches.',
        'Divide by 12 to change inches to feet: 180 ÷ 12 = 15.',
        'The row is 15 feet long.',
      ] },
      { title: 'Way 2: Convert one board, then multiply', steps: [
        'One board is 30 ÷ 12 = 2 1/2 feet.',
        'Six boards make 6 × 2 1/2 = 12 + 3 = 15.',
        'The row is 15 feet long.',
      ] },
    ] },
  { id: 'md-48', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'multiple-choice',
    prompt: 'A shipping crate is 10 ft long, 4 ft wide, and 6 ft high. What is its volume?',
    diagram: { kind: 'prism', l: 10, w: 4, h: 6 },
    choices: ['60 cubic feet', '120 cubic feet', '240 cubic feet', '480 cubic feet'], answer: '240 cubic feet',
    hints: ['V = l × w × h.', '10 × 4 = 40, then × 6.'],
    explanation: 'V = 10 × 4 × 6 = 240 cubic feet.',
    solutions: [
      { title: 'Way 1: Base area times height', steps: [
        'The floor of the crate is 10 × 4 = 40 square feet.',
        'Multiply by the height: 40 × 6 = 240.',
        'The volume is 240 cubic feet.',
      ] },
      { title: 'Way 2: Group the factors differently', steps: [
        'Multiply 4 × 6 = 24 first.',
        'Then 24 × 10 = 240.',
        'The volume is 240 cubic feet.',
      ] },
    ] },
  { id: 'md-49', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'numeric',
    prompt: 'A soup recipe needs 2 quarts of broth. Mia has only 5 cups. How many MORE cups does she need?',
    answer: '3', acceptable: ['3', '3 cups'],
    hints: ['1 quart = 4 cups, so 2 quarts = 8 cups.', '8 − 5.'],
    explanation: '2 qt = 8 cups; 8 − 5 = 3 more cups.',
    solutions: [
      { title: 'Way 1: Use 1 quart = 4 cups', steps: [
        'One quart equals 4 cups, so 2 quarts is 2 × 4 = 8 cups.',
        'Mia already has 5 cups, so subtract: 8 − 5 = 3.',
        'She needs 3 more cups.',
      ] },
      { title: 'Way 2: Step down through pints', steps: [
        'Each quart is 2 pints, so 2 quarts is 4 pints.',
        'Each pint is 2 cups, so 4 pints is 8 cups.',
        'She has 5 cups, and 8 − 5 = 3, so she needs 3 more cups.',
      ] },
    ] },
  { id: 'md-50', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'multiple-choice',
    prompt: 'A cube-shaped planter has edges 5 inches long. What is its volume?',
    diagram: { kind: 'prism', l: 5, w: 5, h: 5 },
    choices: ['15 cubic inches', '25 cubic inches', '125 cubic inches', '150 cubic inches'], answer: '125 cubic inches',
    hints: ['A cube has equal edges: V = 5 × 5 × 5.', '25 × 5.'],
    explanation: 'V = 5 × 5 × 5 = 125 cubic inches.',
    solutions: [
      { title: 'Way 1: Multiply the three edges', steps: [
        'Every edge of a cube is the same, so V = 5 × 5 × 5.',
        'Work it out: 5 × 5 = 25, then 25 × 5 = 125.',
        'The volume is 125 cubic inches.',
      ] },
      { title: 'Way 2: Count cube layers', steps: [
        'The bottom layer holds 5 × 5 = 25 inch cubes.',
        'There are 5 layers: 25, 50, 75, 100, 125.',
        'The volume is 125 cubic inches.',
      ] },
    ] },
  { id: 'md-51', domain: '5.MD', standard: '5.MD.2', tier: 3, type: 'numeric',
    prompt: 'Four beakers hold 1/2 L, 1/2 L, 3/4 L, and 1/4 L. If the water is shared EQUALLY among the 4 beakers, how many liters go in each?',
    answer: '0.5', acceptable: ['0.5', '1/2', '0.5 L', '1/2 L'],
    hints: ['First find the total amount of water.', 'Total 2 L shared by 4 beakers: 2 ÷ 4.'],
    explanation: 'Total = 2 L; 2 ÷ 4 = 1/2 L in each beaker.',
    solutions: [
      { title: 'Way 1: Total, then divide', steps: [
        'Add all the water: 1/2 + 1/2 + 3/4 + 1/4 = 1 + 1 = 2 liters.',
        'Share among 4 beakers: 2 ÷ 4 = 1/2.',
        'Each beaker gets 1/2 liter, which is 0.5 L.',
      ] },
      { title: 'Way 2: Pour to even things out', steps: [
        'Two beakers already hold 1/2 L each.',
        'Pour 1/4 L from the 3/4 beaker into the 1/4 beaker.',
        'Now all four beakers hold 1/2 L, so the fair share is 0.5 L.',
      ] },
    ] },
  { id: 'md-52', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'constructed',
    prompt: 'Jay says 36 ounces equals 3 pounds because he divided by 12. Explain his mistake and give the correct number of pounds.',
    answer: '16', acceptable: ['2 1/4', '2.25', '2 lb 4 oz', 'divide by 16', '16 ounces'],
    hints: ['How many ounces are in 1 pound?', '1 lb = 16 oz, so divide 36 by 16.'],
    explanation: 'Jay used the feet fact; 1 lb = 16 oz, so 36 ÷ 16 = 2 1/4 pounds.',
    solutions: [
      { title: 'Way 1: Fix the conversion fact', steps: [
        'Jay divided by 12, but 12 is for inches in a foot, not ounces in a pound.',
        'The correct fact is 1 pound = 16 ounces.',
        'Divide: 36 ÷ 16 = 2 remainder 4, so 36 oz is 2 lb 4 oz, or 2 1/4 pounds.',
      ] },
      { title: 'Way 2: Build up by 16s', steps: [
        'Count whole pounds: 16 oz is 1 lb, and 32 oz is 2 lb.',
        'From 32 to 36 there are 4 ounces left over.',
        'Since 4 oz is 4/16 = 1/4 lb, the correct answer is 2 1/4 pounds.',
      ] },
    ] },
  { id: 'md-53', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'constructed',
    prompt: 'Box A is 4 × 4 × 4. Box B is 8 × 2 × 4. Kim says Box A holds more because it is a cube. Is she right? Explain.',
    answer: 'same', acceptable: ['equal', '64', 'both', 'no', 'same volume'],
    hints: ['Find each volume with V = l × w × h.', 'Compare 4 × 4 × 4 with 8 × 2 × 4.'],
    explanation: 'Both volumes are 64 cubic units, so Kim is wrong — the boxes hold the same amount.',
    solutions: [
      { title: 'Way 1: Compute both volumes', steps: [
        'Box A: 4 × 4 × 4 = 64 cubic units.',
        'Box B: 8 × 2 × 4 = 64 cubic units.',
        'The volumes are equal, so Kim is wrong — the boxes hold the same amount.',
      ] },
      { title: 'Way 2: Compare the bases', steps: [
        'Box A has a 4 × 4 base, an area of 16; Box B has an 8 × 2 base, also 16.',
        'Both boxes are 4 units tall, so each is 16 × 4 = 64.',
        'Same base area and same height means the same volume, so Kim is not right.',
      ] },
    ] },
  { id: 'md-54', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'numeric',
    prompt: 'A train leaves at 9:40 a.m. and arrives at 11:15 a.m. How many MINUTES does the trip take?',
    answer: '95', acceptable: ['95', '95 min', '95 minutes'],
    hints: ['Count up: 9:40 to 10:00, then to 11:00, then to 11:15.', '20 + 60 + 15.'],
    explanation: '20 + 60 + 15 = 95 minutes.',
    solutions: [
      { title: 'Way 1: Count up in friendly chunks', steps: [
        'From 9:40 to 10:00 is 20 minutes.',
        'From 10:00 to 11:00 is 60 minutes, and 11:00 to 11:15 is 15 more.',
        'Add the chunks: 20 + 60 + 15 = 95 minutes.',
      ] },
      { title: 'Way 2: Use 2 hours and back up', steps: [
        'From 9:40 to 11:40 would be exactly 2 hours, or 120 minutes.',
        'The train arrives at 11:15, which is 25 minutes before 11:40.',
        'Subtract: 120 − 25 = 95 minutes.',
      ] },
    ] },
  { id: 'md-55', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'multiple-choice',
    prompt: 'A staircase-shaped solid is a 6 × 2 × 2 box with a 3 × 2 × 2 box stacked on top. What is the total volume?',
    choices: ['12 cubic units', '24 cubic units', '36 cubic units', '48 cubic units'], answer: '36 cubic units',
    hints: ['Find each box: 6 × 2 × 2 and 3 × 2 × 2.', '24 + 12.'],
    explanation: '24 + 12 = 36 cubic units.',
    solutions: [
      { title: 'Way 1: Add the two boxes', steps: [
        'The bottom box is 6 × 2 × 2 = 24 cubic units.',
        'The top box is 3 × 2 × 2 = 12 cubic units.',
        'Add: 24 + 12 = 36 cubic units.',
      ] },
      { title: 'Way 2: Big box minus the missing notch', steps: [
        'Imagine a full box 6 long, 2 wide, and 4 tall: 6 × 2 × 4 = 48.',
        'The missing top corner is 3 × 2 × 2 = 12.',
        'Subtract: 48 − 12 = 36 cubic units.',
      ] },
    ] },
  { id: 'md-56', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'multiple-choice',
    prompt: 'A trail is 3.2 km long. Liam hikes 1.5 km, rests, then hikes 900 m more. How many METERS of trail are left?',
    choices: ['8 m', '80 m', '800 m', '1,700 m'], answer: '800 m',
    hints: ['Convert everything to meters: 3.2 km = 3200 m, 1.5 km = 1500 m.', '3200 − 1500 − 900.'],
    explanation: '3200 − 1500 − 900 = 800 meters left.',
    solutions: [
      { title: 'Way 1: Convert all, then subtract twice', steps: [
        'Change to meters: 3.2 km = 3200 m and 1.5 km = 1500 m.',
        'Subtract the first hike: 3200 − 1500 = 1700 m.',
        'Subtract the second hike: 1700 − 900 = 800 m left.',
      ] },
      { title: 'Way 2: Add the hiking first', steps: [
        'Liam hiked 1500 m and then 900 m: 1500 + 900 = 2400 m.',
        'The whole trail is 3200 m.',
        'Subtract: 3200 − 2400 = 800 m left.',
      ] },
    ] },
  { id: 'md-57', domain: '5.MD', standard: '5.MD.1', tier: 4, type: 'numeric',
    prompt: 'A stand makes 3 gallons of lemonade and sells it in 1-pint cups for $2 each. How many DOLLARS does the stand earn if every cup sells?',
    answer: '48', acceptable: ['48', '$48', '48 dollars'],
    hints: ['1 gallon = 4 quarts and 1 quart = 2 pints.', '3 gal = 24 pints, each selling for $2.'],
    explanation: '3 gal = 24 pints; 24 × $2 = $48.',
    solutions: [
      { title: 'Way 1: Step down through quarts', steps: [
        'Convert gallons to quarts: 3 × 4 = 12 quarts.',
        'Convert quarts to pints: 12 × 2 = 24 pints, so 24 cups.',
        'Each cup earns $2, so 24 × 2 = 48 dollars.',
      ] },
      { title: 'Way 2: Use 1 gallon = 8 pints', steps: [
        'One gallon holds 8 pints, so 3 gallons hold 3 × 8 = 24 pints.',
        'That makes 24 one-pint cups.',
        'Multiply by the price: 24 × $2 = $48.',
      ] },
    ] },
  { id: 'md-58', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'numeric',
    prompt: 'A solid starts as an 8 × 5 × 4 box, then a 3 × 2 × 4 notch is cut from one corner. What is the remaining volume in cubic units?',
    answer: '136', acceptable: ['136', '136 cubic units'],
    hints: ['Big box volume: 8 × 5 × 4.', 'Subtract the notch: 3 × 2 × 4.'],
    explanation: '160 − 24 = 136 cubic units remain.',
    solutions: [
      { title: 'Way 1: Big box minus the notch', steps: [
        'The full box has volume 8 × 5 × 4 = 160 cubic units.',
        'The notch removes 3 × 2 × 4 = 24 cubic units.',
        'Subtract: 160 − 24 = 136 cubic units remain.',
      ] },
      { title: 'Way 2: Base area times height', steps: [
        'The notch runs the full 4-unit height, so look at the base.',
        'The base area left is 8 × 5 − 3 × 2 = 40 − 6 = 34 square units.',
        'Multiply by the height: 34 × 4 = 136 cubic units.',
      ] },
    ] },
  { id: 'md-59', domain: '5.MD', standard: '5.MD.1', tier: 4, type: 'multiple-choice',
    prompt: 'Which package is the HEAVIEST?',
    choices: ['2 lb', '30 oz', '1 lb 15 oz', '28 oz'], answer: '2 lb',
    hints: ['Convert every choice to ounces.', '1 lb = 16 oz, so 2 lb = 32 oz.'],
    explanation: 'In ounces the choices are 32, 30, 31, and 28, so 2 lb is heaviest.',
    solutions: [
      { title: 'Way 1: Convert everything to ounces', steps: [
        'Change each choice: 2 lb = 32 oz, and 1 lb 15 oz = 16 + 15 = 31 oz.',
        'Now compare 32, 30, 31, and 28 ounces.',
        'The largest is 32 oz, so 2 lb is the heaviest package.',
      ] },
      { title: 'Way 2: Compare each choice to 2 pounds', steps: [
        'Two pounds equals 32 ounces, so check if anything beats 32.',
        '30 oz is less, 28 oz is less, and 1 lb 15 oz is 31 oz — just 1 oz short.',
        'Nothing beats 32 oz, so 2 lb is the heaviest.',
      ] },
    ] },
  { id: 'md-60', domain: '5.MD', standard: '5.MD.2', tier: 4, type: 'numeric',
    prompt: 'A line plot shows cups of sugar used in recipes: Xs at 1/4: 2, Xs at 1/2: 3, Xs at 3/4: 2, Xs at 1: 1. How many cups in all?',
    answer: '4.5', acceptable: ['4.5', '4 1/2', '9/2', '4.5 cups'],
    hints: ['Multiply each value by its count, then add.', '1/2 + 1 1/2 + 1 1/2 + 1.'],
    explanation: '1/2 + 1 1/2 + 1 1/2 + 1 = 4 1/2 = 4.5 cups.',
    solutions: [
      { title: 'Way 1: Multiply each value, then add', steps: [
        'At 1/4: 2 × 1/4 = 1/2 cup. At 1/2: 3 × 1/2 = 1 1/2 cups.',
        'At 3/4: 2 × 3/4 = 1 1/2 cups. At 1: 1 × 1 = 1 cup.',
        'Add: 1/2 + 1 1/2 + 1 1/2 + 1 = 4 1/2, so 4.5 cups in all.',
      ] },
      { title: 'Way 2: Count everything in fourths', steps: [
        'Two 1/4s give 2 fourths, and three 1/2s give 6 fourths.',
        'Two 3/4s give 6 fourths, and one whole cup gives 4 fourths.',
        'Total: 2 + 6 + 6 + 4 = 18 fourths, and 18/4 = 4 1/2 = 4.5 cups.',
      ] },
    ] },
  { id: 'md-61', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'multiple-choice',
    prompt: 'A prism has volume 210 m³. Its length is 7 m and its height is 5 m. What is its WIDTH?',
    choices: ['5 m', '6 m', '7 m', '8 m'], answer: '6 m',
    hints: ['Multiply the known dimensions: 7 × 5 = 35.', 'Width = 210 ÷ 35.'],
    explanation: '210 ÷ (7 × 5) = 210 ÷ 35 = 6 m.',
    solutions: [
      { title: 'Way 1: Divide by the known product', steps: [
        'Multiply the known dimensions: 7 × 5 = 35.',
        'Divide the volume by that: 210 ÷ 35 = 6.',
        'The width is 6 m.',
      ] },
      { title: 'Way 2: Test the choices', steps: [
        'Try width 6: 7 × 6 × 5 = 42 × 5 = 210, which matches the volume.',
        'Check another, like 5: 7 × 5 × 5 = 175, too small.',
        'So the width must be 6 m.',
      ] },
    ] },
  { id: 'md-62', domain: '5.MD', standard: '5.MD.1', tier: 4, type: 'numeric',
    prompt: 'Each loaf of bread needs 450 grams of flour. A baker makes 5 loaves from a 2.5 kg bag. How many GRAMS of flour are left?',
    answer: '250', acceptable: ['250', '250 g', '250 grams'],
    hints: ['2.5 kg = 2500 g.', 'Flour used: 5 × 450 = 2250 g.'],
    explanation: '2500 − 2250 = 250 grams left.',
    solutions: [
      { title: 'Way 1: Convert the bag first', steps: [
        'Change 2.5 kg to grams: 2.5 × 1000 = 2500 g.',
        'Find the flour used: 5 × 450 = 2250 g.',
        'Subtract: 2500 − 2250 = 250 grams left.',
      ] },
      { title: 'Way 2: Work in kilograms, convert at the end', steps: [
        'Five loaves use 5 × 450 = 2250 g, which is 2.25 kg.',
        'Subtract from the bag: 2.5 − 2.25 = 0.25 kg.',
        'Convert back: 0.25 kg = 250 grams left.',
      ] },
    ] },
  { id: 'md-63', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'constructed',
    prompt: 'An L-shaped solid is made from a 5 × 2 × 2 box and a 3 × 2 × 2 box. Explain how to find its total volume, then give it.',
    answer: 'add', acceptable: ['32', 'split', 'two boxes', 'break apart', 'decompose'],
    hints: ['Split the L into its two boxes.', 'Find each volume and add: 20 + 12.'],
    explanation: 'Split the solid into the two boxes: 5×2×2 = 20 and 3×2×2 = 12, so 20 + 12 = 32 cubic units.',
    solutions: [
      { title: 'Way 1: Split into two boxes and add', steps: [
        'Break the L-shape into its two rectangular boxes.',
        'The first box is 5 × 2 × 2 = 20, and the second is 3 × 2 × 2 = 12.',
        'Add the parts: 20 + 12 = 32 cubic units.',
      ] },
      { title: 'Way 2: Big box minus the missing piece', steps: [
        'Picture the 3 × 2 × 2 box stacked on the 5 × 2 × 2 box: a full box would be 5 × 2 × 4 = 40.',
        'The missing corner piece is 2 long, 2 wide, and 2 tall: 2 × 2 × 2 = 8.',
        'Subtract: 40 − 8 = 32 cubic units.',
      ] },
    ] },
  { id: 'md-64', domain: '5.MD', standard: '5.MD.1', tier: 4, type: 'multiple-choice',
    prompt: 'Soccer practice lasts 75 minutes and starts at 3:50 p.m. What time does it end?',
    choices: ['4:25 p.m.', '4:55 p.m.', '5:05 p.m.', '5:15 p.m.'], answer: '5:05 p.m.',
    hints: ['75 minutes = 1 hour 15 minutes.', 'Jump to 4:00 first, then add the rest.'],
    explanation: '3:50 + 1 h 15 min = 5:05 p.m.',
    solutions: [
      { title: 'Way 1: Jump to the next hour first', steps: [
        'From 3:50 to 4:00 uses 10 minutes, leaving 75 − 10 = 65 minutes.',
        'From 4:00, add 60 minutes to reach 5:00, leaving 5 minutes.',
        'Add the last 5 minutes: practice ends at 5:05 p.m.',
      ] },
      { title: 'Way 2: Add 1 hour, then 15 minutes', steps: [
        'Rewrite 75 minutes as 1 hour 15 minutes.',
        'Add 1 hour to 3:50 to get 4:50.',
        'Add 15 more minutes: 4:50 + 15 = 5:05 p.m.',
      ] },
    ] },
  { id: 'md-65', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'numeric',
    prompt: 'A toy chest is 2 feet long, 18 inches wide, and 1 foot high. What is its volume in CUBIC INCHES?',
    diagram: { kind: 'prism', l: 24, w: 18, h: 12 },
    answer: '5184', acceptable: ['5184', '5,184', '5184 cubic inches'],
    hints: ['Convert to inches first: 2 ft = 24 in, 1 ft = 12 in.', 'Then multiply 24 × 18 × 12.'],
    explanation: '24 × 18 × 12 = 5184 cubic inches.',
    solutions: [
      { title: 'Way 1: Convert everything to inches first', steps: [
        'Change the units: 2 ft = 24 in and 1 ft = 12 in, so the chest is 24 × 18 × 12.',
        'Multiply the base: 24 × 18 = 432 square inches.',
        'Multiply by the height: 432 × 12 = 5184 cubic inches.',
      ] },
      { title: 'Way 2: Group the factors a friendlier way', steps: [
        'After converting, the dimensions are 24, 18, and 12 inches.',
        'Multiply 18 × 12 = 216 first.',
        'Then 216 × 24 = 5184, so the volume is 5184 cubic inches.',
      ] },
    ] },
  { id: 'md-66', domain: '5.MD', standard: '5.MD.2', tier: 4, type: 'constructed',
    prompt: 'A line plot shows juice in 3 bottles: one X at 1/4 L, one X at 1/2 L, one X at 3/4 L. Explain how to share the juice equally among the 3 bottles, then give each amount.',
    answer: '1/2', acceptable: ['0.5', 'add', 'divide', 'divide by 3', 'equal shares'],
    hints: ['First add all three amounts.', 'Total 1 1/2 L shared by 3: divide by 3.'],
    explanation: 'Total = 1/4 + 1/2 + 3/4 = 1 1/2 L; 1 1/2 ÷ 3 = 1/2 L in each bottle.',
    solutions: [
      { title: 'Way 1: Total, then divide by 3', steps: [
        'Add all the juice: 1/4 + 1/2 + 3/4 = 1/4 + 2/4 + 3/4 = 6/4 = 1 1/2 liters.',
        'Share equally among 3 bottles: 1 1/2 ÷ 3 = 1/2.',
        'Each bottle gets 1/2 liter.',
      ] },
      { title: 'Way 2: Pour from the fullest to the emptiest', steps: [
        'The middle bottle already has 1/2 L, the fair-share amount.',
        'Pour 1/4 L from the 3/4 bottle into the 1/4 bottle.',
        'Now every bottle holds 1/2 liter, so the equal share is 1/2 L.',
      ] },
    ] },
];
