import type { Problem, Lesson } from '../types';

// ===========================================================================
// 5.MD — Measurement & Data (unit conversion, line plots, volume)
// ===========================================================================

export const lessons: Lesson[] = [
  {
    domain: '5.MD', standard: '5.MD.1',
    title: 'Convert Measurement Units',
    steps: [
      'Know the key facts: 1 ft = 12 in, 1 m = 100 cm, 1 km = 1000 m, 1 lb = 16 oz, 1 gal = 4 qt.',
      'Bigger unit → smaller unit: MULTIPLY.',
      'Smaller unit → bigger unit: DIVIDE.',
    ],
    example: '3 ft = 3 × 12 = 36 in.',
    tip: 'Write the units beside the numbers so you can check they cancel correctly.',
  },
  {
    domain: '5.MD', standard: '5.MD.5',
    title: 'Volume of Rectangular Prisms',
    steps: [
      'Volume = length × width × height (V = l × w × h).',
      'You can also do V = base area × height.',
      'For an irregular solid, split it into boxes and add the volumes.',
      'Volume is measured in CUBIC units (cm³, in³).',
    ],
    example: 'A box 4 × 3 × 2 has V = 4 × 3 × 2 = 24 cubic units.',
    tip: 'Count layers: base layer of l×w cubes, stacked h high.',
  },
  {
    domain: '5.MD', standard: '5.MD.2',
    title: 'Line Plots with Fractions',
    steps: [
      'Each X on the line plot is one data point at that value.',
      'To find a total, multiply each value by how many Xs, then add.',
      'You can redistribute amounts evenly to find a fair share.',
    ],
    example: 'Three plants at 1/4 cup → 3 × 1/4 = 3/4 cup total.',
    tip: 'Line plots often ask for the difference between the tallest and shortest stacks.',
  },
];

export const problems: Problem[] = [
  { id: 'md-1', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'numeric',
    prompt: 'How many inches are in 2 feet?', answer: '24', acceptable: ['24', '24 in'],
    hints: ['1 foot = 12 inches.', '2 × 12.'],
    explanation: '2 ft × 12 in/ft = 24 inches.' },
  { id: 'md-2', domain: '5.MD', standard: '5.MD.5', tier: 1, type: 'numeric',
    prompt: 'Find the volume of a box 5 long, 2 wide, 3 high.',
    diagram: { kind: 'prism', l: 5, w: 2, h: 3 },
    answer: '30', acceptable: ['30', '30 cubic units'],
    hints: ['V = l × w × h.', '5 × 2 × 3.'],
    explanation: 'V = 5 × 2 × 3 = 30 cubic units.' },
  { id: 'md-3', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'numeric',
    prompt: 'A rope is 250 cm long. How many meters is that?', answer: '2.5', acceptable: ['2.5', '2.5 m'],
    hints: ['1 m = 100 cm.', 'Smaller→bigger: divide by 100.'],
    explanation: '250 cm ÷ 100 = 2.5 m.' },
  { id: 'md-4', domain: '5.MD', standard: '5.MD.5', tier: 2, type: 'numeric',
    prompt: 'A fish tank is 8 × 4 × 5 inches. What is its volume in cubic inches?',
    diagram: { kind: 'prism', l: 8, w: 4, h: 5 },
    answer: '160', acceptable: ['160'],
    hints: ['Base area = 8 × 4 = 32.', 'Times height 5.'],
    explanation: 'V = 8 × 4 × 5 = 160 cubic inches.' },
  { id: 'md-5', domain: '5.MD', standard: '5.MD.2', tier: 3, type: 'numeric',
    prompt: 'On a line plot, 4 cups hold 1/2 L each and 2 cups hold 1/4 L each. Total liters?',
    answer: '2.5', acceptable: ['2.5', '5/2', '2 1/2'],
    hints: ['4 × 1/2 = 2 L.', '2 × 1/4 = 1/2 L. Add.'],
    explanation: '4 × 1/2 = 2 L; 2 × 1/4 = 1/2 L; total = 2 1/2 = 2.5 L.' },
  { id: 'md-6', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'numeric',
    prompt: 'An L-shaped solid is made of a 3×3×2 box plus a 3×1×2 box. Total volume?',
    answer: '24', acceptable: ['24'],
    hints: ['Find each box: 3×3×2 and 3×1×2.', '18 + 6.'],
    explanation: 'First box 3×3×2 = 18; second 3×1×2 = 6; total = 18 + 6 = 24 cubic units.' },
  { id: 'md-7', domain: '5.MD', standard: '5.MD.1', tier: 4, type: 'numeric',
    prompt: 'A race is 2.5 km. A runner has gone 1750 m. How many METERS are left?',
    answer: '750', acceptable: ['750', '750 m'],
    hints: ['2.5 km = 2500 m.', '2500 − 1750.'],
    explanation: '2.5 km = 2500 m; 2500 − 1750 = 750 m left.' },
  { id: 'md-8', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'constructed',
    prompt: 'A box has volume 48 cm³ and a base of 6 cm × 2 cm. Explain how to find its height.',
    answer: '4', acceptable: ['4', '4 cm', 'divide'],
    hints: ['Base area = 6 × 2 = 12.', 'Height = Volume ÷ base area.'],
    explanation: 'Base area = 6 × 2 = 12 cm². Since V = base × height, height = 48 ÷ 12 = 4 cm.' },
  { id: 'md-9', domain: '5.MD', standard: '5.MD.1', tier: 1, type: 'numeric',
    prompt: 'How many grams are in 3 kilograms?', answer: '3000', acceptable: ['3000', '3,000', '3000 g'],
    hints: ['1 kg = 1000 g.', 'Bigger → smaller unit: multiply.'],
    explanation: '3 kg × 1000 = 3000 grams.' },
  { id: 'md-10', domain: '5.MD', standard: '5.MD.1', tier: 2, type: 'numeric',
    prompt: 'How many quarts are in 3 gallons?', answer: '12', acceptable: ['12', '12 quarts'],
    hints: ['1 gallon = 4 quarts.'],
    explanation: '3 gal × 4 qt/gal = 12 quarts.' },
  { id: 'md-11', domain: '5.MD', standard: '5.MD.2', tier: 2, type: 'multiple-choice',
    prompt: 'A line plot shows plant heights: two Xs at 1/2 in, three Xs at 3/4 in. What is the DIFFERENCE between the tallest and shortest heights?',
    choices: ['1/4 in', '1/2 in', '3/4 in', '1 in'], answer: '1/4 in',
    hints: ['Tallest value 3/4, shortest 1/2.', '3/4 − 1/2 = 3/4 − 2/4.'],
    explanation: '3/4 − 1/2 = 3/4 − 2/4 = 1/4 inch.' },
  { id: 'md-12', domain: '5.MD', standard: '5.MD.1', tier: 3, type: 'numeric',
    prompt: 'How many MINUTES are in 2 1/4 hours?', answer: '135', acceptable: ['135', '135 min'],
    hints: ['1 hour = 60 min, so 2 hours = 120.', '1/4 hour = 15 min.'],
    explanation: '2 × 60 = 120; 1/4 × 60 = 15; total = 135 minutes.' },
  { id: 'md-13', domain: '5.MD', standard: '5.MD.5', tier: 3, type: 'numeric',
    prompt: 'A cube has edges 4 cm long. What is its volume in cm³?',
    diagram: { kind: 'prism', l: 4, w: 4, h: 4 },
    answer: '64', acceptable: ['64'],
    hints: ['All edges equal: V = 4 × 4 × 4.'],
    explanation: 'V = 4 × 4 × 4 = 64 cm³.' },
  { id: 'md-14', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'numeric',
    prompt: 'A box has volume 90 in³. Its length is 5 in and width is 3 in. What is its HEIGHT?',
    answer: '6', acceptable: ['6', '6 in'],
    hints: ['Base area = 5 × 3 = 15.', 'Height = 90 ÷ 15.'],
    explanation: 'V = l × w × h, so h = 90 ÷ (5 × 3) = 90 ÷ 15 = 6 inches.' },
  { id: 'md-15', domain: '5.MD', standard: '5.MD.1', tier: 4, type: 'numeric',
    prompt: 'A package weighs 5 pounds 4 ounces. How many OUNCES is that in total?',
    answer: '84', acceptable: ['84', '84 oz'],
    hints: ['1 lb = 16 oz.', '5 × 16 = 80, then add the extra 4.'],
    explanation: '5 lb = 80 oz; 80 + 4 = 84 ounces.' },
  { id: 'md-16', domain: '5.MD', standard: '5.MD.5', tier: 4, type: 'constructed',
    prompt: 'Two different boxes BOTH have volume 24 cubic units. Give possible dimensions for each and explain how that can happen.',
    answer: '24', acceptable: ['2x3x4', '1x4x6', '2 × 3 × 4', '1 × 4 × 6', 'same volume'],
    hints: ['Find numbers that multiply to 24.', 'Try 2 × 3 × 4 and 1 × 4 × 6.'],
    explanation: '2 × 3 × 4 = 24 and 1 × 4 × 6 = 24. Different shapes can hold the same amount — volume only depends on the PRODUCT of the dimensions.' },
];
