import type { Problem, Lesson } from '../types';

// ===========================================================================
// 5.OA — Operations & Algebraic Thinking
// ===========================================================================

export const lessons: Lesson[] = [
  {
    domain: '5.OA', standard: '5.OA.1',
    title: 'Order of Operations (PEMDAS)',
    steps: [
      'Parentheses / brackets / braces first — innermost first.',
      'Exponents (powers) next.',
      'Multiply & Divide left to right.',
      'Add & Subtract left to right.',
    ],
    example: '3 × (4 + 2) = 3 × 6 = 18. Do the parentheses BEFORE multiplying.',
    tip: 'Grouping symbols nest: braces { } hold brackets [ ] hold parentheses ( ). Work inside-out.',
  },
  {
    domain: '5.OA', standard: '5.OA.2',
    title: 'Write Expressions from Words',
    steps: [
      '"Sum" = +, "difference" = −, "product" = ×, "quotient" = ÷.',
      '"Twice / double" = × 2.  "Times as much" = ×.',
      'Use parentheses when a whole group is acted on.',
    ],
    example: '"Add 8 and 7, then multiply by 2" → 2 × (8 + 7).',
    tip: 'Read carefully: "2 times the sum" needs parentheses; "2 times 8, plus 7" does not.',
  },
  {
    domain: '5.OA', standard: '5.OA.3',
    title: 'Number Patterns & Rules',
    steps: [
      'Find the rule (e.g. "add 3" or "multiply by 2").',
      'Apply the rule to extend the pattern.',
      'Compare two patterns by lining up their terms.',
    ],
    example: 'Start 0, add 3: 0, 3, 6, 9, 12 …',
    tip: 'On MAP, you may plot pattern pairs as points (x, y) — look for the relationship between the two.',
  },
];

export const problems: Problem[] = [
  { id: 'oa-1', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'numeric',
    prompt: 'Evaluate: 2 + 3 × 4', answer: '14', acceptable: ['14'],
    hints: ['Multiply before adding.', '3 × 4 = 12, then + 2.'],
    explanation: 'Multiplication first: 3 × 4 = 12, then 2 + 12 = 14.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['PEMDAS says multiplication comes before addition.', 'Multiply: 3 × 4 = 12.', 'Add: 2 + 12 = 14.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 2 + 3 × 4.', 'Replace 3 × 4 with 12 to get 2 + 12.', '2 + 12 = 14, so the answer is 14.'] },
      { title: 'Way 3: Spot the trap', steps: ['Going left to right gives 2 + 3 = 5, then 5 × 4 = 20 — that is wrong.', 'Multiplication must happen before addition.', 'The correct answer is 14.'] },
    ] },
  { id: 'oa-2', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'multiple-choice',
    prompt: 'Which equals 20?', choices: ['4 × (2 + 3)', '4 × 2 + 3', '(4 × 2) + 3', '4 + 2 × 3'], answer: '4 × (2 + 3)',
    hints: ['Do the parentheses first.', '2 + 3 = 5, then × 4.'],
    explanation: '4 × (2 + 3) = 4 × 5 = 20.',
    solutions: [
      { title: 'Way 1: Build the target', steps: ['The target is 20, and 20 = 4 × 5.', 'You need a 5, and the parentheses in 4 × (2 + 3) make 2 + 3 = 5.', 'So 4 × (2 + 3) = 4 × 5 = 20.'] },
      { title: 'Way 2: Test every choice', steps: ['4 × (2 + 3) = 4 × 5 = 20.', '4 × 2 + 3 = 8 + 3 = 11, and (4 × 2) + 3 = 11 too.', '4 + 2 × 3 = 4 + 6 = 10.', 'Only 4 × (2 + 3) equals 20.'] },
    ] },
  { id: 'oa-3', domain: '5.OA', standard: '5.OA.2', tier: 2, type: 'multiple-choice',
    prompt: 'Choose the expression for: "subtract 6 from 10, then multiply by 5".',
    choices: ['5 × (10 − 6)', '10 − 6 × 5', '(5 × 10) − 6', '10 − (6 × 5)'], answer: '5 × (10 − 6)',
    hints: ['"Then multiply" acts on the whole result.', 'Group the subtraction first.'],
    explanation: 'Do 10 − 6 first (group it), then × 5 → 5 × (10 − 6) = 20.',
    solutions: [
      { title: 'Way 1: Translate piece by piece', steps: ['"Subtract 6 from 10" means 10 − 6.', '"Then multiply by 5" acts on that whole result, so group it: (10 − 6).', 'The expression is 5 × (10 − 6).'] },
      { title: 'Way 2: Eliminate the wrong orders', steps: ['10 − 6 × 5 multiplies first by PEMDAS, giving 10 − 30 — not the story.', '10 − (6 × 5) and (5 × 10) − 6 also do the wrong step first.', 'Only 5 × (10 − 6) subtracts first, then multiplies.'] },
    ] },
  { id: 'oa-4', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'numeric',
    prompt: 'Evaluate: 24 ÷ (2 + 4) × 3', answer: '12', acceptable: ['12'],
    hints: ['Parentheses first: 2 + 4 = 6.', 'Then left to right: 24 ÷ 6 = 4, × 3.'],
    explanation: '2 + 4 = 6; 24 ÷ 6 = 4; 4 × 3 = 12.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['Parentheses first: 2 + 4 = 6.', 'Now read 24 ÷ 6 × 3 from left to right.', '24 ÷ 6 = 4, then 4 × 3 = 12.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 24 ÷ (2 + 4) × 3.', 'It becomes 24 ÷ 6 × 3, then 4 × 3.', '4 × 3 = 12, so the answer is 12.'] },
      { title: 'Way 3: Spot the trap', steps: ['Do not compute 6 × 3 = 18 first — ÷ and × are equal rank.', 'Equal-rank operations go left to right: 24 ÷ 6 = 4 happens first.', 'Then 4 × 3 = 12.'] },
    ] },
  { id: 'oa-5', domain: '5.OA', standard: '5.OA.1', tier: 3, type: 'numeric',
    prompt: 'Evaluate: 3 × [2 + (6 − 4)]', answer: '12', acceptable: ['12'],
    hints: ['Innermost first: 6 − 4 = 2.', 'Then 2 + 2 = 4, then × 3.'],
    explanation: 'Inside-out: 6 − 4 = 2; 2 + 2 = 4; 3 × 4 = 12.',
    solutions: [
      { title: 'Way 1: Work inside-out', steps: ['Innermost parentheses first: 6 − 4 = 2.', 'Brackets next: 2 + 2 = 4.', 'Multiply: 3 × 4 = 12.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 3 × [2 + (6 − 4)].', 'It becomes 3 × [2 + 2], then 3 × 4.', '3 × 4 = 12, so the answer is 12.'] },
    ] },
  { id: 'oa-6', domain: '5.OA', standard: '5.OA.3', tier: 3, type: 'multiple-choice',
    prompt: 'Pattern A starts at 0 and adds 2. Pattern B starts at 0 and adds 4. How do B-terms compare to A-terms?',
    choices: ['B is always 2 times A', 'B is always 2 more than A', 'They are equal', 'A is twice B'], answer: 'B is always 2 times A',
    hints: ['List them: A = 0,2,4,6 … B = 0,4,8,12 …', 'Compare each pair.'],
    explanation: 'A: 0,2,4,6; B: 0,4,8,12. Each B term is exactly 2 × the matching A term.',
    solutions: [
      { title: 'Way 1: Make a table', steps: ['List Pattern A: 0, 2, 4, 6, 8.', 'List Pattern B: 0, 4, 8, 12, 16.', 'Match them up: 4 = 2 × 2, 8 = 2 × 4, 12 = 2 × 6.', 'Every B term is 2 times the matching A term.'] },
      { title: 'Way 2: Compare the rules', steps: ['Both patterns start at the same number, 0.', 'Each step, B grows by 4 while A grows by 2 — twice as fast.', 'So every B term is 2 times the matching A term.'] },
      { title: 'Way 3: Test the wrong choice', steps: ['If B were always 2 MORE than A, every gap would be 2.', 'But 4 − 2 = 2 while 8 − 4 = 4, so the gap keeps changing.', 'The true relationship is B = 2 × A.'] },
    ] },
  { id: 'oa-7', domain: '5.OA', standard: '5.OA.1', tier: 4, type: 'numeric',
    prompt: 'Evaluate: 5 + 2 × [12 ÷ (1 + 3)]', answer: '11', acceptable: ['11'],
    hints: ['Innermost: 1 + 3 = 4.', '12 ÷ 4 = 3; then 2 × 3 = 6; then + 5.'],
    explanation: '1 + 3 = 4; 12 ÷ 4 = 3; 2 × 3 = 6; 5 + 6 = 11.',
    solutions: [
      { title: 'Way 1: Work inside-out', steps: ['Innermost parentheses: 1 + 3 = 4.', 'Brackets: 12 ÷ 4 = 3.', 'Multiply: 2 × 3 = 6.', 'Add: 5 + 6 = 11.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 5 + 2 × [12 ÷ (1 + 3)].', 'It becomes 5 + 2 × [12 ÷ 4], then 5 + 2 × 3.', 'Multiply before adding: 5 + 6 = 11.'] },
    ] },
  { id: 'oa-8', domain: '5.OA', standard: '5.OA.2', tier: 4, type: 'constructed',
    prompt: 'Write an expression (do not solve) for: "the product of 9 and 6, increased by half of 8". Explain your grouping.',
    answer: '9 × 6 + 8 ÷ 2', acceptable: ['9*6+8/2', '(9×6)+(8÷2)', '54+4'],
    hints: ['"Product of 9 and 6" = 9 × 6.', '"Half of 8" = 8 ÷ 2; "increased by" = +.'],
    explanation: '9 × 6 + 8 ÷ 2. Order of operations does the × and ÷ before the +, so no extra parentheses are needed (it equals 58).',
    solutions: [
      { title: 'Way 1: Translate piece by piece', steps: ['"The product of 9 and 6" means 9 × 6.', '"Half of 8" means 8 ÷ 2.', '"Increased by" means add the two parts.', 'The expression is 9 × 6 + 8 ÷ 2.'] },
      { title: 'Way 2: Check the grouping with values', steps: ['The story wants 54 (the product) plus 4 (half of 8), which is 58.', 'In 9 × 6 + 8 ÷ 2, PEMDAS does × and ÷ before +, giving 54 + 4 = 58.', 'The grouping already matches, so 9 × 6 + 8 ÷ 2 needs no extra parentheses.'] },
    ] },
  { id: 'oa-9', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'numeric',
    prompt: 'Evaluate: 18 − (4 + 6)', answer: '8', acceptable: ['8'],
    hints: ['Parentheses first: 4 + 6 = 10.'],
    explanation: '4 + 6 = 10; then 18 − 10 = 8.',
    solutions: [
      { title: 'Way 1: Parentheses first', steps: ['Do the parentheses first: 4 + 6 = 10.', 'Then subtract: 18 − 10 = 8.'] },
      { title: 'Way 2: Subtract one part at a time', steps: ['Subtracting a sum is like subtracting each part in turn.', '18 − 4 = 14, then 14 − 6 = 8.', 'Either way the answer is 8.'] },
    ] },
  { id: 'oa-10', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'numeric',
    prompt: 'Evaluate: (9 − 3) × (2 + 5)', answer: '42', acceptable: ['42'],
    hints: ['Do BOTH parentheses first.', '6 × 7.'],
    explanation: '9 − 3 = 6 and 2 + 5 = 7; then 6 × 7 = 42.',
    solutions: [
      { title: 'Way 1: Both groups first', steps: ['Do each group: 9 − 3 = 6 and 2 + 5 = 7.', 'Multiply the results: 6 × 7 = 42.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with (9 − 3) × (2 + 5).', 'It becomes 6 × (2 + 5), then 6 × 7.', '6 × 7 = 42, so the answer is 42.'] },
    ] },
  { id: 'oa-11', domain: '5.OA', standard: '5.OA.3', tier: 2, type: 'multiple-choice',
    prompt: 'What number comes next in the pattern 3, 6, 12, 24, …?',
    choices: ['30', '36', '48', '27'], answer: '48',
    hints: ['How do you get from 3 to 6? From 6 to 12?', 'Each term doubles.'],
    explanation: 'The rule is "multiply by 2": 24 × 2 = 48.',
    solutions: [
      { title: 'Way 1: Find the rule', steps: ['Check each jump: 3 × 2 = 6, 6 × 2 = 12, 12 × 2 = 24.', 'The rule is multiply by 2.', 'Next term: 24 × 2 = 48.'] },
      { title: 'Way 2: Rule out adding', steps: ['From 3 to 6 is +3, but from 6 to 12 is +6, so it is not adding the same number.', 'Each term is double the term before it.', 'So the next term is 24 × 2 = 48.'] },
    ] },
  { id: 'oa-12', domain: '5.OA', standard: '5.OA.1', tier: 3, type: 'numeric',
    prompt: 'Evaluate: 2 × {3 + [8 ÷ (5 − 1)]}', answer: '10', acceptable: ['10'],
    hints: ['Innermost: 5 − 1 = 4.', '8 ÷ 4 = 2; 3 + 2 = 5; then × 2.'],
    explanation: 'Inside-out: 5 − 1 = 4; 8 ÷ 4 = 2; 3 + 2 = 5; 2 × 5 = 10.',
    solutions: [
      { title: 'Way 1: Work inside-out', steps: ['Innermost parentheses: 5 − 1 = 4.', 'Brackets: 8 ÷ 4 = 2.', 'Braces: 3 + 2 = 5.', 'Multiply: 2 × 5 = 10.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 2 × {3 + [8 ÷ (5 − 1)]}.', 'It becomes 2 × {3 + [8 ÷ 4]}, then 2 × {3 + 2}.', 'Finally 2 × 5 = 10.'] },
    ] },
  { id: 'oa-13', domain: '5.OA', standard: '5.OA.2', tier: 3, type: 'multiple-choice',
    prompt: 'Without computing, which expression is THREE TIMES as large as 4 + 5?',
    choices: ['3 × (4 + 5)', '3 + 4 + 5', '(3 × 4) + 5', '3 × 4 × 5'], answer: '3 × (4 + 5)',
    hints: ['"Three times as large as the sum" multiplies the WHOLE sum.'],
    explanation: '3 × (4 + 5) is exactly 3 times the value of 4 + 5 — no need to compute (this is 5.OA.2 reasoning).',
    solutions: [
      { title: 'Way 1: Think in chunks', steps: ['Treat (4 + 5) as one chunk — the whole sum.', 'Multiplying that chunk by 3 makes it exactly three times as large.', 'So 3 × (4 + 5) is the answer with no arithmetic needed.'] },
      { title: 'Way 2: Verify by computing', steps: ['4 + 5 = 9, and three times 9 is 27.', '3 × (4 + 5) = 3 × 9 = 27, so it matches.', 'The other choices give 12, 17, and 60 — none is 27.'] },
    ] },
  { id: 'oa-14', domain: '5.OA', standard: '5.OA.3', tier: 4, type: 'numeric',
    prompt: 'A table follows the rule y = 3 × x. The pairs are (1,3), (2,6), (3,9). What is y when x = 7?',
    answer: '21', acceptable: ['21'],
    hints: ['Apply the rule: multiply x by 3.'],
    explanation: 'y = 3 × 7 = 21. On MAP these pairs are often plotted as points on a coordinate grid.',
    solutions: [
      { title: 'Way 1: Apply the rule', steps: ['The rule says multiply x by 3.', 'When x = 7, y = 3 × 7 = 21.'] },
      { title: 'Way 2: Extend the table', steps: ['Keep the table going: (4, 12), (5, 15), (6, 18), (7, 21).', 'When x = 7, y = 21.'] },
      { title: 'Way 3: Count the jumps', steps: ['Each time x goes up by 1, y goes up by 3.', 'From (3, 9) to x = 7 is 4 jumps, so y adds 4 × 3 = 12.', '9 + 12 = 21, so y = 21.'] },
    ] },
  { id: 'oa-15', domain: '5.OA', standard: '5.OA.1', tier: 4, type: 'multiple-choice',
    prompt: 'Which expression CHANGES value if you remove its parentheses?',
    choices: ['5 × (3 + 2)', '(5 × 3) + 2', '(5 + 3) + 2', '5 + (3 × 2)'], answer: '5 × (3 + 2)',
    hints: ['Try each one with and without parentheses.', '5 × (3+2) = 25, but 5 × 3 + 2 = 17.'],
    explanation: '5 × (3 + 2) = 25, but without parentheses 5 × 3 + 2 = 17. The others keep the same value because of order of operations.',
    solutions: [
      { title: 'Way 1: Test each choice', steps: ['5 × (3 + 2) = 5 × 5 = 25, but 5 × 3 + 2 = 17 — different!', '(5 × 3) + 2 = 17 either way, and (5 + 3) + 2 = 10 either way.', '5 + (3 × 2) = 11 either way.', 'Only 5 × (3 + 2) changes, so it is the answer.'] },
      { title: 'Way 2: Think about PEMDAS', steps: ['Parentheses only matter when they force a DIFFERENT order than PEMDAS.', 'In three of the choices, the parentheses match what PEMDAS would do anyway.', 'In 5 × (3 + 2), they force adding before multiplying, so removing them changes the value.'] },
    ] },
  { id: 'oa-16', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'numeric',
    prompt: 'Evaluate: 10 − 2 × 3', answer: '4', acceptable: ['4'],
    hints: ['Multiply before subtracting.', '2 × 3 = 6, then 10 − 6.'],
    explanation: 'Multiply first: 2 × 3 = 6, then 10 − 6 = 4.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['PEMDAS says multiplication comes before subtraction.', 'Multiply: 2 × 3 = 6.', 'Subtract: 10 − 6 = 4.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 10 − 2 × 3.', 'Replace 2 × 3 with 6 to get 10 − 6.', '10 − 6 = 4, so the answer is 4.'] },
      { title: 'Way 3: Spot the trap', steps: ['Left to right would give 10 − 2 = 8, then 8 × 3 = 24 — that is wrong.', 'Multiplication must happen before subtraction.', 'The correct answer is 4.'] },
    ] },
  { id: 'oa-17', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'multiple-choice',
    prompt: 'What should you do FIRST to evaluate 8 + 12 ÷ 4?',
    choices: ['Divide 12 by 4', 'Add 8 and 12', 'Add 8 and 4', 'Divide 8 by 4'], answer: 'Divide 12 by 4',
    hints: ['Remember PEMDAS: where does division come?', 'Division happens before addition.'],
    explanation: 'Division comes before addition, so do 12 ÷ 4 = 3 first, then 8 + 3 = 11.',
    solutions: [
      { title: 'Way 1: Use the PEMDAS order', steps: ['There are no parentheses or exponents here.', 'Division comes before addition in PEMDAS.', 'So the first step is to divide 12 by 4.'] },
      { title: 'Way 2: Compare the two orders', steps: ['Dividing first gives 8 + 3 = 11.', 'Adding first would give 20 ÷ 4 = 5 — a different number.', 'PEMDAS picks the first order, so divide 12 by 4 first.'] },
    ] },
  { id: 'oa-18', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'numeric',
    prompt: 'Evaluate: (7 + 5) ÷ 3', answer: '4', acceptable: ['4'],
    hints: ['Parentheses first: 7 + 5 = 12.', 'Then divide by 3.'],
    explanation: '7 + 5 = 12; then 12 ÷ 3 = 4.',
    solutions: [
      { title: 'Way 1: Parentheses first', steps: ['Do the parentheses first: 7 + 5 = 12.', 'Then divide: 12 ÷ 3 = 4.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with (7 + 5) ÷ 3.', 'It becomes 12 ÷ 3.', '12 ÷ 3 = 4, so the answer is 4.'] },
    ] },
  { id: 'oa-19', domain: '5.OA', standard: '5.OA.2', tier: 1, type: 'multiple-choice',
    prompt: 'Which expression matches the words "the sum of 4 and 9"?',
    choices: ['4 + 9', '4 × 9', '9 − 4', '4 ÷ 9'], answer: '4 + 9',
    hints: ['"Sum" is the result of one operation.', 'Sum means addition.'],
    explanation: '"Sum" always means addition, so the expression is 4 + 9.',
    solutions: [
      { title: 'Way 1: Know the keyword', steps: ['"Sum" is the keyword for addition.', 'The sum of 4 and 9 is written 4 + 9.'] },
      { title: 'Way 2: Name every choice', steps: ['4 × 9 is a product, 9 − 4 is a difference, and 4 ÷ 9 is a quotient.', 'Only 4 + 9 is a sum.', 'So 4 + 9 matches the words.'] },
    ] },
  { id: 'oa-20', domain: '5.OA', standard: '5.OA.3', tier: 1, type: 'numeric',
    prompt: 'A pattern starts at 5 and follows the rule "add 4": 5, 9, 13, … What is the next term?',
    answer: '17', acceptable: ['17'],
    hints: ['Apply the rule to the last term shown.', '13 + 4 = ?'],
    explanation: 'Add 4 to the last term: 13 + 4 = 17.',
    solutions: [
      { title: 'Way 1: Apply the rule', steps: ['The rule is add 4 each time.', 'The last term shown is 13.', '13 + 4 = 17, so the next term is 17.'] },
      { title: 'Way 2: Check the jumps', steps: ['Check that each jump is +4: 5 + 4 = 9 and 9 + 4 = 13.', 'The rule works, so keep going: 13 + 4 = 17.'] },
    ] },
  { id: 'oa-21', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'multiple-choice',
    prompt: 'Evaluate: 6 × 2 + 1', choices: ['13', '18', '14', '9'], answer: '13',
    hints: ['Multiply before adding.', '6 × 2 = 12, then + 1.'],
    explanation: 'Multiply first: 6 × 2 = 12, then 12 + 1 = 13.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['Multiplication comes before addition.', 'Multiply: 6 × 2 = 12.', 'Add: 12 + 1 = 13.'] },
      { title: 'Way 2: Spot the trap answer', steps: ['The choice 18 comes from adding first: 2 + 1 = 3, then 6 × 3 = 18.', 'That breaks PEMDAS — you must multiply first.', '6 × 2 + 1 = 12 + 1 = 13.'] },
    ] },
  { id: 'oa-22', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'numeric',
    prompt: 'Evaluate: 20 ÷ 4 + 1', answer: '6', acceptable: ['6'],
    hints: ['Divide before adding.', '20 ÷ 4 = 5, then + 1.'],
    explanation: 'Divide first: 20 ÷ 4 = 5, then 5 + 1 = 6.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['Division comes before addition.', 'Divide: 20 ÷ 4 = 5.', 'Add: 5 + 1 = 6.'] },
      { title: 'Way 2: Spot the trap', steps: ['Adding first would give 20 ÷ 5 = 4 — that is wrong.', 'Without parentheses, division happens before addition.', 'The correct answer is 6.'] },
    ] },
  { id: 'oa-23', domain: '5.OA', standard: '5.OA.3', tier: 1, type: 'multiple-choice',
    prompt: 'What is the rule for the pattern 2, 4, 6, 8?',
    choices: ['Add 2', 'Multiply by 2', 'Add 4', 'Subtract 2'], answer: 'Add 2',
    hints: ['Look at the jump from each term to the next.', 'Check ALL the jumps, not just the first one.'],
    explanation: 'Every jump is + 2: 2, 4, 6, 8 — the rule is add 2.',
    solutions: [
      { title: 'Way 1: Check every jump', steps: ['2 + 2 = 4, 4 + 2 = 6, and 6 + 2 = 8.', 'Every jump adds 2.', 'The rule is add 2.'] },
      { title: 'Way 2: Rule out multiply by 2', steps: ['Multiply by 2 works for the first jump: 2 × 2 = 4.', 'But then 4 × 2 = 8, not 6 — so that rule fails.', 'Only add 2 fits every term.'] },
    ] },
  { id: 'oa-24', domain: '5.OA', standard: '5.OA.1', tier: 1, type: 'numeric',
    prompt: 'Evaluate: 2 × (3 + 4)', answer: '14', acceptable: ['14'],
    hints: ['Parentheses first: 3 + 4 = 7.', 'Then 2 × 7.'],
    explanation: '3 + 4 = 7; then 2 × 7 = 14.',
    solutions: [
      { title: 'Way 1: Parentheses first', steps: ['Do the parentheses first: 3 + 4 = 7.', 'Multiply: 2 × 7 = 14.'] },
      { title: 'Way 2: Double each part', steps: ['Doubling a sum is the same as doubling each part.', '2 × 3 = 6 and 2 × 4 = 8.', '6 + 8 = 14, the same answer.'] },
    ] },
  { id: 'oa-25', domain: '5.OA', standard: '5.OA.2', tier: 2, type: 'multiple-choice',
    prompt: 'Which expression matches: "add 8 and 7, then multiply the result by 2"?',
    choices: ['2 × (8 + 7)', '2 × 8 + 7', '8 + 7 × 2', '2 + 8 × 7'], answer: '2 × (8 + 7)',
    hints: ['"Then multiply the RESULT" means the whole sum gets multiplied.', 'Group the addition in parentheses first.'],
    explanation: 'The whole sum is multiplied, so group it: 2 × (8 + 7).',
    solutions: [
      { title: 'Way 1: Translate piece by piece', steps: ['"Add 8 and 7" means 8 + 7.', '"Then multiply the result by 2" acts on the whole sum, so group it.', 'The expression is 2 × (8 + 7).'] },
      { title: 'Way 2: Test with values', steps: ['The story says add first: 8 + 7 = 15, then double it to get 30.', '2 × (8 + 7) = 2 × 15 = 30 — it matches.', '2 × 8 + 7 = 23 and 8 + 7 × 2 = 22, so those do not match.'] },
    ] },
  { id: 'oa-26', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'numeric',
    prompt: 'Evaluate: 36 ÷ (3 × 2)', answer: '6', acceptable: ['6'],
    hints: ['Parentheses first: 3 × 2 = 6.', 'Then 36 ÷ 6.'],
    explanation: '3 × 2 = 6; then 36 ÷ 6 = 6.',
    solutions: [
      { title: 'Way 1: Parentheses first', steps: ['Do the parentheses first: 3 × 2 = 6.', 'Then divide: 36 ÷ 6 = 6.'] },
      { title: 'Way 2: Spot the trap', steps: ['Without parentheses, 36 ÷ 3 × 2 would go left to right: 12 × 2 = 24.', 'The parentheses force 3 × 2 = 6 to happen first.', '36 ÷ 6 = 6, so the answer is 6.'] },
    ] },
  { id: 'oa-27', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'numeric',
    prompt: 'Evaluate: 5 × 4 − 12 ÷ 3', answer: '16', acceptable: ['16'],
    hints: ['Do BOTH the × and the ÷ before subtracting.', '20 − 4.'],
    explanation: '5 × 4 = 20 and 12 ÷ 3 = 4; then 20 − 4 = 16.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['Multiplication and division come before subtraction.', 'Multiply: 5 × 4 = 20. Divide: 12 ÷ 3 = 4.', 'Subtract: 20 − 4 = 16.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 5 × 4 − 12 ÷ 3.', 'It becomes 20 − 12 ÷ 3, then 20 − 4.', '20 − 4 = 16, so the answer is 16.'] },
    ] },
  { id: 'oa-28', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'multiple-choice',
    prompt: 'Insert parentheses to make this true: 4 + 2 × 5 = 30.',
    choices: ['(4 + 2) × 5', '4 + (2 × 5)', '(4 + 2 × 5)', '4 + 2 × (5)'], answer: '(4 + 2) × 5',
    hints: ['Without parentheses, 4 + 2 × 5 = 14, not 30.', 'What two numbers multiply to 30? Try 6 × 5.'],
    explanation: '(4 + 2) × 5 = 6 × 5 = 30; the parentheses force the addition first.',
    solutions: [
      { title: 'Way 1: Work backward from 30', steps: ['30 = 6 × 5, and 6 can come from 4 + 2.', 'Group the addition: (4 + 2) × 5.', 'Check: (4 + 2) × 5 = 6 × 5 = 30.'] },
      { title: 'Way 2: Test every choice', steps: ['(4 + 2) × 5 = 6 × 5 = 30 — it works.', '4 + (2 × 5) = 4 + 10 = 14, the same as no parentheses.', '(4 + 2 × 5) and 4 + 2 × (5) also equal 14.', 'Only (4 + 2) × 5 makes 30.'] },
    ] },
  { id: 'oa-29', domain: '5.OA', standard: '5.OA.3', tier: 2, type: 'multiple-choice',
    prompt: 'What is the rule for the pattern 40, 35, 30, 25?',
    choices: ['Subtract 5', 'Add 5', 'Divide by 5', 'Subtract 10'], answer: 'Subtract 5',
    hints: ['Are the terms going up or down?', 'Find the size of each jump.'],
    explanation: 'Each term is 5 less than the one before: the rule is subtract 5.',
    solutions: [
      { title: 'Way 1: Check every jump', steps: ['40 − 5 = 35, 35 − 5 = 30, and 30 − 5 = 25.', 'Every jump subtracts 5.', 'The rule is subtract 5.'] },
      { title: 'Way 2: Rule out dividing', steps: ['Divide by 5 would give 40 ÷ 5 = 8, but the next term is 35.', 'Subtract 10 would give 40 − 10 = 30, but the next term is 35.', 'Only subtract 5 fits, so that is the rule.'] },
    ] },
  { id: 'oa-30', domain: '5.OA', standard: '5.OA.3', tier: 2, type: 'multiple-choice',
    prompt: 'What number comes next in the pattern 2, 6, 18, …?',
    choices: ['54', '24', '36', '22'], answer: '54',
    hints: ['How do you get from 2 to 6? From 6 to 18?', 'Each term is 3 times the one before.'],
    explanation: 'The rule is multiply by 3: 18 × 3 = 54.',
    solutions: [
      { title: 'Way 1: Find the rule', steps: ['2 × 3 = 6 and 6 × 3 = 18.', 'The rule is multiply by 3.', 'Next term: 18 × 3 = 54.'] },
      { title: 'Way 2: Rule out adding', steps: ['From 2 to 6 is +4, but from 6 to 18 is +12, so it is not adding the same number.', 'Each term is triple the term before.', 'So the next term is 18 × 3 = 54.'] },
    ] },
  { id: 'oa-31', domain: '5.OA', standard: '5.OA.2', tier: 2, type: 'multiple-choice',
    prompt: 'Without computing, how does 6 × (30 + 7) compare to 30 + 7?',
    choices: ['It is 6 times as large', 'It is 6 more', 'It is the same', 'It is 7 times as large'], answer: 'It is 6 times as large',
    hints: ['Treat (30 + 7) as one chunk.', 'What does multiplying a chunk by 6 do to it?'],
    explanation: 'Multiplying the whole sum by 6 makes it exactly 6 times as large — no computing needed.',
    solutions: [
      { title: 'Way 1: Think in chunks', steps: ['Treat (30 + 7) as one chunk.', '6 × (30 + 7) is that chunk taken 6 times.', 'So it is 6 times as large — no arithmetic needed.'] },
      { title: 'Way 2: Verify with the numbers', steps: ['30 + 7 = 37.', '6 × 37 = 222, and 222 = 6 × 37 exactly.', 'That confirms it is 6 times as large, not 6 more.'] },
    ] },
  { id: 'oa-32', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'numeric',
    prompt: 'Evaluate: 50 − (6 + 4) × 3', answer: '20', acceptable: ['20'],
    hints: ['Parentheses first: 6 + 4 = 10.', 'Then multiply by 3 BEFORE subtracting.'],
    explanation: '6 + 4 = 10; 10 × 3 = 30; 50 − 30 = 20.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['Parentheses first: 6 + 4 = 10.', 'Multiply before subtracting: 10 × 3 = 30.', 'Subtract: 50 − 30 = 20.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 50 − (6 + 4) × 3.', 'It becomes 50 − 10 × 3, then 50 − 30.', '50 − 30 = 20, so the answer is 20.'] },
      { title: 'Way 3: Spot the trap', steps: ['Do not compute 50 − 10 = 40 first and then × 3 = 120.', 'Multiplication comes before subtraction.', 'The correct answer is 20.'] },
    ] },
  { id: 'oa-33', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'multiple-choice',
    prompt: 'Leo computed 2 + 3 × 4 = 20. What went wrong?',
    choices: ['He added 2 + 3 before multiplying', 'He multiplied 3 × 4 first', 'He used the wrong numbers', 'Nothing — 20 is correct'], answer: 'He added 2 + 3 before multiplying',
    hints: ['What is the correct value of 2 + 3 × 4?', 'How could Leo have gotten 20?'],
    explanation: 'Leo did 2 + 3 = 5 first, then 5 × 4 = 20; PEMDAS requires 3 × 4 = 12 first, so the answer is 14.',
    solutions: [
      { title: 'Way 1: Find the correct answer first', steps: ['PEMDAS: multiply first, 3 × 4 = 12.', 'Then 2 + 12 = 14, so 20 is wrong.', 'Leo must have broken the order of operations.'] },
      { title: 'Way 2: Rebuild the mistake', steps: ['Ask: what steps give 20?', 'Adding first gives 2 + 3 = 5, and 5 × 4 = 20 — that matches Leo.', 'So his error was adding before multiplying.'] },
    ] },
  { id: 'oa-34', domain: '5.OA', standard: '5.OA.2', tier: 2, type: 'constructed',
    prompt: 'Write an expression (do not solve) for: "3 times the sum of 4 and 5".',
    answer: '3 × (4 + 5)', acceptable: ['3*(4+5)', '3×(4+5)', '(4+5)×3', '(4+5)*3', '(5+4)×3'],
    hints: ['"The sum of 4 and 5" is one chunk: (4 + 5).', '"3 times" multiplies that whole chunk.'],
    explanation: 'Group the sum, then multiply: 3 × (4 + 5).',
    solutions: [
      { title: 'Way 1: Translate piece by piece', steps: ['"The sum of 4 and 5" means 4 + 5.', '"3 times" that whole sum means multiply the group by 3.', 'The expression is 3 × (4 + 5).'] },
      { title: 'Way 2: Check why parentheses matter', steps: ['Without parentheses, 3 × 4 + 5 = 17 by PEMDAS.', 'But 3 times the sum should be 3 × 9 = 27.', 'Only 3 × (4 + 5) gives 27, so the parentheses are required.'] },
    ] },
  { id: 'oa-35', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'numeric',
    prompt: 'Evaluate: 7 + 3 × (10 − 4)', answer: '25', acceptable: ['25'],
    hints: ['Parentheses first: 10 − 4 = 6.', 'Then 3 × 6 = 18, then + 7.'],
    explanation: '10 − 4 = 6; 3 × 6 = 18; 7 + 18 = 25.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['Parentheses first: 10 − 4 = 6.', 'Multiply before adding: 3 × 6 = 18.', 'Add: 7 + 18 = 25.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 7 + 3 × (10 − 4).', 'It becomes 7 + 3 × 6, then 7 + 18.', '7 + 18 = 25, so the answer is 25.'] },
    ] },
  { id: 'oa-36', domain: '5.OA', standard: '5.OA.3', tier: 2, type: 'multiple-choice',
    prompt: 'The points (1, 6), (2, 7), and (3, 8) follow the rule y = x + 5. What is y when x = 10?',
    diagram: { kind: 'coordinate', points: [{ x: 1, y: 6 }, { x: 2, y: 7 }, { x: 3, y: 8 }], max: 10 },
    choices: ['15', '50', '16', '10'], answer: '15',
    hints: ['Apply the rule: add 5 to x.', '10 + 5 = ?'],
    explanation: 'y = x + 5, so when x = 10, y = 10 + 5 = 15.',
    solutions: [
      { title: 'Way 1: Apply the rule', steps: ['The rule says add 5 to x.', 'When x = 10, y = 10 + 5 = 15.'] },
      { title: 'Way 2: Check the rule on the points', steps: ['Test the points: 1 + 5 = 6, 2 + 5 = 7, 3 + 5 = 8 — the rule fits.', 'So for x = 10, y = 10 + 5 = 15.'] },
      { title: 'Way 3: Spot the trap', steps: ['50 comes from multiplying 10 × 5, but the rule ADDS 5.', 'Each y is exactly 5 more than its x.', 'So y = 15 when x = 10.'] },
    ] },
  { id: 'oa-37', domain: '5.OA', standard: '5.OA.1', tier: 2, type: 'numeric',
    prompt: 'Evaluate: 48 ÷ 6 + 2 × 5', answer: '18', acceptable: ['18'],
    hints: ['Do the ÷ and the × before the +.', '8 + 10.'],
    explanation: '48 ÷ 6 = 8 and 2 × 5 = 10; then 8 + 10 = 18.',
    solutions: [
      { title: 'Way 1: PEMDAS step by step', steps: ['Division and multiplication come before addition.', 'Divide: 48 ÷ 6 = 8. Multiply: 2 × 5 = 10.', 'Add: 8 + 10 = 18.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 48 ÷ 6 + 2 × 5.', 'It becomes 8 + 2 × 5, then 8 + 10.', '8 + 10 = 18, so the answer is 18.'] },
    ] },
  { id: 'oa-38', domain: '5.OA', standard: '5.OA.2', tier: 2, type: 'multiple-choice',
    prompt: 'Which words match the expression 4 × (9 − 2)?',
    choices: ['4 times the difference of 9 and 2', '4 times 9, then subtract 2', 'the product of 4 and 9, minus 2', 'subtract 2 from 9 times 4'], answer: '4 times the difference of 9 and 2',
    hints: ['The parentheses hold a difference.', 'The WHOLE difference gets multiplied by 4.'],
    explanation: 'The parentheses group the difference 9 − 2, and the whole thing is multiplied by 4.',
    solutions: [
      { title: 'Way 1: Read the grouping', steps: ['Inside the parentheses is 9 − 2, the difference of 9 and 2.', 'The 4 multiplies that whole difference.', 'So the words are "4 times the difference of 9 and 2".'] },
      { title: 'Way 2: Test with values', steps: ['4 × (9 − 2) = 4 × 7 = 28.', '"4 times 9, then subtract 2" gives 36 − 2 = 34 — the other three choices all mean 34.', 'Only the difference phrase gives 28, so it matches.'] },
    ] },
  { id: 'oa-39', domain: '5.OA', standard: '5.OA.1', tier: 3, type: 'numeric',
    prompt: 'Evaluate: 4 × [3 + (10 − 8)]', answer: '20', acceptable: ['20'],
    hints: ['Innermost first: 10 − 8 = 2.', 'Then 3 + 2 = 5, then × 4.'],
    explanation: 'Inside-out: 10 − 8 = 2; 3 + 2 = 5; 4 × 5 = 20.',
    solutions: [
      { title: 'Way 1: Work inside-out', steps: ['Innermost parentheses: 10 − 8 = 2.', 'Brackets: 3 + 2 = 5.', 'Multiply: 4 × 5 = 20.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 4 × [3 + (10 − 8)].', 'It becomes 4 × [3 + 2], then 4 × 5.', '4 × 5 = 20, so the answer is 20.'] },
    ] },
  { id: 'oa-40', domain: '5.OA', standard: '5.OA.1', tier: 3, type: 'multiple-choice',
    prompt: 'Which placement of parentheses makes 5 + 3 × 2 − 1 equal 15?',
    choices: ['(5 + 3) × 2 − 1', '5 + 3 × (2 − 1)', '(5 + 3) × (2 − 1)', '5 + (3 × 2) − 1'], answer: '(5 + 3) × 2 − 1',
    hints: ['Without parentheses the value is 5 + 6 − 1 = 10.', 'Try to build 16 − 1.'],
    explanation: '(5 + 3) × 2 − 1 = 8 × 2 − 1 = 16 − 1 = 15.',
    solutions: [
      { title: 'Way 1: Work backward from 15', steps: ['15 could be 16 − 1, and 16 = 8 × 2.', '8 comes from 5 + 3, so group that: (5 + 3) × 2 − 1.', 'Check: 8 × 2 − 1 = 16 − 1 = 15.'] },
      { title: 'Way 2: Test every choice', steps: ['(5 + 3) × 2 − 1 = 16 − 1 = 15 — it works.', '5 + 3 × (2 − 1) = 5 + 3 = 8.', '(5 + 3) × (2 − 1) = 8 × 1 = 8, and 5 + (3 × 2) − 1 = 10.', 'Only the first choice makes 15.'] },
    ] },
  { id: 'oa-41', domain: '5.OA', standard: '5.OA.3', tier: 3, type: 'numeric',
    prompt: 'Pattern A starts at 0 and adds 3: 0, 3, 6, 9, 12. Pattern B starts at 0 and adds 6. What B term matches the A term 12?',
    answer: '24', acceptable: ['24'],
    hints: ['Write Pattern B under Pattern A, term by term.', '12 is the 5th term of A — find the 5th term of B.'],
    explanation: 'B: 0, 6, 12, 18, 24 — the term matching A = 12 is 24, which is 2 × 12.',
    solutions: [
      { title: 'Way 1: Line up both patterns', steps: ['Pattern A: 0, 3, 6, 9, 12.', 'Pattern B: 0, 6, 12, 18, 24.', 'The A term 12 is in the 5th spot, and the 5th B term is 24.'] },
      { title: 'Way 2: Use the relationship', steps: ['B adds 6 while A adds 3, and both start at 0.', 'So every B term is 2 times the matching A term.', '2 × 12 = 24, so the B term is 24.'] },
    ] },
  { id: 'oa-42', domain: '5.OA', standard: '5.OA.2', tier: 3, type: 'multiple-choice',
    prompt: 'Without computing, compare (44 + 16) ÷ 4 to 44 + 16.',
    choices: ['It is one fourth as large', 'It is 4 times as large', 'It is 4 less', 'It is the same'], answer: 'It is one fourth as large',
    hints: ['Treat (44 + 16) as one chunk.', 'What does dividing a chunk by 4 do to it?'],
    explanation: 'Dividing the whole sum by 4 makes it one fourth as large — no computing needed.',
    solutions: [
      { title: 'Way 1: Think in chunks', steps: ['Treat (44 + 16) as one chunk.', 'Dividing the chunk by 4 splits it into 4 equal parts and keeps one.', 'So the result is one fourth as large as 44 + 16.'] },
      { title: 'Way 2: Verify with the numbers', steps: ['44 + 16 = 60 and 60 ÷ 4 = 15.', '15 is exactly one fourth of 60.', 'That confirms the answer: one fourth as large.'] },
    ] },
  { id: 'oa-43', domain: '5.OA', standard: '5.OA.1', tier: 3, type: 'numeric',
    prompt: 'Evaluate: 100 − 2 × [15 + (3 × 5)]', answer: '40', acceptable: ['40'],
    hints: ['Innermost first: 3 × 5 = 15.', 'Then 15 + 15 = 30; 2 × 30 = 60; 100 − 60.'],
    explanation: '3 × 5 = 15; 15 + 15 = 30; 2 × 30 = 60; 100 − 60 = 40.',
    solutions: [
      { title: 'Way 1: Work inside-out', steps: ['Innermost parentheses: 3 × 5 = 15.', 'Brackets: 15 + 15 = 30.', 'Multiply: 2 × 30 = 60.', 'Subtract: 100 − 60 = 40.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 100 − 2 × [15 + (3 × 5)].', 'It becomes 100 − 2 × [15 + 15], then 100 − 2 × 30.', 'Then 100 − 60 = 40.'] },
      { title: 'Way 3: Spot the trap', steps: ['Do not do 100 − 2 = 98 first.', 'The 2 must multiply the whole bracket before any subtracting.', 'The correct answer is 40.'] },
    ] },
  { id: 'oa-44', domain: '5.OA', standard: '5.OA.3', tier: 3, type: 'multiple-choice',
    prompt: 'The points (1, 2), (2, 4), and (3, 6) are plotted from a pattern table. Which rule relates y to x?',
    diagram: { kind: 'coordinate', points: [{ x: 1, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 6 }], max: 8 },
    choices: ['y = 2 × x', 'y = x + 2', 'y = x + 1', 'y = 3 × x'], answer: 'y = 2 × x',
    hints: ['Test each rule on ALL three points.', 'Does doubling each x give its y?'],
    explanation: 'Each y is double its x: 2 = 2 × 1, 4 = 2 × 2, 6 = 2 × 3, so y = 2 × x.',
    solutions: [
      { title: 'Way 1: Test the rule on every point', steps: ['Try y = 2 × x: 2 × 1 = 2, 2 × 2 = 4, 2 × 3 = 6.', 'All three points fit.', 'The rule is y = 2 × x.'] },
      { title: 'Way 2: Eliminate the other rules', steps: ['y = x + 2 fails at (1, 2) because 1 + 2 = 3, not 2.', 'y = x + 1 gives (1, 2) but fails at (2, 4) since 2 + 1 = 3.', 'y = 3 × x gives (1, 3), not (1, 2).', 'Only y = 2 × x fits every point.'] },
    ] },
  { id: 'oa-45', domain: '5.OA', standard: '5.OA.2', tier: 3, type: 'constructed',
    prompt: 'Write an expression (do not solve) for: "the quotient of 18 and 3, decreased by 2".',
    answer: '18 ÷ 3 − 2', acceptable: ['18/3-2', '18÷3−2', '(18÷3)−2', '(18/3)-2', '6-2'],
    hints: ['"Quotient of 18 and 3" = 18 ÷ 3.', '"Decreased by 2" means subtract 2 at the end.'],
    explanation: '18 ÷ 3 − 2; PEMDAS divides before subtracting, so no parentheses are needed.',
    solutions: [
      { title: 'Way 1: Translate piece by piece', steps: ['"The quotient of 18 and 3" means 18 ÷ 3.', '"Decreased by 2" means subtract 2 from that result.', 'The expression is 18 ÷ 3 − 2.'] },
      { title: 'Way 2: Check the grouping with values', steps: ['The story wants 6 (the quotient) minus 2, which is 4.', 'PEMDAS divides before subtracting, so 18 ÷ 3 − 2 = 6 − 2 = 4.', 'The order already matches, so 18 ÷ 3 − 2 needs no parentheses.'] },
    ] },
  { id: 'oa-46', domain: '5.OA', standard: '5.OA.2', tier: 3, type: 'constructed',
    prompt: 'Write an expression (do not solve) for: "the sum of 6 and 9, divided by 5".',
    answer: '(6 + 9) ÷ 5', acceptable: ['(6+9)/5', '(6+9)÷5', '(9+6)÷5', '(9+6)/5'],
    hints: ['The WHOLE sum gets divided.', 'Group the sum in parentheses before dividing.'],
    explanation: 'The whole sum is divided, so group it: (6 + 9) ÷ 5.',
    solutions: [
      { title: 'Way 1: Translate piece by piece', steps: ['"The sum of 6 and 9" means 6 + 9.', 'The whole sum is divided by 5, so group it.', 'The expression is (6 + 9) ÷ 5.'] },
      { title: 'Way 2: Check why parentheses matter', steps: ['Without parentheses, 6 + 9 ÷ 5 divides only the 9 by PEMDAS.', 'The story divides the WHOLE sum, 15, by 5 to get 3.', 'Only (6 + 9) ÷ 5 equals 3, so the parentheses are required.'] },
    ] },
  { id: 'oa-47', domain: '5.OA', standard: '5.OA.1', tier: 3, type: 'multiple-choice',
    prompt: 'Mia says 36 ÷ 6 ÷ 2 = 12 because she divided 6 by 2 first. What is true?',
    choices: ['She is wrong; dividing left to right gives 3', 'She is right; 12 is correct', 'She is wrong; the answer is 6', 'She is wrong; the answer is 1'], answer: 'She is wrong; dividing left to right gives 3',
    hints: ['With two divisions and no parentheses, which comes first?', 'Equal-rank operations go left to right.'],
    explanation: 'Divisions go left to right: 36 ÷ 6 = 6, then 6 ÷ 2 = 3, not 12.',
    solutions: [
      { title: 'Way 1: Go left to right', steps: ['With no parentheses, equal-rank operations go left to right.', 'First: 36 ÷ 6 = 6.', 'Then: 6 ÷ 2 = 3, so the answer is 3, not 12.'] },
      { title: 'Way 2: Rebuild the mistake', steps: ['Mia did 6 ÷ 2 = 3 first, then 36 ÷ 3 = 12.', 'That order would need parentheses: 36 ÷ (6 ÷ 2).', 'Without them, left to right gives 3.'] },
    ] },
  { id: 'oa-48', domain: '5.OA', standard: '5.OA.3', tier: 3, type: 'numeric',
    prompt: 'Pattern A starts at 1 and multiplies by 2: 1, 2, 4, 8. Pattern B starts at 1 and multiplies by 4. What is the 4th term of Pattern B?',
    answer: '64', acceptable: ['64'],
    hints: ['Build Pattern B term by term.', '1, 4, 16, then × 4 once more.'],
    explanation: 'Pattern B: 1, 4, 16, 64 — the 4th term is 64.',
    solutions: [
      { title: 'Way 1: Build the pattern', steps: ['Start at 1 and multiply by 4 each time.', '1 × 4 = 4, then 4 × 4 = 16, then 16 × 4 = 64.', 'The 4th term is 64.'] },
      { title: 'Way 2: Compare with Pattern A', steps: ['Pattern A doubles: 1, 2, 4, 8.', 'Pattern B grows by × 4, which is doubling twice each step.', 'Term by term B is the square of A: 8 × 8 = 64, so the 4th term is 64.'] },
    ] },
  { id: 'oa-49', domain: '5.OA', standard: '5.OA.2', tier: 3, type: 'multiple-choice',
    prompt: 'Which words match the expression 2 × 8 + 7?',
    choices: ['the product of 2 and 8, plus 7', '2 times the sum of 8 and 7', 'add 8 and 7, then double the result', 'twice the sum of 7 and 8'], answer: 'the product of 2 and 8, plus 7',
    hints: ['There are NO parentheses, so the × only touches 2 and 8.', '"Sum" phrases would need parentheses.'],
    explanation: 'With no parentheses, only 2 × 8 is multiplied, then 7 is added: the product of 2 and 8, plus 7.',
    solutions: [
      { title: 'Way 1: Read the structure', steps: ['With no parentheses, PEMDAS multiplies 2 × 8 first.', 'Then 7 is added to that product.', 'So the words are "the product of 2 and 8, plus 7".'] },
      { title: 'Way 2: Test with values', steps: ['2 × 8 + 7 = 16 + 7 = 23.', 'All three "sum" choices mean 2 × (8 + 7) = 30.', 'Only the product phrase gives 23, so it matches.'] },
    ] },
  { id: 'oa-50', domain: '5.OA', standard: '5.OA.1', tier: 3, type: 'numeric',
    prompt: 'Evaluate: 3 + 6 × {10 − [2 + (4 ÷ 2)]}', answer: '39', acceptable: ['39'],
    hints: ['Innermost first: 4 ÷ 2 = 2.', 'Then 2 + 2 = 4; 10 − 4 = 6; 6 × 6 = 36; + 3.'],
    explanation: 'Inside-out: 4 ÷ 2 = 2; 2 + 2 = 4; 10 − 4 = 6; 6 × 6 = 36; 3 + 36 = 39.',
    solutions: [
      { title: 'Way 1: Work inside-out', steps: ['Innermost parentheses: 4 ÷ 2 = 2.', 'Brackets: 2 + 2 = 4.', 'Braces: 10 − 4 = 6.', 'Multiply then add: 6 × 6 = 36, and 3 + 36 = 39.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 3 + 6 × {10 − [2 + (4 ÷ 2)]}.', 'It becomes 3 + 6 × {10 − [2 + 2]}, then 3 + 6 × {10 − 4}.', 'Then 3 + 6 × 6 = 3 + 36.', '3 + 36 = 39.'] },
    ] },
  { id: 'oa-51', domain: '5.OA', standard: '5.OA.3', tier: 3, type: 'multiple-choice',
    prompt: 'Pattern x adds 1 starting at 0; pattern y adds 3 starting at 0. The pairs (0, 0), (1, 3), (2, 6), (3, 9) are plotted. Which point comes next?',
    diagram: { kind: 'coordinate', points: [{ x: 0, y: 0 }, { x: 1, y: 3 }, { x: 2, y: 6 }, { x: 3, y: 9 }], max: 12 },
    choices: ['(4, 12)', '(4, 10)', '(12, 4)', '(3, 12)'], answer: '(4, 12)',
    hints: ['Apply each rule once more: x + 1 and y + 3.', 'After (3, 9), x becomes 4 and y becomes 12.'],
    explanation: 'x goes 3 → 4 and y goes 9 → 12, so the next point is (4, 12).',
    solutions: [
      { title: 'Way 1: Apply both rules', steps: ['The x pattern adds 1: after 3 comes 4.', 'The y pattern adds 3: after 9 comes 12.', 'The next point is (4, 12).'] },
      { title: 'Way 2: Use the relationship', steps: ['In every pair, y is 3 times x: 3 = 3 × 1, 6 = 3 × 2, 9 = 3 × 3.', 'When x = 4, y = 3 × 4 = 12.', 'So the next point is (4, 12).'] },
      { title: 'Way 3: Follow the line of points', steps: ['The plotted points climb in a straight line, over 1 and up 3 each time.', 'From (3, 9), one more step lands on (4, 12).'] },
    ] },
  { id: 'oa-52', domain: '5.OA', standard: '5.OA.1', tier: 4, type: 'numeric',
    prompt: 'Evaluate: 2 × {4 + 3 × [10 − (2 + 4)]}', answer: '32', acceptable: ['32'],
    hints: ['Innermost first: 2 + 4 = 6.', 'Then 10 − 6 = 4; 3 × 4 = 12; 4 + 12 = 16; × 2.'],
    explanation: 'Inside-out: 2 + 4 = 6; 10 − 6 = 4; 3 × 4 = 12; 4 + 12 = 16; 2 × 16 = 32.',
    solutions: [
      { title: 'Way 1: Work inside-out', steps: ['Innermost parentheses: 2 + 4 = 6.', 'Brackets: 10 − 6 = 4.', 'Inside the braces, multiply first: 3 × 4 = 12, then 4 + 12 = 16.', 'Finally 2 × 16 = 32.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with 2 × {4 + 3 × [10 − (2 + 4)]}.', 'It becomes 2 × {4 + 3 × [10 − 6]}, then 2 × {4 + 3 × 4}.', 'Multiply inside: 2 × {4 + 12} = 2 × 16.', '2 × 16 = 32.'] },
    ] },
  { id: 'oa-53', domain: '5.OA', standard: '5.OA.1', tier: 4, type: 'multiple-choice',
    prompt: 'Which placement of parentheses makes 6 + 6 ÷ 6 + 6 equal 8?',
    choices: ['(6 + 6) ÷ 6 + 6', '6 + 6 ÷ (6 + 6)', '6 + (6 ÷ 6) + 6', '(6 + 6) ÷ (6 + 6)'], answer: '(6 + 6) ÷ 6 + 6',
    hints: ['Without parentheses, 6 + 1 + 6 = 13.', 'Try to build 2 + 6.'],
    explanation: '(6 + 6) ÷ 6 + 6 = 12 ÷ 6 + 6 = 2 + 6 = 8.',
    solutions: [
      { title: 'Way 1: Work backward from 8', steps: ['8 could be 2 + 6, and 2 = 12 ÷ 6.', '12 comes from 6 + 6, so group it: (6 + 6) ÷ 6 + 6.', 'Check: 12 ÷ 6 + 6 = 2 + 6 = 8.'] },
      { title: 'Way 2: Test every choice', steps: ['(6 + 6) ÷ 6 + 6 = 2 + 6 = 8 — it works.', '6 + (6 ÷ 6) + 6 = 6 + 1 + 6 = 13.', '(6 + 6) ÷ (6 + 6) = 12 ÷ 12 = 1, and 6 + 6 ÷ (6 + 6) is 6 and a half.', 'Only the first choice makes 8.'] },
    ] },
  { id: 'oa-54', domain: '5.OA', standard: '5.OA.2', tier: 4, type: 'constructed',
    prompt: 'Write an expression (do not solve) for: "subtract the sum of 4 and 6 from 30, then divide the result by 2".',
    answer: '(30 − (4 + 6)) ÷ 2', acceptable: ['(30-(4+6))/2', '(30−(4+6))÷2', '[30−(4+6)]÷2', '[30-(4+6)]/2', '(30-10)/2'],
    hints: ['"Subtract the sum of 4 and 6 from 30" is 30 − (4 + 6).', 'The WHOLE result is divided by 2, so group it again.'],
    explanation: 'Group twice: (30 − (4 + 6)) ÷ 2 — the sum first, then the whole difference is divided.',
    solutions: [
      { title: 'Way 1: Translate piece by piece', steps: ['"The sum of 4 and 6" means (4 + 6).', '"Subtract it from 30" means 30 − (4 + 6).', '"Then divide the result by 2" wraps the whole thing: (30 − (4 + 6)) ÷ 2.'] },
      { title: 'Way 2: Check with values', steps: ['The story says: 4 + 6 = 10, then 30 − 10 = 20, then 20 ÷ 2 = 10.', '(30 − (4 + 6)) ÷ 2 = (30 − 10) ÷ 2 = 20 ÷ 2 = 10 — it matches.', 'Without the outer group, 30 − 10 ÷ 2 would be 30 − 5 = 25, which is wrong.'] },
    ] },
  { id: 'oa-55', domain: '5.OA', standard: '5.OA.3', tier: 4, type: 'multiple-choice',
    prompt: 'Pattern A starts at 2 and adds 2: 2, 4, 6, 8. Pattern B starts at 6 and adds 2: 6, 8, 10, 12. The pairs (A, B) are plotted. What is the relationship?',
    diagram: { kind: 'coordinate', points: [{ x: 2, y: 6 }, { x: 4, y: 8 }, { x: 6, y: 10 }, { x: 8, y: 12 }], max: 12 },
    choices: ['B is always 4 more than A', 'B is always 3 times A', 'B is always 2 times A', 'B is always 6 more than A'], answer: 'B is always 4 more than A',
    hints: ['Subtract each A term from its B term.', '6 − 2 = 4, 8 − 4 = 4 …'],
    explanation: 'Both add 2, but B starts 4 higher, so every B term is exactly 4 more than A.',
    solutions: [
      { title: 'Way 1: Subtract each pair', steps: ['6 − 2 = 4, 8 − 4 = 4, 10 − 6 = 4, 12 − 8 = 4.', 'The gap is 4 every single time.', 'So B is always 4 more than A.'] },
      { title: 'Way 2: Compare the rules', steps: ['Both patterns add 2, so they grow at the same speed.', 'B starts at 6 and A starts at 2 — a head start of 4.', 'The head start never changes, so B is always 4 more than A.'] },
      { title: 'Way 3: Test the times choices', steps: ['Is B = 3 × A? It works for (2, 6), but 3 × 4 = 12, not 8.', 'Is B = 2 × A? 2 × 4 = 8 works, but 2 × 6 = 12, not 10.', 'Only "4 more" fits every pair.'] },
    ] },
  { id: 'oa-56', domain: '5.OA', standard: '5.OA.1', tier: 4, type: 'numeric',
    prompt: 'Evaluate: [60 ÷ (4 + 8)] × 7 − 5', answer: '30', acceptable: ['30'],
    hints: ['Innermost first: 4 + 8 = 12.', '60 ÷ 12 = 5; 5 × 7 = 35; then − 5.'],
    explanation: '4 + 8 = 12; 60 ÷ 12 = 5; 5 × 7 = 35; 35 − 5 = 30.',
    solutions: [
      { title: 'Way 1: Work inside-out', steps: ['Innermost parentheses: 4 + 8 = 12.', 'Brackets: 60 ÷ 12 = 5.', 'Multiply: 5 × 7 = 35.', 'Subtract: 35 − 5 = 30.'] },
      { title: 'Way 2: Rewrite after each step', steps: ['Start with [60 ÷ (4 + 8)] × 7 − 5.', 'It becomes [60 ÷ 12] × 7 − 5, then 5 × 7 − 5.', 'Multiply before subtracting: 35 − 5 = 30.'] },
    ] },
  { id: 'oa-57', domain: '5.OA', standard: '5.OA.2', tier: 4, type: 'multiple-choice',
    prompt: 'Without computing, which expression has the GREATEST value?',
    choices: ['2 × (50 + 30)', '(50 + 30) ÷ 2', '50 + 30', '50 + 30 − 2'], answer: '2 × (50 + 30)',
    hints: ['Every choice is built from the same sum, 50 + 30.', 'Which choice makes the sum BIGGER?'],
    explanation: 'Doubling the sum beats halving it, leaving it alone, or subtracting 2 — so 2 × (50 + 30) is greatest.',
    solutions: [
      { title: 'Way 1: Compare to the sum', steps: ['Call the sum S = 50 + 30.', '2 × S doubles it, S ÷ 2 halves it, S stays the same, and S − 2 shrinks it a little.', 'Only doubling makes it bigger, so 2 × (50 + 30) is greatest.'] },
      { title: 'Way 2: Verify by computing', steps: ['50 + 30 = 80.', 'The choices give 160, 40, 80, and 78.', '160 is the largest, so 2 × (50 + 30) wins.'] },
    ] },
  { id: 'oa-58', domain: '5.OA', standard: '5.OA.3', tier: 4, type: 'numeric',
    prompt: 'A pattern follows the rule "multiply x by 2, then add 1". The points (1, 3), (2, 5), and (3, 7) are shown. What is y when x = 9?',
    diagram: { kind: 'coordinate', points: [{ x: 1, y: 3 }, { x: 2, y: 5 }, { x: 3, y: 7 }], max: 10 },
    answer: '19', acceptable: ['19'],
    hints: ['Apply the rule to x = 9.', '2 × 9 = 18, then add 1.'],
    explanation: 'y = 2 × 9 + 1 = 19.',
    solutions: [
      { title: 'Way 1: Apply the rule', steps: ['The rule says multiply x by 2, then add 1.', '2 × 9 = 18.', '18 + 1 = 19, so y = 19.'] },
      { title: 'Way 2: Check the rule, then use it', steps: ['Test the points: 2 × 1 + 1 = 3, 2 × 2 + 1 = 5, 2 × 3 + 1 = 7 — the rule fits.', 'So for x = 9, y = 2 × 9 + 1 = 19.'] },
      { title: 'Way 3: Count the jumps', steps: ['Each time x goes up by 1, y goes up by 2.', 'From (3, 7) to x = 9 is 6 jumps, so y adds 6 × 2 = 12.', '7 + 12 = 19, so y = 19.'] },
    ] },
  { id: 'oa-59', domain: '5.OA', standard: '5.OA.2', tier: 4, type: 'constructed',
    prompt: 'Without adding, write an expression that is exactly 10 times as large as 215 + 379.',
    answer: '10 × (215 + 379)', acceptable: ['10*(215+379)', '10×(215+379)', '(215+379)×10', '(215+379)*10'],
    hints: ['You do NOT need the value of 215 + 379.', 'Multiply the whole sum, as one group, by 10.'],
    explanation: 'Group the sum and multiply: 10 × (215 + 379) — no adding required.',
    solutions: [
      { title: 'Way 1: Think in chunks', steps: ['Treat (215 + 379) as one chunk.', 'Ten times that chunk is written 10 × (215 + 379).', 'The parentheses keep the sum together, so no adding is needed.'] },
      { title: 'Way 2: Check why parentheses matter', steps: ['Without parentheses, 10 × 215 + 379 multiplies only the 215.', 'That is not 10 times the whole sum.', 'So the answer must be 10 × (215 + 379).'] },
    ] },
  { id: 'oa-60', domain: '5.OA', standard: '5.OA.1', tier: 4, type: 'multiple-choice',
    prompt: 'Jin evaluated 40 − 2 × [9 − (2 + 3)] and got 152. What was his mistake?',
    choices: ['He subtracted 40 − 2 before multiplying', 'He added 2 + 3 incorrectly', 'He forgot the brackets entirely', 'Nothing — 152 is correct'], answer: 'He subtracted 40 − 2 before multiplying',
    hints: ['Find the correct value first: the bracket equals 4.', 'How could Jin have gotten 152? Try (40 − 2) × 4.'],
    explanation: 'Correct: 2 + 3 = 5, 9 − 5 = 4, 2 × 4 = 8, 40 − 8 = 32; Jin did (40 − 2) × 4 = 152 by subtracting first.',
    solutions: [
      { title: 'Way 1: Find the correct answer first', steps: ['Innermost: 2 + 3 = 5, then 9 − 5 = 4.', 'Multiply before subtracting: 2 × 4 = 8.', '40 − 8 = 32, so 152 is wrong.'] },
      { title: 'Way 2: Rebuild the mistake', steps: ['Ask: what steps give 152?', 'Subtracting first gives 40 − 2 = 38, and 38 × 4 = 152 — that matches Jin.', 'So his mistake was doing 40 − 2 before the multiplication.'] },
    ] },
];
